### ISSUE TITLE
radio.net

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#1]
### List the website(s) where you encounter issues with ABP filters 

```
http://www.radio.at/
http://www.radio.de/
http://www.radio.dk/
http://www.radio.es/
http://www.radio.fr/
http://www.radio.it/
http://www.radio.net/
http://www.radio.pl/
http://www.radio.pt/
http://www.radio.se/
```

### Define the problem 

unblocked ad-defend ads

### Screenshot(s)

* http://i.imgur.com/igrY3yT.png

### List all of your filter lists

EasyList
EasyPrivacy
Fanboy's Annoyances

### Tell us about your system configuration 

- Operating system and version: Manjaro 17
- Browser and version: Firefox 61 / Chromium 67
- Adblock Plus version: 3.2

### Other details 

https://forums.lanik.us/viewtopic.php?f=62&t=38653
https://git.io/fN8xm

**Comment by wizmak** [comment]
Should be fixed now in ABP 3.3

**Comment by smed79** [comment]
Ads are still there.

* https://i.imgur.com/gQDyTzi.png

**Comment by smed79** [comment]
Ads are still there https://i.imgur.com/gQDyTzi.png

**Comment by smed79** [comment]
An update is required here.

**Comment by smed79** [comment]
`radio.at,radio.de,radio.dk,radio.es,radio.fr,radio.it,radio.net,radio.pl,radio.pt,radio.se#$#abort-on-property-read canRunAds`

@wizmak
