### ISSUE TITLE
canberratimes.com.au

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#10]
**List the website(s) where you encounter issues with ABP filters**

- `https://www.canberratimes.com.au/`

**Define the problem**

-  ad-reinsertion

**Tell us about your system configuration**

- Operating system and version: Manjaro 17
- Browser and version: Firefox 62 / Chromium 69
- Adblock Plus version: 3.3.1

**List all of your filter lists**

- ABP filters
- EasyList
- EasyPrivacy
- Fanboy's Annoyances
- Adblock Warning Removal List

**Other details**

- https://github.com/uBlockOrigin/uAssets/issues/3431

**Comment by wizmak** [comment]
Does not seem to be an issue any more.
