### ISSUE TITLE
yts.mx

### ISSUE THREAD

**Issue by tripkmh** [abp-filters/abp-filters-anti-cv#1040]
### List the website(s) where you encounter issues with ABP filters 

``https://yts.mx``
``https://yts.mx/movies/the-search-for-freedom-2015``

### Define the problem 

This filter breaks the functionality: ytstv.me,yts.do,yts.mx,yts.movie,yts.rs#$#abort-on-property-read atob; abort-on-property-read setInterval;

- Quick search from header not doing any action, not returning results
- Login, Register from header not showing the modal
- Download button from inner page not doing any action when clicked
- Other functionalities broken because of the same filter (available after login)

### Screenshot(s) 
![Capture1](https://user-images.githubusercontent.com/106953747/172549996-50a05e21-ac44-42b6-8391-267cac696a1a.PNG)
![Capture2](https://user-images.githubusercontent.com/106953747/172549998-a5561bcc-bcb5-45c0-af3d-79b55d173859.PNG)
![Capture3](https://user-images.githubusercontent.com/106953747/172550000-0b2978e6-345e-477e-88dc-946724f3afba.PNG)

### List all of your filter lists 

Anti-Circumvention filter

### Tell us about your system configuration 

- Operating system and version: Windows 8.1
- Browser and version: Chrome 101
- Adblock Plus version: 4.46.2

**Comment by manuel-martinez-dev** [comment]
hello, 
thanks for the report.
please make sure to update your lists manually... if problem persists ,please create a new issue.
