### ISSUE TITLE
NSFW txxx.com

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#107]
**Website**

* **NSFW** txxx\.com (search page)

**Define the problem**

* transparent ad link

**Screenshot**

* https:\/\/vgy.me/3MRbNh.png

**HTML**

* https:\/\/pastebin.com/3N6MRGVv

**Fix**
```
txxx.com#$#abort-on-property-read BetterJsPop
```

**Comment by smed79** [comment]
@wizmak An update to block the popunder is required here.

**Comment by smed79** [comment]
@wizmak add `txxx.com#$#abort-on-property-read open`

**Comment by smed79** [comment]
@wizmak popunder, add
- `txxx.com#$#abort-on-property-read adver`

**Comment by smed79** [comment]
@wizmak can you reproduce the popunder here?

**Comment by wizmak** [comment]
> can you reproduce the popunder here?

@smed79 Yes I can, will see if I can push something.
