### ISSUE TITLE
sdamgia.ru

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#109]
Please add a snippet `sdamgia.ru#$#abort-on-property-read Ya`

https://bio-ege.sdamgia.ru/
https://i.imgur.com/TjcOPoV.jpg

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace: `sdamgia.ru#$#abort-on-property-read Ya`

To: `sdamgia.ru#$#abort-on-property-read Object.prototype.AdvManager`

**Comment by dimisa-RUAdList** [comment]
@mile-ne 
@wizmak 
Please add: `abort-on-property-read Object.prototype.adUsageStorageVars`

**Comment by dimisa-RUAdList** [comment]
@mile-ne
Please add: `abort-on-property-read Object.prototype.isAllowedRepeatAds`

**Comment by dimisa-RUAdList** [comment]
@monzta 
Please add: `abort-on-property-read Object.prototype.__confirmBlocks`

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Please add: `abort-on-property-read Object.prototype.allowRepeatAds`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `abort-on-property-read Object.prototype.AdblockCookieMatchingType`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `abort-on-property-read Object.prototype.getSkipBanner`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `abort-on-property-read Object.prototype.getAdSessionId`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `abort-on-property-read Object.prototype.AdvManagerLoaderRender`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: 
`abort-on-property-read Object.prototype.Direct`
`abort-on-property-read Object.prototype.isNewLoader`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `abort-on-property-read Object.prototype.getYaContext`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace everything with: `abort-on-property-read  Object.prototype.getYa`

**Comment by dimisa-RUAdList** [comment]
@arsykan 
Please replace with: `abort-on-property-read Object.prototype.PRODUCT_MARKERS`

**Comment by arsykan** [comment]
I can't reproduce ads on gorodrabot.ru, if you could confirm.

**Comment by dimisa-RUAdList** [comment]
@arsykan 
I see ads on gorodrabot.ru and it is not blocked.
Example: `https://moskva.gorodrabot.ru/` - https://i.imgur.com/DYjPd5o.jpg
Please change the rule for this domain to: `abort-on-property-read Object.prototype.storeBlockSettings`

Further, if necessary, continue here: https://github.com/abp-filters/abp-filters-anti-cv/issues/61

**Comment by dimisa-RUAdList** [comment]
@arsykan 
@manuel-martinez-dev 
@wizmak 

Please replace: `sdamgia.ru#$#abort-on-property-read Object.prototype.adSessionId`

with: `||sdamgia.ru/$header=content-type=text/javascript`
