### ISSUE TITLE
FB posts removed on hover

### ISSUE THREAD

**Issue by hollo6** [abp-filters/abp-filters-anti-cv#1136]
### List the website(s) where you encounter issues with ABP filters 

`https://www.facebook.com/`

### Define the problem 

Posts from `https://www.facebook.com/happyfactsme/` containing articles from `https://www.happyfacts.co/` are being removed by ABP on hover over. This should not happen.
The site is being followed.
The posts are visible in feed and also on the site's own page initially, they disappear on hover over from both places (very easy to reproduce by simply opening the site's page and hovering over any post linking a happyfacts.co article).
The problem is definitely with this filter. If it is the only one enabled, the problem is present. If it is disabled, problem is not present. All other conditions unchanged.
Firefox Inspector / ABP tab doesn't show anything related to this, nothing in the log either.

### List all of your filter lists 

ABP filters

### Tell us about your system configuration 

- Operating system and version: Windows 10 Pro, Version 10.0.19041 Build 19041
- Browser and version: Firefox 102.0.1 (64-bit)
- Adblock Plus version: 3.14.1

### Other details 

This started happening a few days ago without me changing or updating anything. Just updated ABP today, not sure what version I was on before but I definitely updated it long before this started (at least a few weeks).
I do realize that based on this, it's probably a change in FB behavior but it still shouldn't affect ABP's.
It's also very weird that it only happens on hover over, resulting in a lot of mistakenly opened posts because they only disappear the moment they are being clicked on.

**Comment by manuel-martinez-dev** [comment]
Hi @hollo6 thanks for the report, 

I've updated the filterlist, could manually update on your end within the next ~30 mins or so and confirm that the issue is resolved?.

thanks again

**Comment by hollo6** [comment]
Hi,
Wow, that was fast. And it is indeed working now!
Thank you!

**Comment by manuel-martinez-dev** [comment]
Awesome! thanks for the report again.
