### ISSUE TITLE
some youtube videos blocked and not playing

### ISSUE THREAD

**Issue by hollo6** [abp-filters/abp-filters-anti-cv#1143]
### List the website(s) where you encounter issues with ABP filters 
`https://www.youtube.com/`

### Define the problem 
Some youtube videos are being blocked by ABP filters.
Some, but not all of them are getting stuck with a loading circle when clicking the play button. Others are being played just fine.
Example: `https://www.youtube.com/watch?v=8QNrEWh00dM`

### List all of your filter lists 
ABP filters

### Tell us about your system configuration 
- Operating system and version: Windows 10 Pro, Version 10.0.19041
- Browser and version: Firefox 102.0.1 (64-bit)
- Adblock Plus version: 3.14.1

### Other details 
FF Inspector ABP tab shows exactly the same blocked elements as the videos that are loaded and played correctly.
When this filter is disabled (nothing else changed), the problematic videos do load but of course with ads.

**Comment by wizmak** [comment]
Hey @hollo6 
We're unable to replicate the described issue. I want to ask if this issue occurs when restoring a previous session, after a browser restart/update, while having the option **Open previous windows and tabs** enabled. If this is not the case, it would be really helpful if you take a note of the exact scenario when this happens.

**Comment by wizmak** [comment]
> Example: https://www.youtube.com/watch?v=8QNrEWh00dM

I tried this example, and noticed nothing wrong. If you can share other videos where you have the issue, maybe it helps.

Also, when the issue occurs, does it go away after refreshing the page?

**Comment by hollo6** [comment]
Neither F5 nor ctrl+F5 helps.

Now I have started looking for more and noticed a very weird thing. What I did:
1. open a few videos in new tabs
2. go around the new tabs and check what's playing and what is not
3. find a broken one
4. copy the link and open it in a new instance
5. it starts playing exactly once in the new instance, then never again - not in the old window and not in any new windows after that

examples:
https://www.youtube.com/watch?v=FnOlrW1VvI8
https://www.youtube.com/watch?v=mo619n0QETA

During this test, I have opened 12 videos and these 2 were broken out of the 12.

**Comment by wizmak** [comment]
This is helpful, now I could reproduce the issue after opening that many videos at the same time. This is not a filter issue, maybe a browser/cache issue, in any case, force reloading (CTRL + SHIFT + R ) makes the issue go away for me, can you try it?

**Comment by hollo6** [comment]
I think ctrl+F5 and ctrl+shift+R is the same, but I tried it anyway and doesn't help.
Disabling ABP filters (and simple f5) makes it load (but with ads) and enabling it again makes it not load ever again.

**Comment by wizmak** [comment]
> I think ctrl+F5 and ctrl+shift+R are the same

True, unsure why it works for me and not you.

> I didn't open all 12 at once but one at a time (I was clicking them one after the other and new tabs load in the background so they never actually try to start playing until I click the play button)

Thanks for clarification, this is what I also did.

I have another question, does the issue also occur if you allow videos to autoplay?

**Comment by hollo6** [comment]
> I have another question, does the issue also occur if you allow videos to autoplay?

Yes, I have just tried setting media.autoplay.enabled to true and also disabled the addon that does it and nothing changes (also restarted FF just in case).
Once a video is broken, it stays that way.

**Comment by hollo6** [comment]
New discoveries:
The behavior is slightly different in normal mode and incognito mode. I have tried the latter with only ABP enabled and all my addons enabled as well, seems to make no difference.
It is still specific to individual videos but the ones prone to this issue behave the same.

In normal mode, I can manually break them by setting the Quality to Auto.
When the quality is manually set to anything else, they are being played. When it is set to Auto, they are not.
Once they are broken, nothing fixes them. They can only be played in Auto quality when ABP filters is disabled.

In both normal and incognito mode, I can reproduce the issue by opening the video and quickly clicking on it (either the video or the play button). Easier to reproduce by opening multiple tabs, selecting one of them then clicking on play.

The broken videos will play fine again in incognito mode after restarting the browser.

In incognito mode, I can only reproduce this with the quick-open-then-play method, changing the quality seems to not break them there but this could also be because even the former method works only in ~20% of the cases*, so it might just take a lot more tries.
*there are times (one or more instances running in incognito mode) when it happens and other times when it does not - this is being reset when all incognito mode instances are closed and a new one is started

**Comment by wizmak** [comment]
Thank you for sharing your findings in such detail.

This issue does not seem specific to ABP/anti-cv-list though, please check [this thread on reddit](https://www.reddit.com/r/uBlockOrigin/comments/wrfcqq/youtube_is_broken_for_me/) for apparently the same issue.

**Comment by hollo6** [comment]
Thanks, it indeed seems to be the same issue.
I believe that it is some kind of clash between content blockers and cookies.
Since the problem always "fixes itself" in incognito mode after restarting the browser and also can be done in normal mode by deleting all yt cookies, it obviously has something to do with cookies but only when a content blocker is present (ABP and apparently ublock too).

I was also able to narrow it down and also find a fix.

There are 3 different ways to deal with yt cookies when it pops up:
1) clicking "Reject all" on the popup right away
2a) clicking "More options", then on the subsequent page (Personalisation settings and cookies), "Reject all" 
2b) on that page, choosing a setting in the first two boxes (yt history, ad personalisation - tbh I've only tried Off, don't know what would happen with On), then clicking "Reject all"

This issue happens only in scenario 2a) - i.e. when on the "Personalisation settings and cookies" page, "YouTube History" and "Ad personalisation on YouTube" settings are not selected.
Apparently in this case, these settings can get stuck in some undefined state, my guess is that the ad personalisation setting being undefined confuses content blockers at some later stage.

**Comment by wizmak** [comment]
Thanks again for sharing your findings!

For me, I can't consistently reproduce the issue, no matter what scenario/steps I follow.

**Comment by hollo6** [comment]
Yeah repro is not trivial because it's video specific and goes away after excessive trying, which I think is connected to the fact that only somewhat older ones are affected.
Maybe there is some YT mechanism that changes a cache or the ads (or other blocked elements) trying to be displayed based on the number of recent views?

Anyway I'm happy to keep reproducing it if you can give me some pointers or methods of debugging / log collection.
