### ISSUE TITLE
teleportal.ua

### ISSUE THREAD

**Issue by dportvine** [abp-filters/abp-filters-anti-cv#1144]
### List the website(s) where you encounter issues with ABP filters 

`https://teleportal.ua/ua/serials/stb/i-budut-lyudi/sezon-1/seryya-1`

### Define the problem 

Ads in player

### Screenshot(s) 

<details>
<summary>Screen</summary>

![2022-08-16_121650](https://user-images.githubusercontent.com/111344219/184844327-6fca5fd1-245c-4808-a064-2822a27f6ccc.png)
</details>

### List all of your filter lists 

<details>
<summary>Screen</summary>

![2022-08-16_121715](https://user-images.githubusercontent.com/111344219/184844308-054e324a-65ca-4d55-9460-f4210036eac0.png)
</details>

### Tell us about your system configuration 

- Operating system and version: Windows 10 Pro 21H2 x64
- Browser and version: Google Chrome 104.0.5112.81
- Adblock Plus version: Adblock Plus 3.14.1

### Other details 
Maybe this rule `||starlight.digital/get-playlist-ad/hls-vod/files/*.mp4/*_AdBlock^$xmlhttprequest,rewrite=abp-resource:blank-text,domain=starlight.digital`

**Comment by dimisa-RUAdList** [comment]
@dportvine 
This rule cannot be applied. It will break any multiframe player.

Example: `https://serial.ictv.ua/ru/videos/pes-6-sezon-29-seryya/`

Correct rule: `changeua.com,ictv.ua,inter.ua,k1.ua,novy.tv,ntn.ua,starlight.digital,stb.ua,teleportal.ua#$#override-property-read Object.prototype.CreativeAdBreaks undefined`

**Comment by dimisa-RUAdList** [comment]
@manuel-martinez-dev 
Will you add this rule?

**Comment by manuel-martinez-dev** [comment]
@dimisa-RUAdList just added it, it does indeed not seem to break the sites. :)
thanks again!

**Comment by dimisa-RUAdList** [comment]
@wizmak 
@manuel-martinez-dev 

Please replace with: `override-property-read Object.prototype.BannerManager undefined`

**Comment by dportvine** [comment]
@Aslatiel
@delta9A

**Comment by dimisa-RUAdList** [comment]
@Aslatiel
@delta9A
@manuel-martinez-dev
@wizmak

Please replace with: `override-property-read Object.prototype.ottAdvExt undefined`

**Comment by dportvine** [comment]
They bypass ABP. You can delete the rule.
