### ISSUE TITLE
seekingalpha.com 3/4 screen ad

### ISSUE THREAD

**Issue by nathanwray** [abp-filters/abp-filters-anti-cv#1145]
### List the website(s) where you encounter issues with ABP filters 

`seekingalpha.com`

### Define the problem 

Seeking Alpha has been running 3/4 page ads for their Pro service on the home page, which ABP doesn't remove

### Screenshot(s) 

![image](https://user-images.githubusercontent.com/8738395/184909455-84b4469a-425f-4cbd-a2af-0075633b996a.png)

### List all of your filter lists 

![image](https://user-images.githubusercontent.com/8738395/184909624-c4e25d89-6496-43f3-a52a-0224b890931e.png)

### Tell us about your system configuration 

- Operating system and version: 
Edition	Windows 10 Pro
Version	21H2
Installed on	‎5/‎11/‎2021
OS build	19044.1889
Experience	Windows Feature Experience Pack 120.2212.4180.0

- Browser and version: 
Chrome Version 104.0.5112.81 (Official Build) (64-bit)

- Adblock Plus version: 
Version number 3.14.1

### Other details 

I've been running the following to hide this div. 

seekingalpha.com#$#hide-if-matches-xpath '//*[contains(@href,"alpha-picks/subscribe")]//parent::div//parent::div//parent::div//parent::div'

**Comment by manuel-martinez-dev** [comment]
Hi @nathanwray , 
thanks for the report, unfortunately we don't hide self promotion ads.

The filter you're applying works very well, alternatively you could swap all the `parent` and shorten the filter like so, as it should also do the same:

`seekingalpha.com#$#hide-if-matches-xpath './/*[contains(@href,"alpha-picks/subscribe")]/ancestor-or-self::div[4]'`

thanks again.
