### ISSUE TITLE
google map ads

### ISSUE THREAD

**Issue by lmarvaud** [abp-filters/abp-filters-anti-cv#1159]
### List the website(s) where you encounter issues with ABP filters 

* [map.google.com](https://www.google.com/maps/)

### Define the problem 

Google map now add ads in the map, those are often irrelevant.

### Screenshot(s) 

![Screenshot 2022-09-02 à 18 14 51](https://user-images.githubusercontent.com/24732919/188195833-f489479a-eb86-47af-9163-3f41027422ae.png)

### List all of your filter lists 

ABP filters
EasyList
EasyPrivacy
Fanboy's Social Blocking List

### Tell us about your system configuration 

- Operating system and version: 
- Browser and version: 
- Adblock Plus version: 

### Other details 

I found the corresponding API call that retrieve the ad data : https://www.google.com/maps/preview/lp?authuser=0&hl=fr&gl=fr&pb=!1m3!1sUC4SY4eAE4qHrwToyqDQDw![...]1!5m2!3b0!5e9

It worked by blocking :
> https://www.google.com/maps/preview/lp

![image](https://user-images.githubusercontent.com/24732919/188197689-183fc53b-a8d0-442f-b033-195c3d44bf2b.png)

**Comment by lmarvaud** [comment]
```
||google.com/maps/preview/lp$header=content-type=application/json
```

**Comment by wizmak** [comment]
Hey @lmarvaud 
Could you please provide the steps to follow to reproduce those ads, and highlight them on the provided screenshot?
Thanks.

**Comment by wizmak** [comment]
@lmarvaud I'll close this ticket, but please feel free to reopen if there is still an issue.
