### ISSUE TITLE
lephoceen.fr

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#116]
Hi,

**Website**

- https:\/\/www\.lephoceen\.fr/

**Define the problem**

- adikteev ads (emoteev.io) / circumvention 

**Screenshot**

- https://vgy.me/IuZHnr.png
- https://vgy.me/sQff5h.png

**List all of your filter lists**

- ABP filters
- EasyList
- EasyList FR
- EasyPrivacy
- Adblock Warning Removal List

**Tell us about your system configuration**

- Browser and version: Firefox 65 & Chromium 73
- Adblock Plus version: 3.5

**Fix**
- `lephoceen.fr#$#abort-on-property-read setInterval`

**Source**

- https://forums.lanik.us/viewtopic.php?f=91&t=42770

**Comment by wizmak** [comment]
@smed79 thanks!
