### ISSUE TITLE
ebay search broken with ABP

### ISSUE THREAD

**Issue by sfetest** [abp-filters/abp-filters-anti-cv#1171]
### List the website(s) where you encounter issues with ABP filters 

* Example - ``https://www.ebay.com/sch/i.html?_from=R40&_trksid=p2334524.m570.l1312&_nkw=walden+thoreau+first+edition&_sacat=0&LH_TitleDesc=0``

### Define the problem 

On ebay when searching, the first four items are always removed regardless of them being ads. I have to turn off ABP to see all items now.

### Screenshot(s) 
![Screen Shot 2022-09-13 at 9 24 20 AM](https://user-images.githubusercontent.com/111095622/189955398-214f186d-4eed-42f6-a466-176785de2680.png)

### List all of your filter lists 
ABP filters
EasyList

### Tell us about your system configuration 

- Operating system and version:  Mac OS X Monterey
- Browser and version: Google Chrome 105
- Adblock Plus version: 3.14.2

### Other details 
This [commit](https://github.com/abp-filters/abp-filters-anti-cv/commit/47a537987dbd083aa9a7eaed44133de9be889619) is likely the root cause of the issue.

**Comment by wizmak** [comment]
@sfetest Issue should be fixed now, you can update your _ABP filters_ list manually in about 10 minutes to get the fix.
Thanks for reporting!
