### ISSUE TITLE
tv.vg.no

### ISSUE THREAD

**Issue by DandelionSprout** [abp-filters/abp-filters-anti-cv#1179]
### List the website(s) where you encounter issues with ABP filters 

* `https://tv.vg.no/video/243907/verdensrekordforsoek-stor-sjanse-for-at-kroppsdeler-ryker`

### Define the problem 

One of Norway's biggest websites has video ads that have been concluded by multiple listmakers to be impossible to block without snippets, since any attempt with regular blocking rules or `redirect:abp-resource` causes the video to show a black screen.

This situation outright requires snippets to fix, which are still considered "ABP Filters"-only territory; and https://github.com/abp-filters/abp-filters-hotfix/pull/6#issuecomment-1255845950 told me to submit it here.

It is also very, *very* critical that the site does get fixed, due to the site's locally large userbase in the millions, around a third of the population.

Additional context: `https://gitlab.com/eyeo/adblockplus/abc/adblockpluscore/-/issues/224#note_1111575321`

### Screenshot(s) 

N/A at the time of writing.

### List all of your filter lists 

'Dandelion Sprout's Nordic Filters + EasyList', ABP Filters

### Tell us about your system configuration 

- Operating system and version: Windows 11 22H2 x64
- Browser and version: Vivaldi 5.4.2753.51 x64
- Adblock Plus version: 3.14.2

### Other details 

I propose `tv.vg.no#$#abort-on-property-write __AB__`, which seems to work when used in User Filters.

**Comment by manuel-martinez-dev** [comment]
Hi @DandelionSprout ,

I've pushed the filter, as it seems to be working as you mentioned, included a second option, because sometimes the proposed filter was not working.

thanks again,
