### ISSUE TITLE
Missing words in articles with Ablock

### ISSUE THREAD

**Issue by vybiral-tomas** [abp-filters/abp-filters-anti-cv#1183]
### List the website(s) where you encounter issues with ABP filters 

* `www.novinky.cz`

### Define the problem 

When the page is diplayed with adblock, there are some missing words. All the words are technically links and they are matched against `/clickthru?` and `?spotId=`.

### Screenshot(s) 
* with Adblock enabled:
![image](https://user-images.githubusercontent.com/109524618/193573912-74471750-dd8b-4c31-b28f-075005105a6f.png)
* without Adblock:
![image](https://user-images.githubusercontent.com/109524618/193574078-194134bc-c9d7-42b1-bea2-7bc294094720.png)
* Ablock output:
![image](https://user-images.githubusercontent.com/109524618/193574247-9e8d7a3e-1de7-4589-b9b0-1329ce227f0e.png)

### List all of your filter lists 

* Easylist
* Adblock extra filters
* Anti-Circumvention filters

### Tell us about your system configuration 

- Operating system and version: Linux (Manjaro) 5.18
- Browser and version: Firefox 105
- Adblock Plus version: using Ablock (5.1.1), but the rules are in this repository

**Comment by manuel-martinez-dev** [comment]
Hi @vybiral-tomas thanks for report,

I've removed the culprit filters, issue should be resolved. Just manually refresh your lists within the next 30 minutes or so.

thanks again,
