### ISSUE TITLE
root-nation.com

### ISSUE THREAD

**Issue by dportvine** [abp-filters/abp-filters-anti-cv#1184]
### List the website(s) where you encounter issues with ABP filters 

`https://root-nation.com/en/articles-en/weapons-en/en-iris-t-slm/`

### Define the problem 

Clickable background ads.

### Screenshot(s) 

<details>
<summary>Screen</summary>

![2022-10-03_181034](https://user-images.githubusercontent.com/111344219/193613916-fa98286b-d23c-4556-8e1f-7882bd4db1b3.png)
</details>

### List all of your filter lists 

<details>
<summary>Screen</summary>

![2022-08-16_121715](https://user-images.githubusercontent.com/111344219/184844308-054e324a-65ca-4d55-9460-f4210036eac0.png)
</details>

### Tell us about your system configuration 

- Operating system and version: Windows 10 Pro 21H2 x64
- Browser and version: Google Chrome 106.0.5249.91
- Adblock Plus version: Adblock Plus 3.14.2

**Comment by manuel-martinez-dev** [comment]
Hi @dportvine, 
thanks for the report.

I've pushed a filter, I believe issue should be fixed.

thanks again.

**Comment by dportvine** [comment]
Thanks a lot works for me.
Can you make a link to the background or -background-?
Advertising there is different, not only for watch.
