### ISSUE TITLE
komikdewasa.me Ads 

### ISSUE THREAD

**Issue by YellowStar11** [abp-filters/abp-filters-anti-cv#1195]
### List the website(s) where you encounter issues with ABP filters 

https://komikdewasa.me

### Define the problem 
So many ads appear on the site, including gambling ad(CNN Slot) {NSFW} 

### List all of your filter lists 
-ABP Anti CV, Easylist,Easyprivacy,ABPIndo, Peter Lowe,Fanboy Annoyance

### Tell us about your system configuration 

- Operating system and version: Android 12
- Browser and version: Vivaldi Browser 5.5
- Default Adblock
 

### Other details 
That's Indonesian Website
![IMG_20221013_075031](https://user-images.githubusercontent.com/98148960/195473915-69331f21-6504-4403-b134-6d589796d9a0.jpg)

**Comment by manuel-martinez-dev** [comment]
Hi @YellowStar11,
thanks for the report.

I've pushed some filters so the issue should be resolved, please update your lists within the next hour or so.

thanks
