### ISSUE TITLE
namemc.com

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#12]
**List the website(s) where you encounter issues with ABP filters**

- `https://namemc.com/`

**Define the problem**

-  ad-reinsertion

**Ss**

-  https://vgy.me/hQwZsX.png

**Tell us about your system configuration**

- Operating system and version: Manjaro 17
- Browser and version: Firefox 62 / Chromium 69
- Adblock Plus version: 3.3.2

**List all of your filter lists**

- ABP filters
- EasyList
- EasyPrivacy
- Fanboy's Annoyances
- Adblock Warning Removal List

**Other details**

- https://forums.lanik.us/viewtopic.php?p=141091#p141091

**Comment by wizmak** [comment]
Fixed temporarily as suggested in: https://forums.lanik.us/viewtopic.php?p=141092#p141092

**Comment by smed79** [comment]
@wizmak Ads not blocked at `namemc.com`
