### ISSUE TITLE
mystream.to

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#121]
**Websites**

* https:\/\/mstream.net/2yfk82hxcyj7
* https:\/\/embed.mystream.to/gzrtbl96un07
* https:\/\/mysembed.net/cl8nc70n182e

**Problem**

* popups

**Fix**

`
mstream.net,mysembed.net,mystream.to#$#abort-on-property-read eval
`

**Other details**

* https://forums.lanik.us/viewtopic.php?f=62&t=42522

**Comment by smed79** [comment]
new domain `https://mstream.rocks/upk766kheb4p`

**Comment by wizmak** [comment]
> new domain `https://mstream.rocks/upk766kheb4p`

The filter `mstream.rocks#$#abort-on-property-read eval` breaks the play button for me.

**Comment by mapx-** [comment]
add
`mstream.rocks#$#abort-on-property-read open`

**Comment by smed79** [comment]
@wizmak add `mstream.fun`

**Comment by smed79** [comment]
@wizmak Please, add `mstream.website`
- e.g. url > `https://mstream.website/bzidsu5r96a6`

**Comment by wizmak** [comment]
There is an issue with the behaviour of `abort-on-property-*` which should be fixed as of ABP 3.10, will re-add once it's a live.
