### ISSUE TITLE
userload.co

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#1216]
**website**

* `https://tubeload.co/e/0sezrgrxyuis/` or (`bf1qhmpvdtge`)

**problem**

* popups

**Comment by edivaniadc** [comment]
Hi @smed79 can you check again on your side. I'm no longer able to reproduce the popups ads, maybe there were some recent changes in EL that blocked these.

**Comment by manuel-martinez-dev** [comment]
Hi @smed79,
can you share the steps on how to reproduce these popups? (as well as other details if possible)
thanks.

**Comment by smed79** [comment]
Check this link `https://tubeload.co/e/bf1qhmpvdtge/`

To reproduce, click anywhere ...
