### ISSUE TITLE
etsy.com market page without any card

### ISSUE THREAD

**Issue by canterocrafting** [abp-filters/abp-filters-anti-cv#1218]
### List the website(s) where you encounter issues with ABP filters 

* Etsy.com `https://www.etsy.com/market/leather_keychain`

### Define the problem 

Etsy has these special pages for specific products, with the ABP turned on I am not seeing any cards at all, regardless of being ads.

### Screenshot(s) 

Turned on:
![image](https://user-images.githubusercontent.com/117848468/200887148-494b64ec-a2da-417c-86d8-dc079f55aab3.png)
Turned off:
![image](https://user-images.githubusercontent.com/117848468/200887238-5f59141e-6e63-4828-b3dc-91c18396c729.png)

### List all of your filter lists 

* ABP filters
* EasyList
* EasyPrivacy

### Tell us about your system configuration 

- Operating system and version: macOS Monterrey
- Browser and version: Chrome 107
- Adblock Plus version: 3.14.2

**Comment by manuel-martinez-dev** [comment]
Hi @canterocrafting,

thanks for reporting, please manually update your filter lists on the extension, issue should be resolved.

thanks again.
