### ISSUE TITLE
motorpage.ru

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#1238]
Please add: `motorpage.ru#$#json-prune '0.BannerId 1.BannerId 2.BannerId 3.BannerId 4.BannerId 5.BannerId 6.BannerId'`

Example: `http://www.motorpage.ru/MINI/news/hjetchbek_mini_osnastili_motorom_v8.html`

**Comment by edivaniadc** [comment]
Hi @dimisa-RUAdList can you please provide more detail how we can reproduce this issue? I couldn't find the ad with `RuAdList+EasyList` enabled. Thank you in advance.

**Comment by dimisa-RUAdList** [comment]
You need to open the network request log. There you will immediately see third-party ad frames, which can change due to rotation. Right now it's `https://discovery-russia.ru/showtime/Far-Cry-Primal-2.html`. The network request `http://www.motorpage.ru/br/` is responsible for the rotation of advertising frames, but we cannot block it with the classic rule `||motorpage.ru/br/`, since in this case the blocker detector will work, which block page scrolling.
<details>
<summary>Screenshot(s)</summary>

![motorpage](https://user-images.githubusercontent.com/20126984/204056183-ce9188d3-6f95-4d65-af38-a4ef1e83f542.jpg)

</details>

To correctly block the rotation of advertising frames, you need to use the rule ~>
`motorpage.ru#$#json-prune '0.BannerId 1.BannerId 2.BannerId 3.BannerId 4.BannerId 5.BannerId 6.BannerId'`
