### ISSUE TITLE
A: https://theeminenceinshadowmanga.com/

### ISSUE THREAD

**Issue by eporubin** [abp-filters/abp-filters-anti-cv#1256]
### List the website(s) where you encounter issues with ABP filters 

* `https://theeminenceinshadowmanga.com/`

### Define the problem 

During my routine check of the ABB issue report I came across this website which does redirect me in another tab and displays ads on previous tab then trying to open any chapter. It seems to be cause by the inline-script covered by your team and the filter `theeminenceinshadowmanga.com#$#abort-current-inline-script document.querySelectorAll popMagic` seems to fix the issue

### List all of your filter lists 
ABP filters + EasyList
VPN to UK

### Tell us about your system configuration 

- Operating system and version: macOS Ventura 13.0.1
- Browser and version: Version 108.0.5359.94 (Official Build) (arm64)
- Adblock Plus version:  3.15.2

**Comment by wizmak** [comment]
@eporubin You're welcome :)
