### ISSUE TITLE
eBay search pages made sluggish by recent filter change

### ISSUE THREAD

**Issue by microshnik** [abp-filters/abp-filters-anti-cv#1266]
### List the website(s) where you encounter issues with ABP filters 

Any eBay.com search results page with a large number of results; barely detectable at 50, very pronounced around 180, as seen here:
* `https://www.ebay.com/sch/i.html?_sacat=1&_nkw=%28piemontite%2Cpiedmontite%2Cepidote%29+%28artonvilla%2Cmessina%2Cmusina%2Cafrica%29+-polished+-donut+-prehnite+-mozambique+-zoisite&_blrs=recall_filtering`

### Define the problem 

Periods of elevated CPU usage and unresponsive page (but browser still responsive) for as much as 30 seconds, triggered by page load, page scroll, window resize, link click, and page unload.  When scrolling, pages are blank past a certain (undetermined) point until CPU usage drops and loaded content is then displayed.

### Screenshot(s) 

Scrolling down:
![image](https://user-images.githubusercontent.com/65793839/207769590-e973385c-73de-4448-8585-4e6086fa7fd5.png)
Scrolling up:
![image](https://user-images.githubusercontent.com/65793839/207769618-f1c17cc3-d925-4991-9ff7-299c77f4cd69.png)

### List all of your filter lists 

* ABP filters
* EasyList
* EasyPrivacy
* Fanboy's Notifications Blocking List
* Fanboy's Social Blocking List
* I don't care about cookies
* (many custom filters)

### Tell us about your system configuration 

- Operating system and version: Windows 7
- Browser and version: Firefox 102.5.0esr
- Adblock Plus version: 3.14.2

### Other details 

This started about a week ago, and after diffing an older set of filter lists from another profile against my normal set, I have traced the problem to this commit: https://github.com/abp-filters/abp-filters-anti-cv/commit/1fe80837a07af4d9e44aac8c8c7c7c306ca07186

**Comment by manuel-martinez-dev** [comment]
Hi @microshnik thanks for your report.

Could you try and update to the latest ABP version?, which is 3.15.2. Do you still notice the same issue?

**Comment by microshnik** [comment]
It is still happening with ABP updated to 3.15.2 and all subscriptions updated.

**Comment by manuel-martinez-dev** [comment]
Hi @microshnik,

thanks for getting back to us,
I've removed the filter, please manually update your filter lists, issue should be resolved in a few hours.
