### ISSUE TITLE
monoschinos2.com

### ISSUE THREAD

**Issue by Khrin** [abp-filters/abp-filters-anti-cv#1267]
On  `https://monoschinos2.com/ver/bleach-sennen-kessen-hen-episodio-10` the Disqus widget is blocked, presumably by `monoschinos2.com#$#abort-on-property-read a3klsam; abort-on-property-write JSON.parse`

**Comment by manuel-martinez-dev** [comment]
Hi @Khrin 
thanks for reporting, deleted the JSON. parse filter which seemed to be the culprit here.
