### ISSUE TITLE
search.seznam.cz

### ISSUE THREAD

**Issue by vasimi** [abp-filters/abp-filters-anti-cv#1285]
### List the website(s) where you encounter issues with ABP filters 

* `https://search.seznam.cz` (homepage)

### Define the problem 

Upon clicking element no. 1 (see screenshot below), element no. 2 should appear. However, element no. 2 gets matched by xpath `.//a[@href][text()]/ancestor::div[@class][1]/parent::div[@class][@style]` and blocked. This issue was introduced in commit [f2b2076](https://github.com/abp-filters/abp-filters-anti-cv/commit/f2b2076)

### Screenshot(s) 
![Snímek obrazovky 2023-01-17 v 17 17 52](https://user-images.githubusercontent.com/9162439/212954034-6617e7c9-934c-4325-90d7-46f71529d428.png)

### List all of your filter lists 
I specifically disabled all filters and found the specific part of the rule that blocks the element.

### Tell us about your system configuration 

- Operating system and version: macOS 13.1
- Browser and version: Chrome 109.0.5414.87
- Adblock Plus version: 5.3.3

**Comment by che0** [comment]
[tv.seznam.cz](https://tv.seznam.cz/) is completely broken with recent filters

**Comment by Aslatiel** [comment]
Hi @vasimi ,

thanks for reporting,
Issue should be resolved if you manually update your filters within the next half hour (more or less).

thanks again for reaching out.
