### ISSUE TITLE
ontivi.net, xittv.net

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#1293]
Please add:
`ontivi.net,xittv.net#$#abort-on-property-read document.head.append`

Example:
`http://ip.ontivi.net/rossiya-1tv.html`
`http://xittv.net/nash-kinoroman.html`

**Comment by dimisa-RUAdList** [comment]
@Aslatiel 
Please add:
`ontivi.net#$#abort-current-inline-script document.createElement Math.random`

clickunder

Example: `http://ip.ontivi.net/2pl28.html`

**Comment by dimisa-RUAdList** [comment]
And del: `ontivi.net,xittv.net#$#abort-on-property-read document.head.append`

**Comment by Aslatiel** [comment]
changes pushed
50f6bf3960bdd628ef5bf1089f759de8240e0ff6

**Comment by dimisa-RUAdList** [comment]
@Aslatiel 
Please add: `tivix.co#$#abort-on-property-read open`

clickunder

Example: `http://ip.tivix.co/348-tv-m1_t1.html`
