### ISSUE TITLE
Blocked discussions on novinky, seznamzpravy

### ISSUE THREAD

**Issue by herrdickinson** [abp-filters/abp-filters-anti-cv#1294]
### List the website(s) where you encounter issues with ABP filters 

* novinky.cz, seznamzpravy.cz, etc.

### Define the problem 

Hello,

this new rule: `||seznam.cz/*/static/js/ssp.js^$domain=seznam.cz`
which was commited in this set of rules: https://github.com/abp-filters/abp-filters-anti-cv/commit/d51487645156a01fae1d0afeeac323ff15cef8e0#diff-cf2d21f8e8753740a0a3ae8134b85836bae6aae59ae2604222dbbe13b9aec791R324
made by @Aslatiel

blocks every diskuse.seznam.cz. Here is a screenshot of Adblock log on novinky.cz:

![image](https://user-images.githubusercontent.com/103173784/216760870-7a7225fe-4c5f-43f6-8e3d-a16770d8b4c9.png)

Discussion looks like this:

![image](https://user-images.githubusercontent.com/103173784/216760933-c553d2e1-eab3-485a-824b-11eb24349f14.png)

Please remove this new rule. This does not block ads but cripple the website.

Thank you for your time!

Best regards,

HD

**Comment by Aslatiel** [comment]
Hi @herrdickinson 

thanks for reporting.

Issue should be fixed, please update your filter lists manually.

thanks again.
