### ISSUE TITLE
mmminigames.mail.ru

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#1299]
Please add: `mmminigames.mail.ru#$#abort-current-inline-script addEventListener advRefreshInterval`

Example (authorization required): `https://my.mail.ru/apps/258999`

**Comment by delta9A** [comment]
@dimisa-RUAdList can you please confirm if domain is indeed `mmminigames.mail.ru` or `minigames.mail.ru`?

**Comment by dimisa-RUAdList** [comment]
There is no error, these are different domains.

**Comment by delta9A** [comment]
> @dimisa-RUAdList can you please confirm if domain is indeed `mmminigames.mail.ru` or `minigames.mail.ru`?

Thanks for confirming that. Filter added https://github.com/abp-filters/abp-filters-anti-cv/commit/efaa826a8be0d3a291dacadeed8d9e5f27c99b83
