### ISSUE TITLE
vuzlit.com

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#1307]
Please add: `bstudy.net,studbooks.net,studme.org,studref.com,studwood.net,vuzlit.com,xstud.org#$#abort-on-property-read abl`

Example: `https://vuzlit.com/1613140/ekspluatatsiya_mashinno-traktornogo_parka`

**Comment by dimisa-RUAdList** [comment]
Unfortunately, the rules do not work, although they should. I already reported the problem to the Eyeo developers (for the first time a year ago), and I hope they will fix the flaw as soon as possible. Until they do, we will have to look for workarounds. I propose the following:
```
bstudy.net#$#abort-on-property-read _0xddc4
studbooks.net#$#abort-on-property-read _0x8336
studme.org#$#abort-on-property-read _0x5443
studref.com#$#abort-on-property-read _0x308a
studwood.net#$#abort-on-property-read _0x8cc0
vuzlit.com#$#abort-on-property-read _0xc091
xstud.org#$#abort-on-property-read _0xd07e
```
Example:
```
https://bstudy.net/621130/agro/zernohranilische_gorizontalnymi_silosami_innovatsionnogo_tipa_obekt_intellektualnogo_monitoringa_upr

https://studbooks.net/2592742/pedagogika/_missiya_universiteta_kak_nauchno-pedagogicheskiy_kontsept_epohi_postindustrialnogo_razvitiya

https://studme.org/1584072019664/bankovskoe_delo/banki_i_bankovskoe_delo

https://studref.com/415278/etika_i_estetika/predislovie

https://studwood.net/2556349/ekologiya/osnovnye_fiziko-himicheskie_faktory_vodnoy_sredy

https://vuzlit.com/1613140/ekspluatatsiya_mashinno-traktornogo_parka

https://xstud.org/251522/geofizika/standarty_audita
```

**Comment by delta9A** [comment]
> Unfortunately, the rules do not work, although they should. I already reported the problem to the Eyeo developers (for the first time a year ago), and I hope they will fix the flaw as soon as possible. Until they do, we will have to look for workarounds. I propose the following:

@dimisa-RUAdList sorry to hear about that. Would you please share the issue/report link so we can look for an update? Thank you.

**Comment by dimisa-RUAdList** [comment]
@delta9A 
https://gitlab.com/eyeo/snippets/-/issues/1

**Comment by dimisa-RUAdList** [comment]
@Aslatiel 
@delta9A 
@wizmak 

Please add: `ozlib.com#$#abort-on-property-read _0xb7d3`

Example: `https://ozlib.com/853610/tehnika/uzly_svyazi_podvizhnyh_punktov_upravleniya_podrazdeleniy_chastey_soedineniy_rvsn`
