### ISSUE TITLE
cq.ru - Filter rule breaks the site

### ISSUE THREAD

**Issue by volkv** [abp-filters/abp-filters-anti-cv#1326]
Hi! Legacy filter rule hides all post's content

ex: `https://cq.ru/news/gaming/v-stalker-2-poiaviatsia-novye-anomalii-i-vot-kak-oni-budut-vygliadet`

Screenshot - `https://i.imgur.com/y6OjoGu.png`

this rule:

https://github.com/abp-filters/abp-filters-anti-cv/blob/cd832cd70d1538dc7bb237b65460a3f928e9d14a/russian.txt#L78

Thanks

**Comment by Aslatiel** [comment]
Hi @volkv,

thanks for reporting.

Please update your filterlists manually, the issue should be resolved within the next hour more or less.
