### ISSUE TITLE
strategium.ru

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#1353]
Please add: `strategium.ru#$#abort-current-inline-script _ dismissAdBlock`

Example: `https://www.strategium.ru/forum/`

**Comment by delta9A** [comment]
@dimisa-RUAdList rule blocks the Adblock wall.

**Comment by dimisa-RUAdList** [comment]
```
   <script>
      ;
      (function($, _, undefined) {
         "use strict";

         ips.controller.register('adblockdetector.front.eabd.agent', {

            initialize: function() {
               var isItEnabled = false;
               this.on(document, 'click', '[data-action="dismissDetector"]', this.dismissAdBlock);
               $(document).ready(function() {
                  window.setTimeout(function() {
                     fetch('https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js')
                        .catch(function(error) {
                           if (ips.utils.cookie.get('adblock_agent_dismissed') == undefined || ips.utils.cookie.get('adblock_agent_dismissed') === 0) {
                              var eabdModalTitle = ips.getSetting('adblockdetector_dialog_title').replace("'", "\'");
                              var eabdModalSize = ips.getSetting('adblockdetector_msg_size');
                              var eabdModalClose = false;
                              var eabdModalModal = ips.getSetting('adblockdetector_overlay');
                              var eabdModalFixed = ips.getSetting('adblockdetector_scroller');
                              var detectAgent = ips.ui.dialog.create({
                                 content: '#detectAgent',
                                 close: eabdModalClose,
                                 modal: eabdModalModal,
                                 title: eabdModalTitle,
                                 size: eabdModalSize,
                                 fixed: eabdModalFixed,
                              });
                              detectAgent.show();

                              $(document).on('keydown', function(e) {
                                 if (e.keyCode == ips.ui.key.ESCAPE) {
                                    setTimeout(function() {
                                       location.reload(true);
                                    }, 0);
                                 }
                              })
                           }
                        })
                  }, 1000);
               });
            },

            dismissAdBlock: function(e) {
               e.preventDefault();
               var url = $(e.currentTarget).attr('href');
               var message = $('[role="dialog"],.ipsModal');

               ips.getAjax()(url).done(function() {
                  var date = new Date();
                  var endAfter = ips.getSetting('adblockdetector_retention');
                  date.setDate(date.getDate() + 1 * endAfter);
                  if (endAfter) {
                     ips.utils.cookie.set('adblock_agent_dismissed', 1, date.toUTCString());
                  } else {
                     ips.utils.cookie.set('adblock_agent_dismissed', 1);
                  }

                  $('body').removeClass('ipsNoScroll');
                  ips.utils.anim.go('fadeOut', message);
                  ips.ui.flashMsg.show(ips.getString('adblock_agent_dismissed_msg'));
               }).fail(function() {
                  window.location = url;
               });
            }
         });
      }(jQuery, _));
```
As you can see from the detector code, a status check is performed: `https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js`

But despite the fact that with regard to this request, RU AdList already contains an exception: https://github.com/easylist/ruadlist/blob/master/advblock/whitelist.txt#L1088 - the detector still works, because Google ads in Russia have been stopped due to sanctions.

As a result, the site is blocked even for those users who do not have any blocker.

**Comment by delta9A** [comment]
> ```
>    <script>
>       ;
>       (function($, _, undefined) {
>          "use strict";
> 
>          ips.controller.register('adblockdetector.front.eabd.agent', {
> 
>             initialize: function() {
>                var isItEnabled = false;
>                this.on(document, 'click', '[data-action="dismissDetector"]', this.dismissAdBlock);
>                $(document).ready(function() {
>                   window.setTimeout(function() {
>                      fetch('https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js')
>                         .catch(function(error) {
>                            if (ips.utils.cookie.get('adblock_agent_dismissed') == undefined || ips.utils.cookie.get('adblock_agent_dismissed') === 0) {
>                               var eabdModalTitle = ips.getSetting('adblockdetector_dialog_title').replace("'", "\'");
>                               var eabdModalSize = ips.getSetting('adblockdetector_msg_size');
>                               var eabdModalClose = false;
>                               var eabdModalModal = ips.getSetting('adblockdetector_overlay');
>                               var eabdModalFixed = ips.getSetting('adblockdetector_scroller');
>                               var detectAgent = ips.ui.dialog.create({
>                                  content: '#detectAgent',
>                                  close: eabdModalClose,
>                                  modal: eabdModalModal,
>                                  title: eabdModalTitle,
>                                  size: eabdModalSize,
>                                  fixed: eabdModalFixed,
>                               });
>                               detectAgent.show();
> 
>                               $(document).on('keydown', function(e) {
>                                  if (e.keyCode == ips.ui.key.ESCAPE) {
>                                     setTimeout(function() {
>                                        location.reload(true);
>                                     }, 0);
>                                  }
>                               })
>                            }
>                         })
>                   }, 1000);
>                });
>             },
> 
>             dismissAdBlock: function(e) {
>                e.preventDefault();
>                var url = $(e.currentTarget).attr('href');
>                var message = $('[role="dialog"],.ipsModal');
> 
>                ips.getAjax()(url).done(function() {
>                   var date = new Date();
>                   var endAfter = ips.getSetting('adblockdetector_retention');
>                   date.setDate(date.getDate() + 1 * endAfter);
>                   if (endAfter) {
>                      ips.utils.cookie.set('adblock_agent_dismissed', 1, date.toUTCString());
>                   } else {
>                      ips.utils.cookie.set('adblock_agent_dismissed', 1);
>                   }
> 
>                   $('body').removeClass('ipsNoScroll');
>                   ips.utils.anim.go('fadeOut', message);
>                   ips.ui.flashMsg.show(ips.getString('adblock_agent_dismissed_msg'));
>                }).fail(function() {
>                   window.location = url;
>                });
>             }
>          });
>       }(jQuery, _));
> ```
> 
> As you can see from the detector code, a status check is performed: `https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js`
> 
> But despite the fact that with regard to this request, RU AdList already contains an exception: https://github.com/easylist/ruadlist/blob/master/advblock/whitelist.txt#L1088 - the detector still works, because Google ads in Russia have been stopped due to sanctions.
> 
> As a result, the site is blocked even for those users who do not have any blocker.

@dimisa-RUAdList thank you for the context. Unfortunately we cannot add this filter, as it will block the adblock wall itself.
