### ISSUE TITLE
Generic hiding rule breaking Instacart

### ISSUE THREAD

**Issue by dbshwang** [abp-filters/abp-filters-anti-cv#1358]
### List the website(s) where you encounter issues with ABP filters 

Any instacart.com links with this format:
* `https://www.instacart.com/products/54177-kalona-supernatural-organic-whipping-cream-quart-32-0-fl-oz`

### Define the problem 

A [recent change](https://github.com/abp-filters/abp-filters-anti-cv/blob/06c91a11cc7f204703df656bfeea221bc145720b/english.txt#L281) caused non-ad images across Instacart to be blocked. The rule is too generic and hides the usage of any `<picture>` and `<source>`. Visiting any of their product pages hides important images.

This xpath matcher: `'.//*[@class]/span/preceding::img[@src][contains(@alt,"")]/preceding::source[@srcset][@media]/ancestor::picture'`

### Screenshot(s) 
<img width="1252" alt="Screen Shot 2023-05-09 at 3 15 00 PM" src="https://github.com/abp-filters/abp-filters-anti-cv/assets/9066975/548e5171-884b-444b-809a-9e6c81d3830b">

### Tell us about your system configuration 

- Operating system and version: 
- Browser and version: 
- Adblock Plus version:

**Comment by Aslatiel** [comment]
Hello,

thanks for reporting.

Issue should be resolved, please update your filter list manually.

thanks,
