### ISSUE TITLE
techmusic.ru

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#1363]
Please add: `techmusic.ru#$#abort-current-inline-script window.onload _uWnd`

Anti-user media popup

Example: `https://techmusic.ru/load/2`

**Comment by delta9A** [comment]
Hi @dimisa-RUAdList filter would block the login popup that links to https://techmusic.ru/register
Can you please give more insights why popup should be blocked? 
Thank you in advance.

**Comment by dimisa-RUAdList** [comment]
The modal media overlay completely blocks interaction with the site. At the same time, the functionality of registration and login after applying the filter remains available by clicking the LOG IN button at the top.

**Comment by delta9A** [comment]
@dimisa-RUAdList thanks for the explanation but unfortunately we cannot block this popup for the following reasons:

- It's not considered an ad.

- It's a site functionality, although login button is still available on the top menu.
