### ISSUE TITLE
ouedkniss.com

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#1381]
Samsung Internet Browser
ABP for Samsung Internet

EasyList + Liste FR + Liste AR + EasyPrivacy

- `https://www.ouedkniss.com/?lang=en`

Sponsored ads

- https://i.ibb.co/CQH2nXk/01.png

Sponsored Stores

- https://i.ibb.co/bbqrSXm/02.png

**Comment by delta9A** [comment]
Hi @smed79 these sponsored ads should be covered on Desktop browsers by EasyList filter: `ouedkniss.com#?#.container:-abp-has(.o-section-heading:-abp-contains(/Sponsored/))`

Unfortunately snippets are not supported on Samsung Internet browser, neither [extended CSS selectors](https://help.adblockplus.org/hc/en-us/articles/360062733293#elemhide-emulation).
We will forward this issue to the relevant team to see if they can implement that.
