### ISSUE TITLE
frandroid.com

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#1382]
**website**

- `https://www.frandroid.com/`

Mobile ua
> Samsung Internet Browser
> ABP for Samsung Internet

Desktop ua
> Chromium / Firefox
> Adblock Plus

Filter lists
> EasyList + Liste FR + Liste AR
> EasyPrivacy
> Annoyance list

**problem**
- Sponsored content
- ad placeholder

**Ss**

https://i.ibb.co/ckw8d2V/IMG-20230618-165857.jpg
https://i.ibb.co/fkHYsXy/IMG-20230618-165927.jpg
https://i.ibb.co/CQnDs5J/IMG-20230618-170516.jpg

**Comment by delta9A** [comment]
Hi @smed79, we pushed a filter to hide the Desktop ads https://github.com/abp-filters/abp-filters-anti-cv/commit/26f06bd
Unfortunately snippets are not supported on Samsung Internet browser, so filter won't work there.
