### ISSUE TITLE
terrikon.com

### ISSUE THREAD

**Issue by dportvine** [abp-filters/abp-filters-anti-cv#1389]
`https://terrikon.com/uk/posts/444573`

### Define the problem 

Ads

### Screenshot(s) 

<details>
<summary>Screen</summary>

![2023-07-02_220555](https://github.com/abp-filters/abp-filters-anti-cv/assets/111344219/2593fc37-0b32-4d47-bcb2-4a48989af76a)
![2023-07-02_220622](https://github.com/abp-filters/abp-filters-anti-cv/assets/111344219/d7cda0d7-7ef7-4600-8471-07ed8e44a0bb)
</details>

### Tell us about your system configuration 

- Operating system and version: Windows 10
- Browser and version: Firefox 114.0.2
- Adblock Plus version: 3.17.1

`terrikon.com#$#abort-on-property-read bdy` works for me.

**Comment by delta9A** [comment]
Hi @dportvine I can't see this side ads, can you please confirm if they are still visible for you? Thank you.

**Comment by dimisa-RUAdList** [comment]
@Aslatiel 
@delta9A 
`terrikon.com#$#abort-on-property-read bdy` - ok
