### ISSUE TITLE
Spiegel.de notice to turn off adblock

### ISSUE THREAD

**Issue by thexperiments** [abp-filters/abp-filters-anti-cv#14]
### List the website(s) where you encounter issues with ABP filters 

* spiegel.de

### Define the problem 

Ad for turning of adblocker

### List all of your filter lists

* EasyList
* Adblock Warning Removal List
* some more

### Tell us about your system configuration 

- Should not matter

### Other details 

Script is loaded from other domain with generated URI

Exampl page containing the "add":
http://www.spiegel.de/netzwelt/web/wie-tim-berners-lee-das-www-retten-will-newsletter-a-1230873.html

Example Script:
http://spiegel-de.spiegel.de/aaefnptdmo-a2l4Y3dteGljbndDekE1KmVnZ3N5cnhjbWhBNzc1KmVmdEF4dnlpKnZpaml2dml2QSpuekE2MjQyNTQ0NypnaGdBe21yaHN7MmN3dGMycXdrMmNtcnhpdnJlcDJnaGc1Kmx2aWpBbHh4dCk3RSk2Sik2Snt7ezJ3dG1pa2lwMmhpKTZKdGVyc3ZlcWUpNkpraXdpcHB3Z2xlangpNkpleXZzem1wcGkxeXhzdG13Z2xpdzFoc3ZqMW1xMWh3Z2x5cmtpcDFtcmhtaXJ3MXdnbHNpcmkxcml5aTF7aXB4MWUxNTY2NTc5ODJseHFwKngpOUZ8KTlIQX0=

Solution:
Block all content from that domain matching the length pattern

/spiegel-de.spiegel.de\/[a-zA-Z0-9=\-_]{339}/$domain=spiegel.de

**Comment by mapx-** [comment]
No, ABP (for legal reasons wont include such filters). 
Try uBo (ublock origin).

**Comment by smed79** [comment]
> This filter list target reinjections of ads no anti adblock.

https://github.com/abp-filters/abp-filters-anti-cv/issues/6#issuecomment-419741822

**Comment by wizmak** [comment]
@thexperiments 
This list does not target messages similar to "Please deactivate your adblocker!".
