### ISSUE TITLE
ouo.io

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#140]
**Website**

* http:\/\/ouo.io/DeES8fH
* http:\/\/ouo.press/DeES8fH

**Problem**

* popups

**Fix**

```
ouo.io,ouo.press#$#abort-on-property-read _pop
ouo.io,ouo.press#$#abort-on-property-write Fingerprint2
```

**Comment by wizmak** [comment]
I can't reproduce any popups

**Comment by smed79** [comment]
I checked again and i get no popup.
