### ISSUE TITLE
eBay.com ViewItem page is breaking

### ISSUE THREAD

**Issue by azoreG** [abp-filters/abp-filters-anti-cv#1407]
**List the website(s) where you encounter issues with ABP filters**
https://www.ebay.com/itm/155587077876?_trkparms=%26rpp_cid%3D64a880511446e8946e1c5d8c%26rpp_icid%3D64a880511446e8946e1c5d8b&_trkparms=parentrq%3Ac1a2656c1890ab967844c22afffffb18%7Cpageci%3Aeb32d919-32ed-11ee-8d67-ee279fea202e%7Ciid%3A1%7Cvlpname%3Avlp_homepage

**Define the problem**
Seller informations is getting hidden (right column)

**Screenshot(s)**
![image (17)](https://github.com/abp-filters/abp-filters-anti-cv/assets/26676164/34599479-701d-4551-87fe-13859576c86d)

**Comment by Aslatiel** [comment]
Hi @azoreG ,

thanks for the report.

This issue does not seem to be reproducible anymore. Could you update your filterlists manually, and let us know if the problem persists.

**Comment by Aslatiel** [comment]
So it seems this issue was not very easily reproducible on all environments.  We've some updates and it should be fine now.

Please update your filterlists manually and check once more if the issue persists.

thanks again for the report.
