### ISSUE TITLE
bug: update anti-curcumvention filters

### ISSUE THREAD

**Issue by johnconner122** [abp-filters/abp-filters-anti-cv#1414]
Follow websites are detecting use of AdBlock:

 - https://www.rockmods.net/
 - https://megaup.net/1gnho/Warrior.2019.S03E10.1080p.10bit.WEBRip.6CH.x265.HEVC-PSA.zip

**Comment by Aslatiel** [comment]
hi @johnconner122 ,

thanks for your report,
Unfortunately, due to legal reasons, we're unable to tackle these *Adblock detection walls*.

ticket will be closed.
