### ISSUE TITLE
Causing Error 2000 on Twitch.tv Streams

### ISSUE THREAD

**Issue by MrAmericanMike** [abp-filters/abp-filters-anti-cv#142]
### List the website(s) where you encounter issues with ABP filters 

https://www.twitch.tv/

### Define the problem 

All streams display an Error 2000

### Screenshot(s) 
![Error 2000](https://i.imgur.com/VxO9FzU.png)

### List all of your filter lists 

Adblock Warning Removal List (Enabled)
EasyPrivacy (Disabled)
Fanboy's Social Blocking List (Enabled)
ABP filters (Enabled)
EasyList (Enabled)

### Tell us about your system configuration 

- Operating system and version: Windows 7 64
- Browser and version: Firefox 66.0.2
- Adblock Plus version: 3.5

### Other details 

Problem is gone when disabling ABP Filters

**Comment by wizmak** [comment]
Closed in 7c33d13
