### ISSUE TITLE
Russian radio stations

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#1427]
Please add: `comedy-radio.ru,radioromantika.ru,veseloeradio.ru#$#abort-on-property-read yaContextCb`

Example:
`https://www.veseloeradio.ru/`
`https://comedy-radio.ru/`
`https://www.radioromantika.ru/`

**Comment by delta9A** [comment]
Hi @dimisa-RUAdList  thank you for your issue.

The suggested filter was added to [GtiLab repo](https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv) instead - commit: [214fc220](https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/commit/214fc220), that's the reason I'm closing this issue.

Please feel free to create new PRs/Issues on the GitLab repo directly from now on.

Thank you for your time.
