### ISSUE TITLE
revivelink.com

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#143]
**Website**

* http:\/\/revivelink.com/1ATIXQ

**Problem**

* propellerads popup

**Fix**

```
revivelink.com#$#abort-on-property-read atob
```

**Comment by wizmak** [comment]
@smed79 unable to reproduce, can you check again?

**Comment by smed79** [comment]
https://i.imgur.com/5In3qxv.png
https://i.imgur.com/aHjrGFW.png
