### ISSUE TITLE
audiofanzine.com

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#145]
Hi,

**Website**

- https:\/\/www.audiofanzine.com/
- https:\/\/www.audiofanzine.com/news/

**Define the problem**

- ads / circumvention 

**Screenshot**

- https://i.vgy.me/CPkPHD.png
- https://i.vgy.me/uihx6K.png

**Tell us about your system configuration**

- Browser and version: Firefox 66 & Chromium 73
- Adblock Plus version: 3.5.1

**List all of your filter lists**

- ABP filters
- EasyList
- EasyPrivacy
- Adblock Warning Removal List

**Comment by okiehsch** [comment]
The adblock/plus equivalent of 
`audiofanzine.com##+js(abort-on-property-read.js, require)` 
should work.

**Comment by smed79** [comment]
```
audiofanzine.com#$#abort-on-property-read require
```
(**\#16030**)
