### ISSUE TITLE
ayefiles.com

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#151]
**Website**

* https:\/\/ayefiles.com/8kkf5nv9zemz

**Problem**

* popups + runative ads

https://imgur.com/mpw6Z9m.png
https://imgur.com/InC7G89.png

**Fix**

```
ayefiles.com#$#abort-on-property-write _pop
ayefiles.com#$#abort-on-property-read NativeAd
ayefiles.com#$#abort-on-property-read atob
ayefiles.com#$#abort-on-property-read popjs.init
```
---
https://forums.lanik.us/viewtopic.php?f=62&t=42185
[uAssets@4094c17](https://github.com/uBlockOrigin/uAssets/commit/4094c171e5a8f3af8c04f1c3c753f387aa6a077f)

**Comment by wizmak** [comment]
@smed79 
Had to leave out `ayefiles.com#$#abort-on-property-read atob` and `ayefiles.com#$#abort-on-property-write _pop` as they made the `Create download link` button nonfunctional.
The other two filters seem enough at the moment on my end, can you check again please?

**Comment by smed79** [comment]
I checked and it is correct what you said.
For popads and propellerads third party scripts I have submitted a [pull request](https://github.com/easylist/easylist/pull/3282/commits/57111a0d97d85b299558347ebaadba21fad303bf) at easylist repo.

**Comment by smed79** [comment]
Domain parked, you can remove it.
