### ISSUE TITLE
ua.sinoptik.ua

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#156]
Please add a snippet: `sinoptik.ua#$#abort-on-property-read SIN.globals.ADBLOCK_DETECTED`

https://ua.sinoptik.ua/

**Comment by dimisa-RUAdList** [comment]
Please replace with:
`sinoptik.ua#$#abort-on-property-read localStorage; abort-on-property-read SIN.globals.ADBLOCK_DETECTED`

**Comment by dimisa-RUAdList** [comment]
Please replace with: `sinoptik.ua#$#abort-on-property-read document.documentElement.createShadowRoot`

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/33230

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/34393

**Comment by Kyiv-ua** [comment]
`https://ua.sinoptik.ua/%D0%BF%D0%BE%D0%B3%D0%BE%D0%B4%D0%B0-%D0%BA%D0%B8%D1%97%D0%B2`

Lots of ads, can you help me?

![2021-01-19_095608](https://user-images.githubusercontent.com/77664434/105007914-3eec9c00-5a41-11eb-962d-4551d2743aca.png)

**Comment by dimisa-RUAdList** [comment]
@Kyiv-ua 
https://greasyfork.org/ru/scripts/19993-ru-adlist-js-fixes

**Comment by P0Rtvine** [comment]
`https://sinoptik.ua/` 😇
### Screenshot(s)
<details>
<summary>Screen</summary>

![2021-04-12_171850](https://user-images.githubusercontent.com/57287308/114409614-4be9d900-9bb3-11eb-9bd2-729d5af95445.png)
</details>

**Comment by dimisa-RUAdList** [comment]
This element has a random ID and it's useless to add it to filters.

**Comment by dportvine** [comment]
Please dell. This rule is outdated.
```adb
sinoptik.ua,dynamo.kiev.ua#$#abort-on-property-read document.documentElement.createShadowRoot
```
