### ISSUE TITLE
agroportal.ua

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#157]
Please add a snippet: `agroportal.ua#$#abort-on-property-read abn`

http://agroportal.ua/ua/

**Comment by wizmak** [comment]
@dimisa-RUAdList please provide a screenshot and/or description.

**Comment by dimisa-RUAdList** [comment]
Infiload > https://i.imgur.com/JAG0Sda.jpg

Previously, there worked a rule `||adbutton.net^$rewrite=1`, however in ABP 3.5.2 redirects works only internal. And using the scriptlet is now the only way to prevent infiload.
