### ISSUE TITLE
gismeteo.ua

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#162]
Please add a snippet: `gismeteo.ua#$#abort-current-inline-script document.createElement`

https://www.gismeteo.ua/

https://i.imgur.com/TaE3jVb.jpg

**Comment by wizmak** [comment]
> Please add a snippet: `gismeteo.ua#$#abort-current-inline-script document.createElement`

@dimisa-RUAdList 
Doesn't seem to work, can you check again?

**Comment by dimisa-RUAdList** [comment]
Indeed. This site works very unstable for me. Try it:  `gismeteo.ua#$#abort-on-property-read localStorage`

**Comment by wizmak** [comment]
> gismeteo.ua#$#abort-on-property-read localStorage

@dimisa-RUAdList also not working for me.

**Comment by dimisa-RUAdList** [comment]
For me it works fine.

**Comment by dimisa-RUAdList** [comment]
https://imgur.com/a/xVnwIT1

**Comment by wizmak** [comment]
@dimisa-RUAdList 
For me It works only if I add/enable the filter before opening the website.

**Comment by dimisa-RUAdList** [comment]
May be: `gismeteo.ua#$#abort-on-property-read localStorage; abort-on-property-write document.cookie`

**Comment by dimisa-RUAdList** [comment]
Please add a snippet: `gismeteo.ua#$#abort-on-property-read Object`

**Comment by DukeBG** [comment]
Hi

Just spent half an hour trying to figure out, why gismeteo.ua stopped working correctly today. Tracked it down to this issue.

`abort-on-property-read Object` breaks jQuery which is used for tabs widget. To switch between three days of the week. And probably other functionality in the website.

They have both the fuctionality of the website and some "FuckAdBlock 3.2.1" functionality in the same script bundle right now //s1.gismeteo.ua/static/compressed/origin_afdd08dd.js

Please remove abort-on-property-read Object. Breaking the website is not a good way to switch off ads.

**Comment by wizmak** [comment]
Hi @DukeBG thank you for your report, problematic filter is now removed.

**Comment by wizmak** [comment]
@dimisa-RUAdList FYI

**Comment by dimisa-RUAdList** [comment]
I believe that deleting a rule without replacing - is a bad decision.

**Comment by mapx-** [comment]
Does this break something ?
`gismeteo.ua#$#abort-on-property-read.js loadMain`

**Comment by DukeBG** [comment]
No, but it also doesn't remove the ads.

**Comment by mapx-** [comment]
no needing on my side, only (the last 3 filters are from russian adguard)
```
gismeteo.ua#$#abort-on-property-read loadMain
gismeteo.ua##div[id="weather-rbkua"]
gismeteo.ua##div#weather-right[id="weather-right"]
gismeteo.ua##.wrap > div#w-hor
```

**Comment by dimisa-RUAdList** [comment]
`gismeteo.ua#$#abort-on-property-read localStorage; abort-on-property-write document.cookie; abort-on-property-read loadMain` - it works well

**Comment by wizmak** [comment]
@mapx- 
> gismeteo.ua#$#abort-on-property-read loadMain

This filter alone works well for me, no need for extra filters at the moment.

**Comment by DukeBG** [comment]
Worked for me too.

Reading their code, I'm not a bit conflicted about document.cookie. There's some user stats code that seems to be used to track total visits and last 24 hours visits (via setting a 24hr cookie) of the user. Then some "ratings" in a WeatherRater, but i don't see any pages actually using that. And then the mentioned "FuckAdBlock" script is detecting adblock and then setting that boolean in a cookie for some purpose. So... maybe nefarious and abort-on-property-write is worth it, maybe not...

**Comment by wizmak** [comment]
@dimisa-RUAdList 
> `abort-on-property-write document.cookie`

This breaks the temperature unit switch button, language switch button, and the search box.

**Comment by dimisa-RUAdList** [comment]
Yes, I already noticed.

**Comment by dimisa-RUAdList** [comment]
Please replace: `gismeteo.ua#$#abort-on-property-read localStorage; abort-on-property-read loadMain`
to > `gismeteo.ua#$#abort-on-property-read loadMain`

**Comment by dimisa-RUAdList** [comment]
Please replace: `gismeteo.ua#$#abort-on-property-read loadMain`
to > `gismeteo.ua#$#abort-on-property-read eval`

**Comment by dimisa-RUAdList** [comment]
Please replace with: `gismeteo.ua#$#abort-on-property-read document.documentElement.createShadowRoot`

**Comment by dimisa-RUAdList** [comment]
@wizmak 
@arsykan 
Del please: `gismeteo.ua#$#abort-on-property-read eval`

Some temperature graphs break, for example here: https://www.gismeteo.ua/weather-chisinau-4980/14-days/ (old design)
