### ISSUE TITLE
Adding ABP+ subscribe links to the README?

### ISSUE THREAD

**Issue by jm3** [abp-filters/abp-filters-anti-cv#163]
Would a PR that adds the one-click ABP+ subscribe links to the README be welcomed? If so I'm happy to do it.

**Comment by wizmak** [comment]
@jm3 Thank you for the proposal!

This anti-cv list is enabled by default, and also there is a checkbox in ABP's general settings page to disable/enable the list.
![image](https://user-images.githubusercontent.com/38558046/57070113-bf4ff400-6cd6-11e9-89af-fa4382d2ca4a.png)

Hope I understood your proposal correctly.
