### ISSUE TITLE
japscan.com

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#168]
**Website**

* https:\/\/www.japscan.com/

**Problem**

* ads + popups 

**Fix**

```
japscan.cc,japscan.com,japscan.to#$#abort-on-property-read localStorage
```

**Comment by smed79** [comment]
@wizmak add also

```
japscan.cc,japscan.com,japscan.to#$#abort-current-inline-script document.createElement String.fromCharCode
```

**Comment by smed79** [comment]
add
```
japscan.cc,japscan.com,japscan.to#$#abort-on-property-read atob
```

**Comment by smed79** [comment]
new domain `japscan.co`

**Comment by smed79** [comment]
@wizmak Please, add
```
japscan.co,japscan.com#$#abort-current-inline-script Object.defineProperty XMLHttpRequest
japscan.co,japscan.com#$#abort-on-property-read String.fromCharCode
```

**Comment by wizmak** [comment]
@smed79 there doesn't seem to be any issues on `japscan.co` & `japscan.com`, could you please add more details?

Also noticed that the french list is breaking some pages, e.g. `https://www.japscan.co/lecture-en-ligne/tales-of-demons-and-gods/262/`

**Comment by smed79** [comment]
> there doesn't seem to be any issues on japscan.co & japscan.com

banners ads reported via email. e.g. https://imgur.com/ieBdofb.png

> Also noticed that the french list is breaking some pages

Already fixed, thank you.
