### ISSUE TITLE
notebookcheck.com

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#169]
**Website**

* https:\/\/www.notebookcheck.com/
* https:\/\/www.notebookcheck.net/

**Problem**

* ads if Adblock Plus is detected

**Ss**

* https://imgur.com/t1m9R43.png
* https://imgur.com/CTcFxAS.png

**Fix**

```
notebookcheck.com,notebookcheck.net#$#abort-current-inline-script Math toString
notebookcheck.com,notebookcheck.net#$#abort-current-inline-script document.createElement /ads|adv/
```

**Comment by wizmak** [comment]
> notebookcheck.com,notebookcheck.net#$#abort-current-inline-script Math toString

@smed79 
Added only this filter as it seems to be enough.
