### ISSUE TITLE
ruanyifeng.com

### ISSUE THREAD

**Issue by cjx82630** [abp-filters/abp-filters-anti-cv#17]
### List the website(s) where you encounter issues with ABP filters 

http://www.ruanyifeng.com/blog/2018/11/awk.html

### Define the problem 

anti-adblock
![on](https://user-images.githubusercontent.com/9707241/48838957-e7046d00-edc4-11e8-8460-ea5ba01545c0.jpg)
![off](https://user-images.githubusercontent.com/9707241/48838987-013e4b00-edc5-11e8-9968-384a83316922.jpg)

### List all of your filter lists

Easylist China
EasyList
ABP filters

### Tell us about your system configuration 

- Operating system and version: win10
- Browser and version: Chrome 70.0.3538.102
- Adblock Plus version: 3.4.1

**Comment by cjx82630** [comment]
for reference only:
ruanyifeng.com#$#abort-on-property-read checker

**Comment by wizmak** [comment]
This list does not target warning messages.
