### ISSUE TITLE
gismeteo.ua

### ISSUE THREAD

**Issue by ditraUA** [abp-filters/abp-filters-anti-cv#170]
### List the website(s) where you encounter issues with ABP filters 

http://gismeteo.ua

### Define the problem 

I have an error when trying to login on forum.lanik.us (Incorrect integer value: 'ANONYMOUS' for column 'user_id' at row 1 [1366]) so have to write here, problem is important.

https://www.gismeteo.ua/weather-kyiv-4944/ -> can't change day. When I try to show tomorrow weather, click is not working at all. 

It happened just after manual update of easylist+ruadlist in Adblock Plus. Same Issue in Adblock. 

And I have lot of errors like
`www.gismeteo.ua/:1 Blocked script execution in 'https://www.gismeteo.ua/weather-kyiv-4944/' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.`

I didn't saw ads before today list update (previuos was made yesterday, about 6:00 pm Kiev time). And I don't see after update, but site in not working. Core functionality (tomorrow weather) is broken. And this problem is hidden from regular user. It is really not obvious that problem is in Adblock Plus and it need to be disabled on this site.

### Screenshot(s) 

https://i.imgur.com/0roub1P.png

### List all of your filter lists 

Easylist + Ruadlist + ABP Filters. Problem in Ruadlist.

### Tell us about your system configuration 

- Operating system and version: Window 10
- Browser and version: Chrome  74.0.3729.131
- Adblock Plus version: 3.5.2

### Other details 

Possibly problem is in rules like
||gismeteo.ua/weather-$csp=sandbox allow-same-origin;

**Comment by smed79** [comment]
@dimisa-RUAdList fyi.

**Comment by ditraUA** [comment]
I'm trying to use site without disabling ABP.  I don't know how to overwrite rules like $csp=sandbox in custom lists, so I had to disable whole Ruadlist leaving only Easylist.  

This case is working almost perfect in pair with Ruadlist JS Fixes (userscript). No ads in shown, but page has some empty blocks (should be hidden with ruadlist). 

I've tried to find a solution using ABP only and here it is:
`gismeteo.ua^$csp=script-src 'self' * 'unsafe-inline'` 

This rule hides even more then JS Fixes. But this is working only if request to https://s.zmctrack.net/z is not blocked. Looks like blocking zmctrack is a signal to Adblock detector (some times I saw message about adblock in console).

May be my rule can break some functionality, but I've tested for about an hour and didn't saw any problems.

Unfortunately, I didn't find how to disable Ruadlist only for gismeteo domain. Or I disable it for all sites and see large amount of banners and empty blocks or gismeteo.ua is broken and I can't use it.

The only good way for now is to disable ABP on gismeteo completely. But ads in the case are VERY evil.

**Comment by wizmak** [comment]
@ditraUA try `@@||gismeteo.ua/|$csp=sandbox allow-same-origin;` in your custom filters, meanwhile @dimisa-RUAdList fixes the problem.

In the future, you can report such issues in the dedicated [EasyList forum](https://forums.lanik.us/viewforum.php?f=102) for Ruadlist  .

**Comment by ditraUA** [comment]
I know this forum but it is not working now:
https://i.imgur.com/PoUXgcF.png when I try to log in.

`@@||gismeteo.ua/|$csp=sandbox allow-same-origin;
gismeteo.ua^$csp=script-src 'self' * 'unsafe-inline'`

Works nice with ruAdlist, thanks! 

And I hope, @dimisa-RUAdList will fix it in general list. At least 3 people in our small office had the same problem today.
