### ISSUE TITLE
spcs.me, strip2.me

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#174]
https://strip2.me/en/video/view/mariah_carey-spcs.Me-1243131/?Li=1621619337&Lii=1243131&Lt=29&Sn=1

https://imgur.com/G7IMHtU

Please add a snippet: `spcs.me,strip2.me#$#abort-on-property-read SpacesClickunder`

**Comment by dimisa-RUAdList** [comment]
Please add a snippet:  `spac1.me,1strip2.me#$#abort-on-property-read SpacesClickunder`

**Comment by dimisa-RUAdList** [comment]
@wizmak 
strip2.me, 1strip2.me > strip2.xxx

**Comment by smed79** [comment]
@dimisa-RUAdList from the "ISSUE TEMPLATE"

> Surround the URLs with backticks `` to prevents the URL from being clickable.
> Warn with "NSFW" where applicable.

**Comment by dimisa-RUAdList** [comment]
Please change to:
`spac1.com,spac1.me,spac1.net,spcs.me,strip2.xxx#$#abort-on-property-write SpacesClickunder`

Otherwise, the rewind in the player breaks: `https://strip2.xxx/ru/video/view/jeff-milton-1309304/` (NSFW)

**Comment by dimisa-RUAdList** [comment]
Please del: `spcs.me`

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Please add: `strip2.in`

Example: `https://strip2.in/video/view/jeff-milton-1309304/` (NSFW)

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with:
`gdespaces.com,spac.me,spac1.com,spac1.me,spac1.net,spaces-blogs.com,spaces.im,strip2.in,strip2.xxx#$#abort-current-inline-script __require /clickunder/`

Example: 
https://spac1.net/video/view/samye-bolwie-i-moschnye-xkskavatory-v-mire-38608805/
http://ipic.su/img/img7/fs/1.1620739978.gif (> https://forums.lanik.us/viewtopic.php?p=159844#p159844)

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Please add: `abort-on-property-read Object.prototype.initOnPlay`

Example:
https://spac1.net/video/view/samye-bolwie-i-moschnye-xkskavatory-v-mire-38608805/
http://ipic.su/img/img7/fs/1.1620802260.gif ( > https://forums.lanik.us/viewtopic.php?p=159858#p159858)

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak

Please add: `spcs.me`. The domain is up and running again.

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak

Please add: `spac1.ru`

Example: `https://spac1.ru/video/view/barselona-selta-3-1-50815697/`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak

Please add: `gdespaces.net`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak

Please add: `spac1.org`

**Comment by dimisa-RUAdList** [comment]
@manuel-martinez-dev
@wizmak

Please add: `spac1.info,spcs.social`

**Comment by dimisa-RUAdList** [comment]
@edivaniadc 
@manuel-martinez-dev
@wizmak

Please add: `spcs.news`

**Comment by dimisa-RUAdList** [comment]
@edivaniadc
@manuel-martinez-dev
@wizmak

Please add:  `spcs.pro`
Example: `https://spcs.pro/sz/igry/android/azartnye/?Link_id=162899`

**Comment by dimisa-RUAdList** [comment]
@edivaniadc
@manuel-martinez-dev
@wizmak

Up!

**Comment by dimisa-RUAdList** [comment]
@Aslatiel 
@delta9A
@manuel-martinez-dev
@wizmak

Please add: `spcs.life`

**Comment by dimisa-RUAdList** [comment]
@Aslatiel
@delta9A
@manuel-martinez-dev
@wizmak

Please add: `spcs.pub`

**Comment by Aslatiel** [comment]
changes pushed
50f6bf3960bdd628ef5bf1089f759de8240e0ff6

**Comment by dimisa-RUAdList** [comment]
@Aslatiel
@delta9A
@manuel-martinez-dev
@wizmak

Please add: `spcs.global`, `usersporn.com`

**Comment by dimisa-RUAdList** [comment]
@Aslatiel
@delta9A
@manuel-martinez-dev
@wizmak

Please add: `google-cloud.services`

**Comment by dimisa-RUAdList** [comment]
@Aslatiel
@delta9A
@wizmak

Please add: `spcs.network,spcs-files.xyz`

**Comment by dimisa-RUAdList** [comment]
@Aslatiel
@delta9A
@wizmak

Please add: `spcs.reviews`

**Comment by dimisa-RUAdList** [comment]
@Aslatiel
@delta9A
@wizmak

Please add: `spac.run`, `spac.wtf`
