### ISSUE TITLE
newsyou.info

### ISSUE THREAD

**Issue by ivanviva** [abp-filters/abp-filters-anti-cv#176]
### List the website(s) where you encounter issues with ABP filters 

https://newsyou.info/

### Define the problem 

https://newsyou.info/peticiya-za-otstavku-zelenskogo-nabrala-neobxodimye-golosa
https://newsyou.info/skolko-ukraincy-tratyat-na-mobilnuyu-svyaz

and all other news pages are totally destroyed when Adblock is enabled. Double checked in four different computers and several browsers. Site works only in Firefox where ABP is enabled. In Chrome and Opera ABP destroys the site just after filter list update.

### Screenshot(s) 
https://i.imgur.com/XIX4Fkf.png
https://i.imgur.com/h32YhaN.png

Before list update theese pages looked like this:

https://i.imgur.com/pYezKd0.png
https://i.imgur.com/rgSws0A.png

### List all of your filter lists 

ABP filters
RuAdList+EasyList

### Tell us about your system configuration 

- Windows 10
- Chrome  74.0.3729.169 (and tested in other browsers)
- Adblock Plus version: 3.5.2

### Other details 

I'm not sure if it is a bug or mistake. The problem is too obvious and consistently repeated in very popular browsers. Looks like russian moderator advisedly destroyed ukrainian political site for large amount of Adblock users. 

If it was not arbitrariness on his part, but following the official policy of Adblock, please let me know. In this case, I will deal with a broader coverage of this issue. I believe that Adblock users deserve to know what actions can perform extension installed in their browsers. And find out the real reason why they cannot access parts of the sites.

**Comment by mile-ne** [comment]
Hey @ivanviva,

In this repository we can only control, fix or review issues related to the abp-cv-list.
Although, I can help you out by calling the attention of @dimisa-RUAdList. 

Anyway, thanks for bringing that up!

**Comment by ivanviva** [comment]
Thanx!
It would be interesting to read the position of @dimisa-RUAdList and the reasons, why the site is broken. 

If the reasons relate to Adblock circumvention, than filter have to be added to ABP Filter list, not general subscription, am I wrong? Or what is the purpose of this separate list?

**Comment by dimisa-RUAdList** [comment]
This should be discussed here: https://forums.lanik.us/viewforum.php?f=102

**Comment by ivanviva** [comment]
Okay, I'll copy this issue to forum.lanik.us. And I think, the result of the discussion need to be posted here. 

If it really was a mistake, it need be fixed and issue will be closed. Otherwise, I will be grateful for clarifying the position of Adblock regarding the news (and other) sites breaking.

**Comment by ivanviva** [comment]
Hello. Unfortunately, communication on the forum did not clarify the situation. 
@dimisa-RUAdList  did not say a word about the reasons on breaking the site in Chrome. He said that the Easylist supports only Firefox, and the rest of browsers on a residual basis. And after my words that I am not a representative of the site, but a journalist, my next posts were deleted altogether.
At the same time, they quietly made changes to the filters and later accused me of the fact that everything works fine and my complaint is false. 

A strange communication style, which only aggravated my suspicions that abuse was happening on someone’s side. But at least the site has stopped breaking and this is already some kind of result.


Over the weekend, I had a couple of meetings with technical experts who showed me how wide the possibilities of Adblock are to hide not only ads, but also any content in general.
You can hide social media posts from a particular author, certain sites in search results, turn entire sites into blank white pages, etc.
This can be a powerful tool for censorship, extortion, or other abuse if you don’t pay enough attention to controlling what filtering options your Easylist partners add.

In this regard, I ask you to get an answer  from @dimisa-RUAdList   about the reasons for blocking. And, if it was nevertheless arbitrariness or bad testing, then I would like to ask you if any measures will be taken to avoid such situations in the future?

Please do not delete my message or leave it unanswered. I am not going to inflate the scandal out of the blue. I appreciate Adblock as a useful tool, and don't want to harm in any kind.
But the topic of possible censorship or other abuse is too important, given the number of Adblock users. Having not received answers to my questions here, I will be forced to ask them publicly, through the media.​

**Comment by mile-ne** [comment]
Hey @ivanviva! Sorry for the late reply. Have been busy!
I am happy that your issue has been fixed. 
If the filters are a set of rules that match HTML and considering that web content is not static, it can happen that changes on your code may cause false positives. This does not happen only with adblockers, but with everything that interacts with your browser, like other extensions, add-ons etc. That is why APB as an extension is prepared with an issue reporter so we can fix false negatives, positives and prevent a negative browser experience for future users. That said, would be an utopia to think that false positives can't happen. 
For this specific case I don't think the list was used in any other way then to serve the purpose of blocking ads. Although if you see differently for other websites, or lists being used for different purposes I would appreciate if you could call the attention of the contributors.
Let me know if there is anything else we can help you with

**Comment by smed79** [comment]
@mile-ne **ABP** not **APB** :)

**Comment by ivanviva** [comment]
@mile-ne, Thank you.

Probably, there really was a technical error, without malicious intent. I would ask for more control over the addition of dangerous filters like $csp.

But I see that the attention to problems is really paid attention to and they are solved. I will try to contribute and report the problems that I discover or was reported to me.

Thanks again for your support and special thanks for the great product.
