### ISSUE TITLE
Quora: share story in feed is blocked by abp

### ISSUE THREAD

**Issue by glee-zenefits** [abp-filters/abp-filters-anti-cv#178]
### List the website(s) where you encounter issues with ABP filters 

* quora.com

### Define the problem 

some feed stories like below in main feed is being blocked. looks like a shared story

### Screenshot(s) 

![image](https://user-images.githubusercontent.com/21316835/58361424-91784e00-7e43-11e9-8012-a988ec79fb49.png)

### List all of your filter lists 

easylist, abp filter

### Tell us about your system configuration 

- Operating system and version: mac
- Browser and version: chrome
- Adblock Plus version: lastest

**Comment by smed79** [comment]
Post an example url where the issue occur or the link of an [ABP issue report](https://help.eyeo.com/en/adblockplus/report-an-issue).

**Comment by glee-zenefits** [comment]
https://reports.adblockplus.org/06352e1e-ac1b-4441-8920-57a5c04ecec4

**Comment by smed79** [comment]
Doesn't help... remove `quora.com` from the [whitelist](https://help.eyeo.com/en/adblockplus/remove-a-website-from-the-whitelist) first, before creating the issue report.

**Comment by glee-zenefits** [comment]
https://reports.adblockplus.org/b3482dbe-59d8-41e0-8a7d-04ca239cea4e
created another one but not sure if you are able to get it. basically the story is blocked, so that's why on my prior report i have to disable to block to show it.

<img width="800" alt="Image 2019-05-25 at 11 07 32 AM" src="https://user-images.githubusercontent.com/21316835/58373134-faac9f80-7edd-11e9-98ef-873de43740ec.png">
------------------------------
and disappeared when i turn on abp

<img width="748" alt="Image 2019-05-25 at 11 08 17 AM" src="https://user-images.githubusercontent.com/21316835/58373135-0009ea00-7ede-11e9-98f1-f6e6421d6e34.png">

**Comment by mapx-** [comment]
I see only 

`quora.com##.FeedStory.HyperLinkFeedStory.feed_item`

so the filter should be removed

add
`quora.com#@#.FeedStory.HyperLinkFeedStory.feed_item`

**Comment by mile-ne** [comment]
Hey @glee-zenefits, I've just removed the filter so you can remove quora.com#@#.FeedStory.HyperLinkFeedStory.feed_item from your custom filters if you like.
thanks @smed79 and @mapx- !
