### ISSUE TITLE
fstore.biz

### ISSUE THREAD

**Issue by juskdtlm** [abp-filters/abp-filters-anti-cv#179]
### List the website(s) where you encounter issues with ABP filters 

* https://fstore.biz/file/DEB70F24FFBC

### Define the problem 

There is anti-adblock. If you enable anti-adblock removal, the site breaks

### Screenshot(s) 

![image](https://user-images.githubusercontent.com/24647715/58400713-2eadcf00-805c-11e9-8bfa-3f2c13b64250.png)

![image](https://user-images.githubusercontent.com/24647715/58400701-26ee2a80-805c-11e9-9fe2-8cfdaa1155d2.png)

### List all of your filter lists 

![image](https://user-images.githubusercontent.com/24647715/58400720-32d9ec80-805c-11e9-89e0-44fd50945ee2.png)

### Tell us about your system configuration 

- Operating system and version: Microsoft Windows 10 Pro 10.0.17134 Build 17134
- Browser and version: Version 74.0.3729.169 (Officiel version) (64-bit)
- Adblock Plus version: 3.5.2

### Other details 

No other details

**Comment by smed79** [comment]
Adblock Plus [filter list](https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt) target reinjections of ads / _not anti adblock messages_.

<details>
  <summary>Collapsibled contents</summary>
<br> report or search for filter at EasyList Forum http://forums.lanik.us/
</details>
