### ISSUE TITLE
xianzhenyuan.cn

### ISSUE THREAD

**Issue by cjx82630** [abp-filters/abp-filters-anti-cv#18]
### List the website(s) where you encounter issues with ABP filters 

http://www.xianzhenyuan.cn/forum.php

### Define the problem 

anti-adblock
![on](https://user-images.githubusercontent.com/9707241/48839175-8b86af00-edc5-11e8-86af-706879caa86a.jpg)
![off](https://user-images.githubusercontent.com/9707241/48839177-8f1a3600-edc5-11e8-99c7-11c1a5f1f726.jpg)

### List all of your filter lists

Easylist China
EasyList
ABP filters

### Tell us about your system configuration 

- Operating system and version: win10
- Browser and version: Chrome 70.0.3538.102
- Adblock Plus version: 3.4.1

**Comment by krystian3w** [comment]
List no create to fight with anti-adblock?

**Comment by cjx82630** [comment]
for reference only:
xianzhenyuan.cn#$#abort-on-property-read ad

**Comment by krystian3w** [comment]
Works :thinking:...

**Comment by wizmak** [comment]
This list does not target anti-adblock messages.

**Comment by krystian3w** [comment]
#21 duplicate **type** issue
