### ISSUE TITLE
ianimes.co

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#180]
**Website**

* `https://www.ianimes.top/`

**Problem**

* popup + popunder

**Fix**

```
ianimes.co,ianimes.top#$#abort-on-property-read _0x522e
ianimes.co,ianimes.top#$#abort-on-property-read adcashMacros
```

**Comment by mile-ne** [comment]
sites are offline. can you re-check?

**Comment by smed79** [comment]
27/05/2019 21:49:53 - https://i.vgy.me/MW81m3.png

**Comment by mile-ne** [comment]
I get a 504 for both pages. Let me know which IP you are using (even tried Annaba)

**Comment by smed79** [comment]
> Let me know which IP you are using

I don't want to be blacklisted by the admin :-)

> I get a 504 for both pages

demo https://imgur.com/a/ADNQW9w

**Comment by krystian3w** [comment]
Test on FR proxy / VPN?
