### ISSUE TITLE
WP group

### ISSUE THREAD

**Issue by easylistpolish** [abp-filters/abp-filters-anti-cv#183]
### List the website(s) where you encounter issues with ABP filters 

abczdrowie.pl,autokult.pl,echirurgia.pl,fotoblogia.pl,kafeteria.pl,kardiolo.pl,komorkomania.pl,luxlux.pl,medycyna24.pl,money.pl,nerwica.com,o2.pl,open.fm,pinger.pl,pogodnie.pl,pudelek.pl,pudelek.tv,pudelekx.pl,pytamy.pl,samosia.pl,smog.pl,snobka.pl,money.pl,wp.pl

### Define the problem 

Circumvented ads on all websites from WP group

### List all of your filter lists 

abczdrowie.pl,autokult.pl,echirurgia.pl,fotoblogia.pl,kafeteria.pl,kardiolo.pl,komorkomania.pl,luxlux.pl,medycyna24.pl,money.pl,nerwica.com,o2.pl,open.fm,pinger.pl,pogodnie.pl,pudelek.pl,pudelek.tv,pudelekx.pl,pytamy.pl,samosia.pl,smog.pl,snobka.pl,money.pl,wp.pl#$#abort-on-property-read Math.asin

### Tell us about your system configuration 

- Operating system and version: Ubuntu
- Browser and version: Chrome 70
- Adblock Plus version: 3.5.2

**Comment by mile-ne** [comment]
hey, 
first, thanks a lot!
second I still see a lot of ads. Are you sure about this parameter Math.asin ?
maybe you could use #$#abort-on-property-read Math.round except for wp.pl since it blocks content

**Comment by easylistpolish** [comment]
Hey @mile-ne 
Unfortunately it's breaking more sites (eg. https://komorkomania.pl/37300,oppo-reno-z-oficjalnie ). Anyway thank you for proposition.:) It inspired me to change filter to
`abczdrowie.pl,autokult.pl,echirurgia.pl,fotoblogia.pl,kafeteria.pl,kardiolo.pl,komorkomania.pl,luxlux.pl,medycyna24.pl,money.pl,nerwica.com,o2.pl,open.fm,pinger.pl,pogodnie.pl,pudelek.pl,pudelek.tv,pudelekx.pl,pytamy.pl,samosia.pl,smog.pl,snobka.pl,money.pl,wp.pl#$#abort-on-property-read Math.asin Math.PI`
It's bloking also script causing video ads.

**Comment by smed79** [comment]
@easylistpolish 

You can [rewrite](https://help.eyeo.com/en/adblockplus/how-to-write-filters#rewrite) the video ad to an empty internal resource:

* https://i.vgy.me/NUpBxL.png
* `||v.wpimg.pl^$media,rewrite=abp-resource:blank-mp3,domain=komorkomania.pl`

@mile-ne 

ABP reject my regex filter https://i.vgy.me/MmucRV.png
What is the correct syntax to combinate between [rewrite option](https://help.eyeo.com/en/adblockplus/how-to-write-filters#rewrite) filter and [regular expression](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions)? 
... or it is not supported?

**Comment by krystian3w** [comment]
I can close this: #22?

**Comment by mile-ne** [comment]
@smed79 take a look at this post regarding the rewrite filter option: https://adblockplus.org/blog/potential-vulnerability-through-the-url-rewrite-filter-option

**Comment by smed79** [comment]
`$rewrite` filter option to [internal resources](https://issues.adblockplus.org/ticket/7067) is **safe**.

**Comment by mile-ne** [comment]
@smed79 I think this last commit is working fine. fyi @krystian3w

**Comment by krystian3w** [comment]
`wp.pl#$#abort-on-property-read aplace`

IMO no hide any ad / empty placeholder any-more (filter need 2 weeks frequency test and update as log WP Media S.A. use ads).

**Comment by kulfoon** [comment]
You guys should be very careful when script-injecting on WP group websites, because, during many years of fixing WP group websites, it was noticed that code on WP group websites changes often, and such injects not only stop working after some time, but such deprecated injects often begin breaking WP websites functionality as well, like: broken/hidden comments, videos, articles.

Btw. - WP Group is most advertised group of websites in Poland, they use agressive and annoying circumvention ads and anti-blocks for many years, just take a look: 
https://github.com/MajkiIT/polish-ads-filter/issues?&q=in%3Atitle+WP
https://github.com/AdguardTeam/AdguardFilters/issues?q=in%3Atitle+WP

<details not-open>
<summary>Also here is a complete list of all websites of WP Group:</summary>

```
domains ending with `wp.pl`:

bigfarm.wp.pl
blog.wp.pl
callofwar.wp.pl
dietajuniora.wp.pl
dlugi.wp.pl
empire.wp.pl
fundusze.wp.pl
gielda.wp.pl
herozero.wp.pl
iwtjxgfu.wp.pl
jfizfp7uihw0q0.wp.pl
multikurs.wp.pl
naryby.wp.pl
nocowanie.wp.pl
owabgxis.wp.pl
pasazfin.wp.pl
poczta.wp.pl
praca.wp.pl
prawo.wp.pl
railnation.wp.pl
taern.wp.pl
targinamedal.wp.pl
twojeip.wp.pl
www.docelu.wp.pl
www.mixer.wp.pl
wycieczki.wp.pl
beta.wp.pl
bilety24.wp.pl
centralagier.wp.pl
diety.wp.pl
dlaprasy.wp.pl
dom.wp.pl
dziejesie.wp.pl
facet.wp.pl
film.wp.pl
finanse.wp.pl
forgeofempires.wp.pl
gry.wp.pl
gryonline.wp.pl
gwiazdy.wp.pl
horoskop.wp.pl
inwestor.wp.pl
kobieta.wp.pl
krs.wp.pl
ksiazki.wp.pl
kuchnia.wp.pl
magazyn.wp.pl
morizon.wp.pl
moto.wp.pl
onas.wp.pl
opinie.wp.pl
pilot.wp.pl
pogoda.wp.pl
profil.wp.pl
pytamy.wp.pl
radar.wp.pl
reklama.wp.pl
rekrutacja.wp.pl
sportowefakty.wp.pl
tech.wp.pl
teleshow.wp.pl
telewizja.wp.pl
turystyka.wp.pl
tv.wp.pl
typer.wp.pl
video.wp.pl
wawalove.wp.pl
wiadomosci.wp.pl
www.wp.pl

domains not ending with `wp.pl`:

abczdrowie.pl
autokult.pl
dobramama.pl
dobreprogramy.pl
domodi.pl
echirurgia.pl
fotoblogia.pl
gadzetomania.pl
homebook.pl
jejswiat.pl
kafeteria.pl
kafeteria.tv
komorkomania.pl
luxlux.pl
medycyna24.pl
mixer.pl
money.pl
nocowanie.pl
o2.pl
open.fm
parenting.pl
pinger.pl
pogodnie.pl
pudelek.pl
pytamy.pl
samosia.pl
smaczneblogi.pl
smog.pl
snobka.pl
testwiedzy.pl
```

</details>
