### ISSUE TITLE
Someone added a new file that blocks video for www.thewatchcartoononline.tv videos from showing I want it taken away. Not sure the source, not great at programming. Thanks.

### ISSUE THREAD

**Issue by truthinsuffering** [abp-filters/abp-filters-anti-cv#184]
### List the website(s) where you encounter issues with ABP filters 

* 

### Tell us about your system configuration 

- Operating system and version: 
- Browser and version: 
- Adblock Plus version:

**Comment by mile-ne** [comment]
thanks for reporting @truthinsuffering!
we just fixed it. If you have any other issue let us know!
