### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by paul271** [abp-filters/abp-filters-anti-cv#185]
Please replace

![image](https://user-images.githubusercontent.com/51440256/59026810-25ff8a80-880c-11e9-996d-2b38657c915a.png)

with

![image](https://user-images.githubusercontent.com/51440256/59026936-74ad2480-880c-11e9-92f3-0ebb08cec25a.png)

This will display the right column but remove the top ads. Thank you.

**Comment by mile-ne** [comment]
hey! can you just send me a url where I can reproduce it?

**Comment by paul271** [comment]
[Here you go](https://www.pornhub.com/view_video.php?viewkey=ph5a00edddb74c9).

**Comment by mile-ne** [comment]
Let me know if this works better for you. Thanks paul!
