### ISSUE TITLE
baidu.com

### ISSUE THREAD

**Issue by cjx82630** [abp-filters/abp-filters-anti-cv#19]
### List the website(s) where you encounter issues with ABP filters 

https://www.baidu.com/

### Define the problem 

hide ads too slow. consider baidu is the top search site in China, the more faster is good for millions users.

### List all of your filter lists

Easylist China
EasyList
ABP filters

### Tell us about your system configuration 

- Operating system and version: win10
- Browser and version: Chrome 70.0.3538.102
- Adblock Plus version: 3.4.1

### Other details 

Goto baidu.com and type in "jd" or other word, and will be redirected to search result soon.
Sometimes,there is ad in the first slot or not, which contain Chinese character "广告".
after around one second,will be hidden by Easylist China. Please use snippet "hide-if-contains", so that did't show up at all.
https://mega.nz/#!1t0XwaLY!k9c3Y2TzwV-tcV_iRbwhipoEmyAk--vQOQxb2fQHRPE

**Comment by cjx82630** [comment]
for reference only:
ipv6.baidu.com,xueshu.baidu.com,www.baidu.com,www1.baidu.com#$#hide-if-contains 广告 .c-container '.f13 > .m'

**Comment by wizmak** [comment]
> ipv6.baidu.com,xueshu.baidu.com,www.baidu.com,www1.baidu.com#$#hide-if-contains 广告 .c-container '.f13 > .m'
@cjx82630 
does this filter work for you?

**Comment by cjx82630** [comment]
@wizmak yes.  "广告" = "ad"
