### ISSUE TITLE
otzovik.com

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#192]
Please add a snippet: `otzovik.com#$#abort-on-property-read Ya.Direct`

https://otzovik.com/review_7399494.html

https://i.imgur.com/Ymhobjt.jpg

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Please add: `abort-on-property-read Object.prototype.renderDirect`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `abort-on-property-read Object.prototype.Metrika`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `abort-on-property-read Object.prototype.loadAd`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `abort-on-property-read Object.prototype.loadRtb`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `abort-on-property-read Object.prototype.getYaContext`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `abort-on-property-read Object.prototype.render`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `abort-on-property-read Object.prototype.RtbRender`

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Please replace all with: `abort-on-property-read Object.prototype.Rtb`

**Comment by wizmak** [comment]
@dimisa-RUAdList 
Done: 72fa4ab

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace all with: `abort-on-property-read Object.prototype.RTB`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.rtbInDirect`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.RtbBlockRenderInit`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.isAllowedRepeatAds`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.__confirmBlocks`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.detect`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.RtbBlockCreateWrapper`
