### ISSUE TITLE
news.yandex.ru

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#20]
The ad is in shadow-root. Add please:
`auto.ru,avito.ru,drive2.ru,fb.ru,kakprosto.ru,razlozhi.ru,yandex.az,yandex.by,yandex.ee,yandex.fr,yandex.kg,yandex.kz,yandex.lt,yandex.lv,yandex.md,yandex.ru,yandex.ua,yandex.uz#$#hide-if-shadow-contains *`
When adding snippets to RU AdList, they do not work.

**Comment by hfiguiere** [comment]
FYI, snippets filters not in the anti-cv list (or the user's custom filters) are ignored. This is intended.

**Comment by dimisa-RUAdList** [comment]
@hfiguiere 
Thank you, I know. You probably did not quite understand me. I ask to add snippets to the filter: https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt

**Comment by wizmak** [comment]
@dimisa-RUAdList 
hey, can you provide some screenshots for ads that the suggested filter targets?

**Comment by dimisa-RUAdList** [comment]
@wizmak 
As I understand it, they circumvented this rule and it does nothing else. Please remove it.

**Comment by wizmak** [comment]
@dimisa-RUAdList 
I removed the old filter as suggested. But, I'm unable to find `Object.prototype.AdvManagerBanner` or notice any effect of the suggested filter, can you provide more details?

**Comment by dimisa-RUAdList** [comment]
@wizmak 
No I can not. The appearance of advertising is observed by authorized users, once every few hours. It’s hard to catch. Sometimes it may not be several days.

**Comment by wizmak** [comment]
@dimisa-RUAdList 
> No I can not. The appearance of advertising is observed by authorized users, once every few hours. It’s hard to catch. Sometimes it may not be several days.

Okay, in such case I added it, as I don't notice any negative impact on those websites.
