### ISSUE TITLE
onlinevideoconverter.com

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#21]
https://www.onlinevideoconverter.com/ru/youtube-converter

BlockAdblock

Add please:`onlinevideoconverter.com#$#abort-on-property-read eval`

**Comment by mapx-** [comment]
Did you test
`@@||onlinevideoconverter.com^$generichide`

?

**Comment by dimisa-RUAdList** [comment]
When using the generichide, there is a lot of advertising that needs to be hidden separately.

**Comment by krystian3w** [comment]
List no created to block Anti-adblock Walls...

**Comment by wizmak** [comment]
This list does not target anti-adblock walls.
