### ISSUE TITLE
appunwrapper.com

### ISSUE THREAD

**Issue by BjornGrylls** [abp-filters/abp-filters-anti-cv#210]
### List the website(s) where you encounter issues with ABP filters 

`https://www.appunwrapper.com/2014/02/27/god-of-light-walkthrough-and-strategy-guide/`

### Define the problem 

Not blocking ad

### Please add to list

appunwrapper.com##.appun-in-content

**Comment by wizmak** [comment]
@BjornGrylls 

> appunwrapper.com##.appun-in-content

This filter doesn't match any ad, and I can't see any ads on that page. Please provide some screenshot and description.

**Comment by wizmak** [comment]
@BjornGrylls closing this for now, please reopen when there are details to provide.

**Comment by BjornGrylls** [comment]
Hi
This is still not fixed. I've tried uBlock Origin and they also had the ad. Please add the filter to EasyList.

![image](https://user-images.githubusercontent.com/35100000/82731560-1d97ac80-9d08-11ea-8631-14563dc651ad.png)
The video is an ad.
![image](https://user-images.githubusercontent.com/35100000/82731565-2b4d3200-9d08-11ea-9d24-d1e854db5adf.png)
When you scroll down it appears on the bottom right of the page.

**Comment by wizmak** [comment]
@BjornGrylls Hi, I see what you mean now, let me ping EasyList. 

@ryanbr @Khrin Could you please take care? Blocking `https://mcd-sdk.playbuzz.com/embed/sdk.js` should do it.

**Comment by wizmak** [comment]
@BjornGrylls this should be fixed now in EasyList.
