### ISSUE TITLE
weebly.com

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#220]
**Website**

* `https://windowssof.weebly.com/`

**Problem**

* propellerads popups

**Fix**

```
weebly.com#$#abort-current-inline-script document.createElement String.fromCharCode
```

**Comment by wizmak** [comment]
`https://www.weebly.com/` offers web hosting services, so made it specific to `windowssof.weebly.com`.

**Comment by smed79** [comment]
The reported host is dead, you can remove it.
