### ISSUE TITLE
streaming-vostfr.com

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#229]
**Website**

* `https://streaming-vostfr.com/`

**Problem**

* admaven + propellerads popups

**Fix**

```
streaming-vostfr.com#$#abort-on-property-read decodeURIComponent
streaming-vostfr.com#$#abort-current-inline-script document.dispatchEvent String.fromCharCode
```

**Comment by smed79** [comment]
`streaming-vostfr.com` seems to be parked/dead.

**Comment by IThinkIAmCool** [comment]
streaming-vostfr.cc - parked

**Comment by wizmak** [comment]
> streaming-vostfr.cc - parked

@IThinkIAmCool The domain above is not on the anti-cv list. Thanks for pointing it out anyways.
