### ISSUE TITLE
almstba.tv

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#234]
**Website**

* `https://www.almstba.tv/`

**Problem**

* admaven + propellerads popups

**Fix**

```
almstba.tv#$#abort-on-property-read atob
```

**Comment by smed79** [comment]
@wizmak add 

`almstbatv.com,elmstba.com,elmstba.tv#$#abort-on-property-read decodeURIComponent`

**Comment by smed79** [comment]
Website dead, you can remove it.

**Comment by arsykan** [comment]
Hey @smed79 ,btw both almstbatv.com,elmstba.tv redirected me to https://www.almstba-tv.com/
