### ISSUE TITLE
gismeteo.md

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#241]
Please add a snippets: `gismeteo.md#$#abort-on-property-read Ya`

Example: https://www.gismeteo.md/weather-moscow-4368/2-weeks/

**Comment by dimisa-RUAdList** [comment]
Please add a snippets: `gismeteo.by#$#abort-on-property-read Ya`

**Comment by dimisa-RUAdList** [comment]
Please add a snippets: `gismeteo.ru#$#abort-on-property-read Ya`

**Comment by dimisa-RUAdList** [comment]
Please replace: `gismeteo.by,gismeteo.kz,gismeteo.md,gismeteo.ru#$#abort-on-property-read Ya`

To: `gismeteo.by,gismeteo.kz,gismeteo.md,gismeteo.ru#$#abort-current-inline-script document.createElement script`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace: `gismeteo.by,gismeteo.kz,gismeteo.md,gismeteo.ru#$#abort-current-inline-script document.createElement script`

To: `gismeteo.by,gismeteo.kz,gismeteo.md,gismeteo.ru#$#abort-on-property-read fetch`

**Comment by dimisa-RUAdList** [comment]
Please add a snippets: `beta.gismeteo.ru,www.gismeteo.by,www.gismeteo.kz,www.gismeteo.md#$#abort-current-inline-script document.createElement currentScript`

**Comment by dimisa-RUAdList** [comment]
Please replace: `beta.gismeteo.ru,www.gismeteo.by,www.gismeteo.kz,www.gismeteo.md#$#abort-current-inline-script document.createElement currentScript`

To: `beta.gismeteo.ru,www.gismeteo.by,www.gismeteo.kz,www.gismeteo.md#$#abort-current-inline-script document.createElement String.fromCharCode`

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Please replace: `beta.gismeteo.ru,www.gismeteo.by,www.gismeteo.kz,www.gismeteo.md#$#abort-current-inline-script document.createElement String.fromCharCode`

To: `beta.gismeteo.ru,www.gismeteo.by,www.gismeteo.kz,www.gismeteo.md#$#abort-on-property-read Object.prototype.AdvManager`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace: `beta.gismeteo.ru#$#abort-on-property-read Object.prototype.AdvManager`

To: `beta.gismeteo.ru#$#abort-on-property-read Object.prototype.AdblockCookieMatchingType`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace: 
`beta.gismeteo.ru#$#abort-on-property-read Object.prototype.AdblockCookieMatchingType`
and
`www.gismeteo.by,www.gismeteo.kz,www.gismeteo.md#$#abort-on-property-read Object.prototype.AdvManager`

To: `beta.gismeteo.ru,www.gismeteo.by,www.gismeteo.kz,www.gismeteo.md#$#abort-on-property-read Object.prototype.AdvManagerStatic`

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Something wrong. The snippet with "AdvManager" still works. And he is also listed in the filter list: https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt

**Comment by wizmak** [comment]
@dimisa-RUAdList can you please elaborate? I'm not sure I get what's the issue.

**Comment by dimisa-RUAdList** [comment]
@wizmak 
I think the problem is in the server. Somehow, the old rules are still there.
https://i.imgur.com/IJt5cGQ.jpg

**Comment by wizmak** [comment]
@dimisa-RUAdList this is crazy, I don't think it's the server though, it's like the commit 7469342 never happened, will push the changes again.

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace: `AdvManagerStatic`
To: `Direct`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add a snippets:
`beta.gismeteo.ru,www.gismeteo.by,www.gismeteo.kz,www.gismeteo.md#$#abort-on-property-read Object.prototype.adUsageStorageVars`

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Please add a snippets:

`beta.gismeteo.ru,www.gismeteo.by,www.gismeteo.kz,www.gismeteo.md#$#abort-on-property-read Object.prototype.isAllowedRepeatAds`

`beta.gismeteo.ru,www.gismeteo.by,www.gismeteo.kz,www.gismeteo.md#$#abort-on-property-read Object.prototype.adfoxCode`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace: `gismeteo.by,gismeteo.kz,gismeteo.md,gismeteo.ru#$#abort-on-property-read Object.prototype.adfoxCode; abort-on-property-read Object.prototype.adUsageStorageVars; abort-on-property-read Object.prototype.Direct; abort-on-property-read Object.prototype.isAllowedRepeatAds`

To: `gismeteo.by,gismeteo.kz,gismeteo.md,gismeteo.ru#$#abort-on-property-read Object.prototype.adfoxCode; abort-on-property-read Object.prototype.adUsageStorageVars; abort-on-property-read Object.prototype.Direct; abort-on-property-read Object.prototype.isAllowedRepeatAds; Object.prototype.pcodeWindowData`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace: `gismeteo.by,gismeteo.kz,gismeteo.md,gismeteo.ru#$#abort-on-property-read Object.prototype.adfoxCode; abort-on-property-read Object.prototype.adUsageStorageVars; abort-on-property-read Object.prototype.Direct; abort-on-property-read Object.prototype.isAllowedRepeatAds; Object.prototype.pcodeWindowData`

To: `gismeteo.by,gismeteo.kz,gismeteo.md,gismeteo.ru#$#abort-on-property-read Object.prototype.adfoxCode; abort-on-property-read Object.prototype.adUsageStorageVars; abort-on-property-read Object.prototype.Direct; abort-on-property-read Object.prototype.isAllowedRepeatAds; Object.prototype.pcodeWindowData; abort-on-property-read YaHeaderBiddingSettings`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace: `gismeteo.by,gismeteo.kz,gismeteo.md,gismeteo.ru#$#abort-on-property-read Object.prototype.adfoxCode; abort-on-property-read Object.prototype.adUsageStorageVars; abort-on-property-read Object.prototype.Direct; abort-on-property-read Object.prototype.isAllowedRepeatAds; Object.prototype.pcodeWindowData; abort-on-property-read YaHeaderBiddingSettings`

To: `gismeteo.by,gismeteo.kz,gismeteo.md,gismeteo.ru#$#abort-on-property-read Object.prototype.__confirmBlocks; abort-on-property-read Object.prototype.adfoxCode; abort-on-property-read Object.prototype.adUsageStorageVars; abort-on-property-read Object.prototype.Direct; abort-on-property-read Object.prototype.isAllowedRepeatAds; Object.prototype.pcodeWindowData; abort-on-property-read YaHeaderBiddingSettings`

**Comment by wizmak** [comment]
@dimisa-RUAdList 
btw, there is an `abort-on-property-read` missing before `Object.prototype.pcodeWindowData`.

**Comment by dimisa-RUAdList** [comment]
Lost :)

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Add please: `abort-on-property-read Object.prototype.getAdUsageStorage`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Add please: `abort-on-property-read Object.prototype.renderTo`

**Comment by mile-ne** [comment]
[added](https://github.com/abp-filters/abp-filters-anti-cv/commit/6df412ca3edc5a3780cd185d185b759ee0b33302)

**Comment by dimisa-RUAdList** [comment]
Add please: `abort-on-property-read Object.prototype.isNewLoader`

**Comment by dimisa-RUAdList** [comment]
@mile-ne
@wizmak
Add please: `abort-on-property-read Object.prototype.blockId`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Add please: `abort-on-property-read Object.prototype.BlockRenderSteps`
Del: `gismeteo.by,gismeteo.kz,gismeteo.md,gismeteo.ru#$#abort-on-property-read fetch`

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Add please: `abort-on-property-read Object.prototype.loadAd`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Add please: `abort-on-property-read Object.prototype.AdvManagerInit`

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Add please: `abort-on-property-read Ya`

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Add please: `abort-on-property-read Object.prototype.props.adv`, `abort-on-property-read Object.prototype.renderBlock`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Add please: `abort-on-property-read Object.prototype.AdvManagerLoaderRender`

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Please replace all with: `gismeteo.by,gismeteo.kz,gismeteo.md,gismeteo.ru#$#abort-on-property-read Object.prototype.getAdbBits`
