### ISSUE TITLE
Streamango

### ISSUE THREAD

**Issue by zoreu** [abp-filters/abp-filters-anti-cv#251]
### List the website(s) where you encounter issues with ABP filters 

https://streamango.com/embed/tbbfrdaanmacpnpk/

### Define the problem 
This filter is preventing streamango videos from playing

`streamango.com,fruithosts.net#$#abort-on-property-read BetterJsPop; abort-on-property-read isSandboxed; abort-on-property-read String.fromCharCode`

### List all of your filter lists
ABP filters
EasyList Portuguese+EasyList

Note: Streamango works without ad with this list without ABP filters
https://github.com/easylistbrasil/easylistbrasil

### Tell us about your system configuration 

- Operating system and version: Windows 10 1903
- Browser and version: Chrome 76.0.3809.100
- Adblock Plus version: 3.6.2

**Comment by wizmak** [comment]
@zoreu thanks for the report! should be fixed now. Let me know if you if you have any other issues.
