### ISSUE TITLE
P: NSFW xhamster.com (mobile mode)

### ISSUE THREAD

**Issue by zoreu** [abp-filters/abp-filters-anti-cv#258]
### List the website(s):

xhamster.com (mobile mode - android)

### Define the problem

popups appear only on mobile devices with mobile mode - Firefox (android) + Adblock plus

I made this rule on a test list on a computer with Chrome + User Agent Switcher
`xhamster.com#$#abort-on-property-read initials.pop`
but does not work on android in mobile mode on phone
desktop version is perfect, but in mobile no

My test filter (android):
https://github.com/easylistbrasil/repositorioteste

### List all of your filter lists 

ABP Filters
EasyList

### Tell us about your system configuration 

- Operating system and version: Android/8.1.0
- Firefox (android) + Adblock Plus
- Adblock Plus for Samsung internet

**Comment by krystian3w** [comment]
SNIPPET works form only privileged lists?

**Comment by wizmak** [comment]
@zoreu 
> xhamster.com#$#abort-on-property-read initials.pop

Unfortunately snippet filters, such as this one, are not yet supported on mobile.
Also, snippet filters only work when they're added locally, or from `abp-filters-anti-cv`

**Comment by zoreu** [comment]
@wizmak It's a shame not to be compatible
