### ISSUE TITLE
P: Openload

### ISSUE THREAD

**Issue by krystian3w** [abp-filters/abp-filters-anti-cv#259]
### List the website(s) where you encounter issues with ABP filters 
 
* `https://openload.co/f/7DBZvmQFvNM/zhengren.zip.001` https://github.com/ryanbr/fanboy-adblock/issues/1130
* `oload.vip/f/7DBZvmQFvNM/zhengren.zip.001`

### Define the problem 

SNIPPET generate anti-adblock and I cannot disable from dev tools. I must disable all list `ABP filters` (`ABP Anti-Circumvention Filter List`).

https://github.com/abp-filters/abp-filters-anti-cv/blob/e359beec42b495a9c210b50f2553d07c286f9dc3/english.txt#L264

### List all of your filter lists 

ABP Filters + EasyList + EasyList Polish

### Tell us about your system configuration 

- Operating system and version: Windows 10
- Browser and version: Chrome 76
- Adblock Plus version: 3.6.2

### Other details 

Why no works:

```
#@$#abort-on-property-write _pop; abort-on-property-read decodeURI; abort-on-property-read popjs; abort-on-property-read toString; abort-on-property-read AaDetector; abort-on-property-read BetterJsPop; abort-on-property-write Fingerprint2; abort-current-inline-script document.getElementById isSandboxed; abort-on-property-read window.open
```
```
#$@#abort-on-property-write _pop; abort-on-property-read decodeURI; abort-on-property-read popjs; abort-on-property-read toString; abort-on-property-read AaDetector; abort-on-property-read BetterJsPop; abort-on-property-write Fingerprint2; abort-current-inline-script document.getElementById isSandboxed; abort-on-property-read window.open
```
```
#@#abort-on-property-write _pop; abort-on-property-read decodeURI; abort-on-property-read popjs; abort-on-property-read toString; abort-on-property-read AaDetector; abort-on-property-read BetterJsPop; abort-on-property-write Fingerprint2; abort-current-inline-script document.getElementById isSandboxed; abort-on-property-read window.open
```

**Comment by zoreu** [comment]
PR: #260
