### ISSUE TITLE
tokopedia.com

### ISSUE THREAD

**Issue by arifrahman42** [abp-filters/abp-filters-anti-cv#262]
### List the website(s) where you encounter issues with ABP filters 

* https://www.tokopedia.com/search?st=product&q=samsung%20a20&lang=en

### Define the problem 

Native Product Promotion Ads by Tokopedia, and i found Adblock Plus are useless to block Tokopedia Native Ads.

### Screenshot(s) 

https://i.imgur.com/Fwwwopj.png

### List all of your filter lists 

* ABP Filters
* ABPIndo + EasyList
* EasyList
* EasyPrivacy
* Fanboy's Social Blocking List

### Tell us about your system configuration 

- Operating system and version: Windows 10 1507
- Browser and version: Firefox 67.0
- Adblock Plus version: 3.6.3

### Other details 

Tokopedia is one of the popular Online Shopping Platform in Indonesia
I just can block the banner ads and ads icon. But i can't block the Ads Search Result.

My Filter List (for Tokopedia):
tokopedia.com##.ta-space-link
tokopedia.com##.ta-cpm-blank-slot.new-cpm-design
tokopedia.com##.ta-tooltip-icon__toa
tokopedia.com##.ta-tooltip-content
tokopedia.com##.ta-tooltip
Screenshot: https://i.imgur.com/7l3sSqQ.png

I just found that ads are with the tag **src=topads**
Example:
``https://www.tokopedia.com/inspir3dshop/samsung-galaxy-a20-3gb-32gb-garansi-resmi-sein-1-tahun-red?src=topads`` (this link is an ad item result)
``https://www.tokopedia.com/samsung/samsung-galaxy-a20-3gb-32gb-black?trkid=f%3DCa0000L000P0W0S0Sh%2CCo0Po0Fr0Cb0_src%3Dsearch_page%3D1_ob%3D23_q%3Dsamsung+a20_po%3D1_catid%3D3054&whid=0`` (this is an organic item result)

**Comment by mile-ne** [comment]
Hey! Adblock Plus [anti-cv list](https://github.com/abp-filters/abp-filters-anti-cv/blob/master/README.md) targets reinjection of ads. 
I recommend you to post your message [here](https://forums.lanik.us/viewforum.php?f=94) to have a better follow up. And here is an [interesting read](https://adblockplus.org/blog/native-schmative-they-re-still-advertisements)
Have a good day and let me know if I can help with anything

**Comment by smed79** [comment]
fixed in https://hg.adblockplus.org/easylist/rev/d93d1cd5f07a
