### ISSUE TITLE
www.20min.ch

### ISSUE THREAD

**Issue by schmidicom** [abp-filters/abp-filters-anti-cv#265]
### List the website(s) where you encounter issues with ABP filters 

* www.20min.ch

### Define the problem 

The website loads a JavaScript that makes the page unusable when an AdBlocker is used.

### Screenshot(s) 

https://drive.google.com/file/d/1wwKrry3IPqfoncW9fOAg2tsdmEgX0oLK/view?usp=sharing

### List all of your filter lists 

ABP filters
Adblock Warning Removal List
EasyList Germany+EasyList

### Tell us about your system configuration 

- Operating system and version: Gentoo Linux
- Browser and version: Chromium 76.0.3809.132
- Adblock Plus version: 3.6.3

### Other details 

The JavaScript "/JS/ctwch.js" causes the problem.

**Comment by mapx-** [comment]
- ABP will not address anti adblocking issues (as per their policy + legal problems)
- use uBlock origin for such goals

**Comment by wizmak** [comment]
@schmidicom Thanks for your report! 
This list doesn't address such issues, I have to close this issue and mark as "won't fix", thank you for your understanding!
