### ISSUE TITLE
dokonlin.ru

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#266]
Please add a snippets: `dokonlin.ru#$#abort-on-property-read btoa`

Example: http://www.dokonlin.ru/video/bbc-drevnii-rim-rascvet-i-padenie-imperi-34-49.html

**Comment by wizmak** [comment]
> Example: http://www.dokonlin.ru/video/bbc-drevnii-rim-rascvet-i-padenie-imperi-34-49.html

Unable to reproduce unblocked ads on this page (using EasyList + RUadlist).

**Comment by dimisa-RUAdList** [comment]
Now the ad content downloaded from `dopc.cz` is hiding with `dokonlin.ru ### columns> div [id] [class]`. However, this rule is easy to circumvent, while the direct blocking of dopc.cz leads to a website breakdown.

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace: `dokonlin.ru#$#abort-on-property-read btoa`

To: `dokonlin.ru#$#abort-on-property-read btoa; abort-on-property-read String.prototype.charCodeAt`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `dokonlin.ru#$#abort-on-property-read document.head.appendChild`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `dokonlin.ru#$#abort-on-property-read document.head.appendChild; abort-on-property-read HTMLIFrameElement`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please del
