### ISSUE TITLE
igg-games.com

### ISSUE THREAD

**Issue by krystian3w** [abp-filters/abp-filters-anti-cv#273]
### List the website(s) where you encounter issues with ABP filters 

* `https://igg-games.com/little-misfortune-free-download.html`
* `https://igg-games.com/the-count-lucanor-437419672-free-download.html`
* `https://igg-games.com/heave-ho-free-download.html`

### Define the problem 

Random hard ads

### Screenshot(s) 

![obraz](https://user-images.githubusercontent.com/35370833/65458971-21102680-de4f-11e9-8885-efc5c328a278.png) |
--- |

### List all of your filter lists 

Default + ABP filters

### Tell us about your system configuration 

- Operating system and version:  Windows 10
- Browser and version:  Firefox 69
- Adblock Plus version: 3.6.2

### Other details 

`igg-games.com#$#abort-on-property-write btoa`

**Comment by mapx-** [comment]
from
https://github.com/uBlockOrigin/uAssets/commit/62379df5dad06790d6e5a4e72ad326028a02293d

**Comment by krystian3w** [comment]
Apparently not covered by copyright.
