### ISSUE TITLE
iltalehti.fi

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#275]
**Website**

* `https://www.iltalehti.fi/` (https://forums.lanik.us/viewtopic.php?f=114&t=43492)

**Problem**

* Sponsored articles

**List all of your filter lists**

- ABP filters
- EasyList
- EasyPrivacy

**Tell us about your system configuration**

- Browser and version: Firefox 69 / Chromium 76
- Adblock Plus version: 3.6.3

**Comment by krystian3w** [comment]
IMO outdated?
