### ISSUE TITLE
kinopoisk.ru

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#277]
Please add a snippet:
`www.kinopoisk.ru#$#abort-on-property-read Object.prototype.getYaContext`

**Comment by dimisa-RUAdList** [comment]
@mile-ne 
@wizmak 
Please replace with:
`www.kinopoisk.ru#$#abort-on-property-read Object.prototype.getAdUsageStorage`

**Comment by dimisa-RUAdList** [comment]
@mile-ne
@wizmak
Please replace with:
www.kinopoisk.ru#$#abort-on-property-read Object.prototype.__confirmBlocks

**Comment by dimisa-RUAdList** [comment]
@monzta 
Please replace with:
`www.kinopoisk.ru#$#abort-on-property-read Object.prototype.createAdContainer`

**Comment by monzta** [comment]
https://github.com/abp-filters/abp-filters-anti-cv/commit/ea87cd9

**Comment by dimisa-RUAdList** [comment]
@monzta
Please replace with:
`www.kinopoisk.ru#$#abort-on-property-read Object.prototype.createAdContainer`

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Please replace with:
www.kinopoisk.ru#$#abort-on-property-read Object.prototype.allowRepeatAds

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with:
`www.kinopoisk.ru#$#abort-on-property-read Object.prototype.doNotMatch`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with:
`www.kinopoisk.ru#$#abort-on-property-read Object.prototype.showBanner`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with:
`www.kinopoisk.ru#$#abort-on-property-read Object.prototype.isAdvManagerLoaded`

**Comment by wizmak** [comment]
30fbdc4

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with:
`www.kinopoisk.ru#$#abort-on-property-read Object.prototype.loadDirectScript`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with:
`www.kinopoisk.ru#$#abort-on-property-read Object.prototype.getAdUsageStorageVars`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with:
`www.kinopoisk.ru#$#abort-on-property-read Object.prototype.isNewLoader`

**Comment by wizmak** [comment]
a3e35c9

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with:
`www.kinopoisk.ru#$#abort-on-property-read Object.prototype.additional-banners`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with:
`www.kinopoisk.ru#$#abort-on-property-read Object.prototype.manageLastBanner`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with:
www.kinopoisk.ru#$#abort-on-property-read Object.prototype.requestMatchIdCookie

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with:
`www.kinopoisk.ru#$#abort-on-property-read Object.prototype.renderDirect`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.isRelAdFox`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.renderBanner`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.RTB`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `yastatic.net#$#abort-on-property-read Object.prototype.vast`

preroll

Example: https://widgets.kinopoisk.ru/discovery/film/84991/trailer/144307
