### ISSUE TITLE
NSFW 0xxx.ws

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#281]
**Website**

`https://0xxx.ws/`

**Problem**

* popunder

**Comment by mile-ne** [comment]
@smed79 let me know if this works for you [this](https://github.com/abp-filters/abp-filters-anti-cv/commit/86549cfe0433054bf9bc552ef350c8625202ad8f)

**Comment by mapx-** [comment]
use (added ages ago in uBo)
`0xxx.ws#$#abort-current-inline-script decodeURI decodeURIComponent`

your filter could break some functionalities

**Comment by smed79** [comment]
Still not fixed for me ==> popunder still there.

> Firefox 69.0.1 (64 bits)
> Chromium 76.0.3809.132 (64 bits)
> ABP 3.6.3

clear cache and cookies before testing.

**Comment by mile-ne** [comment]
@smed79  I have changed it :)
