### ISSUE TITLE
animebest.org

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#289]
Please add a snippet: animebest.org#$#abort-on-property-read document.head.appendChild

Example (adserver recoco.it): https://animebest.org/anime/4417-nanatsu-no-taizai-kamigami-no-gekirin-ab3.html

**Comment by dimisa-RUAdList** [comment]
No longer needed. I figured out how to do it differently: https://hg.adblockplus.org/ruadlist/rev/184bd59810c9#l1.12

**Comment by wizmak** [comment]
@dimisa-RUAdList I'll close it then.
