### ISSUE TITLE
razlozhi.ru

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#29]
Please add a snippet razlozhi.ru#$#abort-on-property-read Ya
https://reports.adblockplus.org/1e56e323-f63a-44e1-b2a1-dc5be53e5bab#tab=screenshot

**Comment by dimisa-RUAdList** [comment]
Please replace with: `razlozhi.ru#$#abort-on-property-read yaCounterId`

**Comment by dimisa-RUAdList** [comment]
I made a mistake.
Please replace with: `razlozhi.ru#$#abort-on-property-read advertSlice`

**Comment by dimisa-RUAdList** [comment]
Please replace with: `razlozhi.ru#$#abort-on-property-read hasAdvert`

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Please replace with: `abort-on-property-read Object.prototype.renderDirect`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.rtbInDirect`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.additionalBanners`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.getAdbBits`

**Comment by dimisa-RUAdList** [comment]
@arsykan 
Please replace with: `abort-on-property-read Object.prototype.showRTB`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.AdblockCookieMatchingType`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.AdList`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.doNotMatch`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.getAdditionalBanners`

**Comment by dimisa-RUAdList** [comment]
@arsykan
Please replace with: `abort-on-property-read Object.prototype.RtbTesttag`

**Comment by dimisa-RUAdList** [comment]
@arsykan
Please replace with: `abort-on-property-read Object.prototype.adblock`

**Comment by dimisa-RUAdList** [comment]
@arsykan
Please replace with: `abort-on-property-read Object.prototype.loadRtb`

**Comment by dimisa-RUAdList** [comment]
@arsykan
Please replace with: `abort-on-property-read Object.prototype.isFirstBanner`

**Comment by dimisa-RUAdList** [comment]
@arsykan
Please replace with: `abort-on-property-read Object.prototype.AdvManagerLoaderRender`

**Comment by dimisa-RUAdList** [comment]
@arsykan
Please replace with: `abort-on-property-read Object.prototype.loadBlocks`

**Comment by dimisa-RUAdList** [comment]
@arsykan
Please replace with: `abort-on-property-read Object.prototype.RTB`

**Comment by arsykan** [comment]
> abort-on-property-read Object.prototype.RTB

it seems for me it does not work. could you recheck?

**Comment by dimisa-RUAdList** [comment]
@arsykan 
`abort-on-property-read Object.prototype.setBlockData`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@wizmak 
`abort-on-property-read Object.prototype.decodeUInt8String`

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Please replace: `decodeUInt8String` with: `serverEncodeEnabled`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace: `serverEncodeEnabled` with: `isSsSkipTokenServerAuto`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace: `isSsSkipTokenServerAuto` with: `encodeUInt8String`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace: `encodeUInt8String` with: `createHostAsserter`

**Comment by dimisa-RUAdList** [comment]
@Aslatiel 
@delta9A 
@wizmak 
Please replace everything with: `||razlozhi.ru^$header=X-Yandex-Req-Id`

**Comment by dimisa-RUAdList** [comment]
@Aslatiel
@delta9A
@wizmak
Please replace with: `||razlozhi.ru^$script,header=report-to`
