### ISSUE TITLE
vidbm.com

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#291]
**Website**

* `https://www.vidbm.com/embed-v0ferq1c7x8q.html`

**Problem**

* propellerads popups

**Fix**

```
vidbm.com#$#abort-on-property-read Math.floor
```

**Comment by mapx-** [comment]
best fix
`vidbm.com#$#abort-current-inline-script Math zfgloaded`

**Comment by smed79** [comment]
@wizmak new domain `vidbem.com`

**Comment by wizmak** [comment]
@smed79 
> new domain `vidbem.com`
> 
> * `https://vidbem.com/s8h4bccxrcx6.html`

This domain is already added to the filter: `#$#abort-current-inline-script Math zfgloaded`
