### ISSUE TITLE
vgtimes.ru

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#297]
Please add a snippet: `vgtimes.ru#$#abort-on-property-read af_loader`

https://vgtimes.ru/

**Comment by wizmak** [comment]
@dimisa-RUAdList the filter breaks the search funcitonality

**Comment by dimisa-RUAdList** [comment]
Really. Very sorry. I have to constantly update the rules for this site and have already applied another solution earlier: https://hg.adblockplus.org/ruadlist/rev/ee1b267dee5a#l1.13

But still have to return to this question. When they adapt again, I will return to finding the right snippet.

**Comment by wizmak** [comment]
@dimisa-RUAdList I'm closing this issue for now then, feel free to re-open later.

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Please add a snippet: `vgtimes.ru#$#abort-on-property-write window.hi_url`

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Del please. There is now a generichide.

**Comment by MissiyaVGT** [comment]
How long will you mock the unfortunate girl? = (You just took and blocked all the content on the site.
