### ISSUE TITLE
reuters.com

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#3]
### List the website(s) where you encounter issues with ABP filters 

```
https://www.reuters.com/
```

### Define the problem 

unblocked ad-defend ads

### Screenshot(s)

* https://i.imgur.com/P5v1LHN.png

### List all of your filter lists

EasyList
EasyPrivacy
Fanboy's Annoyances
Adblock Warning Removal List

### Tell us about your system configuration 

- Operating system and version: Manjaro 17.1.11
- Browser and version: Firefox 61 / Chromium 67
- Adblock Plus version: 3.2

### Other details 

https://forums.lanik.us/viewtopic.php?f=62&t=41271
https://git.io/fNEVq

**Comment by wizmak** [comment]
Should be fixed now in ABP 3.3

**Comment by smed79** [comment]
An update is required here, the ads are not blocked.
- https://i.imgur.com/erLQutF.png

**Comment by mapx-** [comment]
@wizmak 
add
`||googletagservices.com/tag/js/gpt.js$script,domain=reuters.com`

**Comment by smed79** [comment]
Blocking `googletagservices.com` does not block the ads for me.

**Comment by mapx-** [comment]
yeah, don't work anymore.

@wizmak  you need an option badfilter or important (like in uBo - already proposed on ABP bug tracker) to override horrible filters in easylist

`@@/^https?:\/\/.*(com|net|de|org|us).*/$image,domain=reuters.com`

**Comment by wizmak** [comment]
@mapx-  thanks for the suggestion.
The filter `@@/^https?:\/\/.*(com|net|de|org|us).*/$image,domain=reuters.com` is now removed from EasyList (https://github.com/easylist/easylist/commit/8dd269d0e1f3290e87a945cbaf3b15c9f54e9eb5)
