### ISSUE TITLE
rambler.ru, gazeta.ru

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#30]
Please add a snippet gazeta.ru,rambler.ru#$#abort-on-property-read atob
https://reports.adblockplus.org/b972bdb3-e2d0-446f-aa86-d5e35f2703f4#tab=screenshot
https://reports.adblockplus.org/98d7fe34-e4b5-47d7-b61a-66af6cbb54c7#tab=screenshot

And championat.com#$#abort-on-property-read atob
https://reports.adblockplus.org/b2031ac7-d059-47b0-9560-5be4c33df16d#tab=screenshot

**Comment by dimisa-RUAdList** [comment]
I get a lot of reports every day with complaints about this ad. This advertisement is targeted and its presence and properties will depend on the accumulated cookies. The above snippets solve the problem.

**Comment by dimisa-RUAdList** [comment]
Please remove the snippet: rambler.ru,gazeta.ru,championat.com#$#abort-on-property-read atob

It does not work anymore, and more than that it interferes.

**Comment by dimisa-RUAdList** [comment]
Please add a snippet:
`championat.com,gazeta.ru,lenta.ru,rambler.ru#$#abort-current-inline-script Object Anti-AdBlock-url-cache`
And the associated blocking rule: `||paracesquare.rambler.ru^`

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Please del: `championat.com,gazeta.ru,lenta.ru,rambler.ru#$#abort-current-inline-script Object Anti-AdBlock-url-cache`

**Comment by wizmak** [comment]
Should I also remove `||paracesquare.rambler.ru^$domain=championat.com|gazeta.ru|lenta.ru|rambler.ru`?

**Comment by dimisa-RUAdList** [comment]
Yes
