### ISSUE TITLE
cikavosti.com

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#304]
Please add a snippets: `cikavosti.com,versii.if.ua#$#abort-on-property-read weekCallbacks`

Example: 
https://cikavosti.com/vcheni-za-dopomogoyu-3d-printera-stvorili-kuleneprobivni-bloki/
https://versii.if.ua/novunu/u-frankivsku-na-vulitsi-vasilianok-vodiy-zbiv-velosipedista/

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Please rename the issue, if possible: cikavosti.com > ext.week.news

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Please add: `zik.ua`

Example: https://zik.ua/news/economics/kholdynh_akhmetova_dtek_enerho_hotuietsia_do_defoltu_cherez_koronavirus_963668

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `fakty.ua`

Example: https://fakty.ua/

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `112.ua`

Example: https://112.ua/ekonomika/v-ukraine-vstupayut-v-silu-novye-pravila-dlya-perevoda-deneg-533125.html

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `pingvin.pro`

Example: https://pingvin.pro/gadgets/news-gadgets/minczyfra-prezentuvala-osvitnij-serial-czyfrovi-groshi.html

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `technoportal.com.ua`

Example: https://technoportal.com.ua/smartfony/47963

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `dialogs.org.ua`

Example: http://dialogs.org.ua/tech/37711/

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `newsone.ua`

Example: https://newsone.ua/news/accidents/v_chernovcah_lihach_sbil_zhenshhinu_s_malenkim_vnukom_na_zebre_foto.html

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `volynpost.com`

Example: http://www.volynpost.com/news/167577-na-volyni-blyskavka-vbyla-molodogo-cholovika

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `uanews.org.ua`

Example: https://uanews.org.ua/post/show/1592293421-u-pravoslavnih-hristiyan-rozpochavsya-petriv-pist

**Comment by wizmak** [comment]
75e442ac4fb5867862f85043196e7cece9c9cc4f
(for some reason issues are not referenced properly in commit messages)

**Comment by dimisa-RUAdList** [comment]
@arsykan
@wizmak
Please add: `gorodkiev.com.ua`

Example: http://www.gorodkiev.com.ua/53300-na-kievshhine-otec-pyanica-pytalsya-ubit-svoego-syna.html

**Comment by dimisa-RUAdList** [comment]
@arsykan
@wizmak
`112.ua ~> 112ua.tv`, `newsone.ua ~> newsoneua.tv`
Please transfer all the rules for these domains.

**Comment by dimisa-RUAdList** [comment]
@arsykan
@wizmak
Please add: `4studio.com.ua`

Example: https://4studio.com.ua/novyny/desyatky-meshkantsiv-lvova-vymagayut-u-vlady-rozchystyty-dorogy-vid-snigu-foto/

**Comment by dimisa-RUAdList** [comment]
@arsykan
@wizmak
Please add: `kriminal.tv`

Example: https://kriminal.tv/news/v_dnepre_na_prospekte_javornitskogo_mashina_sbila_dvoih_ljudej_moment_video.html

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `informator.ua`

Example:  https://kiev.informator.ua/2021/04/27/v-kieve-perekroyut-proezd-na-sezde-s-ulitsy-getmana-na-prospekt-pobedy/

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak
Please del: `zikua.tv`

**Comment by dimisa-RUAdList** [comment]
@wizmak 
@Aslatiel 
@delta9A 

Please del: `mignews.com.ua`
