### ISSUE TITLE
VertaMedia (Adtelligent) Ads

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#305]
Please add a snippets:
`1news.com.ua,365news.biz,4mama.ua,7days-ua.com,cikavosti.com,comments.ua,depo.ua,dnews.dn.ua,dv-gazeta.info,fedpress.ru,glavnoe.ua,glavnoe24.ru,inforpost.com,kurskcity.ru,liga.net,narodna-pravda.ua,pingvin.pro,pl.com.ua,real-vin.com,russianshowbiz.info,semobile.com.ua,vchaspik.ua,versii.if.ua,volyninfo.com,womo.ua#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

**Comment by dimisa-RUAdList** [comment]
Please add: `unn.com.ua`

Example: https://www.unn.com.ua/uk/news/1838979-na-vinnichchini-kit-zadushiv-9-misyachnu-ditinu-yaka-spala-u-vizochku

**Comment by dimisa-RUAdList** [comment]
Please add: `volynpost.com`

Example: http://www.volynpost.com/news/153662-na-volyni-deputata-sudytymut-za-vbyvstvo-teschi

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Please add: `poltava365.com`

Example: https://poltava365.com/gogol-22-fakti-pro-zhittya-ta-smert-pismennika.html

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `wpristav.ru`

Example: https://wpristav.ru/news/v_mosule_arestovali_muftija_igil/2020-01-18-46386

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `asiaplustj.info`

Example: https://www.asiaplustj.info/ru/news/world/20200127/v-rabote-pochti-mailru-proizoshel-masshtabnii-sboi

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `sud.ua`

Example: https://sud.ua/ru/news/ukraine/161052-v-ukraine-vvodyat-elektronnuyu-aktsiznuyu-marku-chto-nado-znat

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `vchaspik.ua`

Example: https://vchaspik.ua/region/474502-v-lisichanske-nayden-shron-s-oruzhiem-kotoryy-ostavila-v-svoem-garazhe-zhenshchina

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `cheline.com.ua`

Example: https://cheline.com.ua/news/society/bilya-silpo-rozgulyuvav-velicheznij-grizun-foto-206118

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `dyvys.info`

Example: https://dyvys.info/2020/03/24/tragediya-u-likarni-z-vikna-p-yatogo-poverhu-vykynuvsya-patsiyent/

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `zik.ua`

Example: https://zik.ua/news/economics/kholdynh_akhmetova_dtek_enerho_hotuietsia_do_defoltu_cherez_koronavirus_963668

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `novavlada.info`

Example: https://novavlada.info/biznes/novosti/odnogo-iz-krupneyshih-ukrainskih-internet-provayderov-podozrevayut-v-neuplate-nalogov

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `tverisport.ru`

Example: https://tverisport.ru/sport/football/eks-igrok-volgi-vozrozhdaet-futbol-v-rajtsentre-tverskoj-oblasti/

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Up!

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: pg11.ru

Example: https://pg11.ru/news/77571

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `expert.in.ua`

Example: http://expert.in.ua/mezhdunarodnaya-analitika/0/868-milliard-chelovek-v-blizhajshie-50-let-mogut-stat--klimaticheskimi-migrantami--

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add:
`volnorez.com.ua`
`newsone.ua`
`autotheme.info`
`odessa-life.od.ua`

Example: 
http://volnorez.com.ua/?post_type=post&p=244151
https://newsone.ua/news/accidents/v_chernovcah_lihach_sbil_zhenshhinu_s_malenkim_vnukom_na_zebre_foto.html
https://autotheme.info/news/125146-ukrainskie-voditeli-zakryvayut-nomera-ot-videofiksatsii.html
https://odessa-life.od.ua/article/ozeram-delty-dunaja-vernuli-prirodnyj-vodoobmen-v-chem-polza-unikalnogo-proekta-jekologov-foto

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `economistua.com`

Example: https://economistua.com/mvf-prizval-ukrainu-sohranit-nezavisimost-natsionalnogo-banka/

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `uainfo.org`

Example: https://uainfo.org/blognews/1592989194--riven-bidi-bilshiy-nizh-u-2008-mu-avakov-pokazav-zhahlivi.html

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `ternopillive.com.ua`, `te.ua`, `uanews.org.ua`, `fraza.com`

Example:
https://ternopillive.com.ua/mykulyneczki-kovbasy-zabezpechuyut-navkolyshnyu-gromadu-yakisnoyu-produkcziyeyu/

https://www.gazeta-misto.te.ua/vijskova-sluzhba-lyshe-za-bazhannyam-yunaky-pryzovnogo-viku-zmozhut-navchatysya-u-vyshah/

https://uanews.org.ua/post/show/1592293421-u-pravoslavnih-hristiyan-rozpochavsya-petriv-pist

https://fraza.com/column/291721-film-chernyj-kop-obratnaja-storona-rasizma-

**Comment by wizmak** [comment]
8fd9803ed09f29ad314512d551e516f401d20228
(for some reason issues are not referenced properly in commit messages)

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `gov.ua`

Example:  https://ukurier.gov.ua/uk/news/ukrayina-zakupit-u-turechchini-udarni-bezpilotniki/

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `argumentiru.com`

Example: https://argumentiru.com/2020/07/is-514586

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `itechua.com`

Example:
https://itechua.com/gadgets/109317

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `mind.ua`

Example:
https://mind.ua/news/20215525-lukashenko-zayaviv-shcho-ne-mozhe-protistoyati-telegram-kanalam

**Comment by dimisa-RUAdList** [comment]
@wizmak
@arsykan 
Please add: `ekovolga.com`

Example:
https://ekovolga.com/science/1236

**Comment by dimisa-RUAdList** [comment]
@wizmak
@arsykan
Please add: `ratel.kz`

Example:
https://ratel.kz/asiope/vse_nachalos_s_mamina

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `cn.ua`, `podpricelom.com.ua`, `begemot.media`, `beauty.ua`

Example:
https://cntime.cn.ua/fotonovini/item/29427-chernihivski-biznesmeny-vlashtuvaly-stykhiine-smittiezvalyshche-foto
http://podpricelom.com.ua/read/politics/krymskuyu-massandru-prodadut-s-molotka.html
https://begemot.media/news/v-ukrainu-vezut-lekarstva-kotorye-voz-priznala-neeffektivnymi/
https://beauty.ua/dietika/fitnes-diets/2658-dieta-nomer-5-osobennosti-i-menyu-na-nedelyu

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `apnews.com.ua`

Example: https://apnews.com.ua/ua/news/u-khmelnitckii-oblasti-vnaslidok-dtp-zaginuli-dva-pidlitki/

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `novynarnia.com`

Example: https://novynarnia.com/2020/10/28/zelenskyj-pryznachyv-tsyutsyuru/

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `tverigrad.ru`

Example: https://tverigrad.ru/publication/v-tveri-sbili-velosipedista-9/

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `golosinfo.com.ua`, `wworld.com.ua`

Example:
https://www.golosinfo.com.ua/na-prykarpatti-dva-dni-shukayut-pensionera-yakyj-pishov-u-lis/
https://wworld.com.ua/recepts/72762

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `politnavigator.net`

Example: https://www.politnavigator.net/amerikancy-podgotovili-ukrainskuyu-motopekhotnuyu-brigadu-k-polnomu-unichtozheniyu-v-donbasse.html

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `greenpost.ua`

Example: https://greenpost.ua/news/koly-v-krayini-nastane-pik-epidemiyi-i23312

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `rivnenews.com.ua`

Example: https://www.rivnenews.com.ua/2020/11/29/u-rivnomu-bilia-lahuny-dtp-z-marshrutkoiu-video/

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `khersonline.net`

Example: https://khersonline.net/video/

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `iz.com.ua`

Example: http://iz.com.ua/zaporoje/zaporozhskiy-biolog-pokazal-udivitelnyie-gribyi-ostrova-hortitsa-foto

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `westnews.info`

Example: https://westnews.info/news/Zatrimali-grupu-vijskovosluzhbovciv-ZSU-yaki-torguvali-zbroyeyu.html

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `praktika-vlasti.com.ua`

Example: https://praktika-vlasti.com.ua/32697-2/

**Comment by dimisa-RUAdList** [comment]
@arsykan 
@wizmak
Please add: `day.kyiv.ua`, `vsviti.com.ua`

Example:
http://day.kyiv.ua/ru/news/251220-raboty-po-vosstanovleniyu-vodnogo-puti-po-reke-pripyat-ugrozhayut-millionam-ukraincev
http://vsviti.com.ua/news/121467

**Comment by dimisa-RUAdList** [comment]
@arsykan
@wizmak
Please add: `telekritika.ua`

Example: https://telekritika.ua/stala-izvestna-data-telepremery-filma-zaboronenij-na-1-1/

**Comment by dimisa-RUAdList** [comment]
@arsykan
@wizmak
Please add: `risu.ua`

Example: https://risu.ua/10-najvplivovishih-religijnih-lideriv-svitu-subyektivna-versiya_n114942

**Comment by dimisa-RUAdList** [comment]
@arsykan
@wizmak
Please add: `volynua.com`

Example: https://volynua.com/posts/rozpochali-zimoviy-zbir-futbolisti-lutskoi-volini-viyshli-z-vidpustki-video

**Comment by dimisa-RUAdList** [comment]
@arsykan
@wizmak
Please add: `gorodkiev.com.ua`

Example: http://www.gorodkiev.com.ua/53300-na-kievshhine-otec-pyanica-pytalsya-ubit-svoego-syna.html

**Comment by dimisa-RUAdList** [comment]
@arsykan
@wizmak
Please add: `glavpost.ua`

Example: https://glavpost.ua/news/v-dtp-s-perevorotom-na-bolshoy-panasovskoy-postradal-voditel-lanos/

**Comment by dimisa-RUAdList** [comment]
@arsykan
@wizmak
Please add: `portal.lviv.ua`, `4studio.com.ua`, `moirebenok.ua`, `mi100.info`

Example:
https://portal.lviv.ua/news/2021/02/08/u-lvovi-prosiat-zaboronyty-prodazh-bud-iakoho-alkoholiu
https://4studio.com.ua/novyny/desyatky-meshkantsiv-lvova-vymagayut-u-vlady-rozchystyty-dorogy-vid-snigu-foto/
https://www.moirebenok.ua/mother/pitanie-mother/dlya-horoshego-sna-9-luchshih-trav-kotorye-pomogut-pri-bessonnitse/
https://mi100.info/2021/02/08/na-horodenkivshhyni-ryatuvalnyky-buksyruvaly-avto-z-chotyrma-lyudmy-video/

**Comment by dimisa-RUAdList** [comment]
@arsykan
@wizmak
Please add: `begemot-media.com`

Example: https://begemot-media.com/news/putin-rasskazal-ob-otklyuchenii-rossii-ot-zarubezhnyh-internet-platform/

**Comment by dimisa-RUAdList** [comment]
@arsykan
@wizmak
Please add: `vgolos.com.ua`

Example: https://vgolos.com.ua/news/zhinka-zrobyla-zamovlennya-kur-yeru-vyplesnuty-chaj-v-oblychchya-yiyi-kolyshnogo-kohanogo-video_1376562.html

**Comment by dimisa-RUAdList** [comment]
@arsykan
@wizmak
Please add: `marieclaire.ua#$#abort-current-inline-script redram /загрузка.../`

Example: https://marieclaire.ua/lifestyle/rasskaz-sluzhanki-data-vyhoda-4-sezona-i-novyj-trejler-seriala/

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `procherk.info#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example: https://procherk.info/resonance/2-cherkassy-news/90888-jak-pandemija-zminjue-osvitnij-protses-chi-gotovi-mi-do-tsogo

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `chas.cv.ua#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example: https://chas.cv.ua/health/82852-на-буковині-зафіксовано-396-нових-випадк.html

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `mycompplus.ru#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example: https://mycompplus.ru/ruki-/31-comp/4346-transcend-storejet-25m3s-1.html

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `ngp-ua.info#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example: https://ngp-ua.info/

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `kolizhanka.com.ua#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example:
https://kolizhanka.com.ua/kabachkova-ikra-perevireni-retsepty-z-majonezom-bez-majonezu-yaki-mayut-buty-u-kozhnoyi-gospodyni/

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Please add: `grad.ua#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example:
https://grad.ua/lenta-novostey/90114-v-odesskoj-oblasti-obitaet-pjat-vidov-zmej.html

**Comment by dimisa-RUAdList** [comment]
@wizmak 
@manuel-martinez-dev 
The site breaks down: `https://reyestr.court.gov.ua/`

And it doesn't matter what is indicated instead of `/ru-n4p|ua-n4p|загрузка.../`. It looks like there is some problem with the snippet template itself `abort-current-inline-script`. At least, it also breaks down and `https://vesti.ua/`.

The problem appeared after the release Adblock Plus 3.11.1. I think right now you need to delete: `gov.ua#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`, because there are a lot of complaints about breakdowns on `*.gov.ua.` And notify the developers.

**Comment by wizmak** [comment]
@dimisa-RUAdList 
There is indeed an issue with `abort-current-inline-script` after the latest ABP update (3.11.1) I will disable related filters until the issue is resolved.

**Comment by wizmak** [comment]
Disabled filters for now: beada42

**Comment by dimisa-RUAdList** [comment]
@wizmak 
While the abort-current-inline-script snippet was disabled, the list of domains changed. Currently, the rule should look like this:
`1news.com.ua,365news.biz,4mama.ua,4studio.com.ua,7days-ua.com,apnews.com.ua,argumentiru.com,asiaplustj.info,autotheme.info,beauty.ua,begemot-media.com,begemot.media,chas.cv.ua,cheline.com.ua,cikavosti.com,cn.ua,comments.ua,day.kyiv.ua,depo.ua,dnews.dn.ua,dv-gazeta.info,dyvys.info,economistua.com,edinstvennaya.ua,ekovolga.com,expert.in.ua,fedpress.ru,forpost.media,fraza.com,glavnoe.ua,glavnoe24.ru,glavpost.ua,golosinfo.com.ua,gorodkiev.com.ua,gov.ua,grad.ua,greenpost.ua,inforpost.com,itechua.com,iz.com.ua,khersonline.net,kolizhanka.com.ua,krymr.com,kurskcity.ru,liga.net,mi100.info,mind.ua,moirebenok.ua,mycompplus.ru,nakanune.ru,narodna-pravda.ua,nashbryansk.ru,newsoneua.tv,ngp-ua.info,novavlada.info,novynarnia.com,odessa-life.od.ua,pg11.ru,pingvin.pro,pl.com.ua,podpricelom.com.ua,politnavigator.net,poltava365.com,portal.lviv.ua,praktika-vlasti.com.ua,prm.ua,procherk.info,profootball.ua,radiosvoboda.org,ratel.kz,real-vin.com,risu.ua,rivnenews.com.ua,rusjev.net,russianshowbiz.info,semobile.com.ua,sport-kr.com.ua,sud.ua,superdom.ua,te.ua,telekritika.ua,ternopillive.com.ua,treebuna.info,tverigrad.ru,tverisport.ru,tvoymalysh.com.ua,uainfo.org,uanews.org.ua,uatv.ua,unn.com.ua,vchaspik.ua,versii.if.ua,vgolos.com.ua,viva.ua,volnorez.com.ua,volyninfo.com,volynpost.com,volynua.com,vsviti.com.ua,westnews.info,womo.ua,wpristav.ru,wworld.com.ua,zikua.tv#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

**Comment by dimisa-RUAdList** [comment]
@arsykan 
@manuel-martinez-dev 
@wizmak 
Please add: `mignews.com.ua#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example: `https://mignews.com.ua/proisshestviya/24991128.html`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak
Please add: `zbirna.com#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example: `https://zbirna.com/post/sergei-nazarenko-rezultat-nuzhen-zdes-i-seichas`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak
Please add: `panoptikon.org#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example: `https://panoptikon.org/world/137491-sered-migrantiv-bilja-kordonu-bilorusi-zafiksovano-pershij-vipadok-covid-19.html`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak
Please add: `inkorr.com,kr.ua,rv.ua#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example:
`https://inkorr.com/skandalnyy-piven-bilya-ofisu-prezydenta-v-kyyevi-lyshyvsya-bez-golovy-foto-16823`
`https://tribuna.kr.ua/2021/11/22/horoskop-na-22-lystopada-2021-shcho-obitsiaiut-astrolohy/`
`https://7dniv.rv.ua/zdorovya/chervonyy-i-korysnyy-podarunok-oseni/`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak
Please add: `oukr.info#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example: `https://oukr.info/u-naczionalnogo-muzeyu-arhitektury-ta-budivnycztva-zyavyvsya-vlasnyj-sajt-2.html`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak
Please add: `np.pl.ua,ukrrain.com#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example:
`https://np.pl.ua/2021/12/vohko-ta-kholodno-iakoiu-bude-pohoda-na-poltavshchyni-u-pershi-vykhidni-zymy/`
`https://ukrrain.com/timoshenko_pidkolola_zelenskogo-_chekali_na_perevorot-_a_prijshla_lishe_zima.html`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak
Please add: `zp.ua#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example: `https://sich.zp.ua/horoskop-na-tyzhden-6-12-hrudnia`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak
Please add: `reporter.ua#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example: `https://dp.reporter.ua/articles/v-dnepre-zaderzhali-muzhchinu-kotorogo-9-let-razyskivaet-policija-kryma`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak
Please add: `news24today.info,vnn24.ru#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak
Please add: `cvnews.cv.ua,ifnews.org.ua,lvnews.org.ua,rvnews.rv.ua,tenews.org.ua#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak
Please del: `zikua.tv`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak
Please add: `ck.ua#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example: `https://provce.ck.ua/za-try-metry-vid-bereha-na-dnipri-vtopyvsia-cherkasets/`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak
Please add: `vlast.kz#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example: `https://vlast.kz/novosti/48648-15-ugolovnyh-del-rassleduetsa-po-faktam-gosizmeny-prevysenia-polnomocij-i-popytke-zahvata-vlasti-v-kazahstane.html`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak
Please add: `kg-portal.ru#$#abort-current-inline-script document.createElement Math.random`

Example: `https://kg-portal.ru/comments/103917-login-cherez-socseti-snova-zarabotal/`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak
Please add: `nnews.com.ua#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example: `https://nnews.com.ua/amd-vypravyla-problemu-pidvysannya-windows-10-ta-11-u-systemah-z-ryzen-ta-vklyuchenym-ftpm.html`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak
Please add: `rivne.media#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example: `https://rivne.media/news/po-kievu-vdarili-raketami-e-postrazhdali`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak
Please add: `theageoffootball.com#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example: `https://theageoffootball.com/novosti/italia/54666/david-neres-zaczikaviv-granda-italijskogo-futbolu/`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak
Please add: `autotema.org.ua#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example: `https://autotema.org.ua/u-kitaї-debyutuye-elektrichnij-sedan-hozon-neta-s-iz-zapasom-xodu-1000-kilometriv/`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak
Please add: `kh.u#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example: `https://www.slk.kh.ua/oblast-online/pecenigi/ziteliv-pecenig-zaklikaut-buti-pilnimi-isnue-nebezpeka-minuvanna-vorogom.html`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak
Please add: `planetanovosti.com#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example: `https://www.planetanovosti.com/deystvitelno-li-krasnoe-vino-ponizhaet-arterialnoe-davlenie`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak
Please add: `ukranews.com#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example: `https://ukranews.com/ua/news/870142-zsu-prodovzhuyut-uspishnyj-kontrnastup-na-hersonshhyni-ok-pivden`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak
Please add: `pik.net.ua#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example: `https://pik.net.ua/2022/07/26/vybuhy-na-odeshhyni-rosiyany-zavdaly-udariv-z-aviatsiyi/`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak
Please del: `ternopillive.com.ua`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak
Please add: `agroter.com.ua#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example: `https://agroter.com.ua/2022/07/29/mikrogrant-dlya-sadivnykiv-instrukcziya-yak-otrymaty/`

**Comment by dimisa-RUAdList** [comment]
@manuel-martinez-dev
@wizmak
Please add: `mega-music.pro#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example: `https://mega-music.pro/yevgen-klopotenko-usi-moyi-restorany-v-pershyj-den-pislya-peremogy-budut-bezkoshtovnymy/`

**Comment by dimisa-RUAdList** [comment]
@manuel-martinez-dev
@wizmak
Please add: `strana.news,strana.today#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example:
`https://strana.news/opinions/405684-ataka-na-media-idet-pod-falshivym-flahom-trebovanij-es.html`
`https://strana.today/opinions/403838-prezident-ne-sbezhal-no-ja-ne-verju-chto-emu-ne-snjatsja-ljudi-iz-buchi.html`

**Comment by dimisa-RUAdList** [comment]
@manuel-martinez-dev
@wizmak
Please add: `ogo.ua,showdream.org#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example:
`https://ogo.ua/articles/view/2022-09-26/126709.html`
`https://showdream.org/novini/kulinarya/34917-meksikanska-zapkanka-z-myasom-ta-ovochami.html`

**Comment by dimisa-RUAdList** [comment]
@manuel-martinez-dev
@wizmak
Please add: `promin.cv.ua#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example: `https://promin.cv.ua/2022/09/26/ukraina-otrymala-vid-lytvy-50-bronetransporteriv-m113.html`

**Comment by dimisa-RUAdList** [comment]
@manuel-martinez-dev
@wizmak
Please add: `firtka.if.ua#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example: `https://firtka.if.ua/blog/view/v-ivano-frankivsku-suditimut-dvokh-kolaboratsionistok-z-luganshchini`

**Comment by dimisa-RUAdList** [comment]
@manuel-martinez-dev
@wizmak
Please add: `newsua.one#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example: `https://newsua.one/news/u-ssha-diznalisya-pro-rozsliduvannya-fbr-proti-trampa.html`

**Comment by dimisa-RUAdList** [comment]
@manuel-martinez-dev
@wizmak
Please add: `alter-science.info#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example: `https://alter-science.info/novosti/fermer-iz-chekhii-nashel-zolotoj-poyas-bronzovogo-veka.html`

**Comment by dimisa-RUAdList** [comment]
@manuel-martinez-dev
@wizmak
Please del: `wpristav.ru`

**Comment by dimisa-RUAdList** [comment]
@manuel-martinez-dev
@wizmak
Please add: `kop.net.ua#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example: `https://kop.net.ua/tankovyj-dvygun-i-1000-syl-yakym-buv-najpotuzhnishyj-i-najshvydshyj-kraz/`

**Comment by dimisa-RUAdList** [comment]
@manuel-martinez-dev
@wizmak
Please add: `avtodream.org#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example: `https://avtodream.org/vsi-novini/avtosvit/53601-volkswagen-gotuye-do-prezentaciji-tayemnichij-elektrokar.html`

**Comment by dimisa-RUAdList** [comment]
@delta9A 
Please add: `gazeta1.com#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example: `https://www.gazeta1.com/statti/u-krementsi-spijmaly-serijnogo-zlodiya/`

**Comment by dimisa-RUAdList** [comment]
@wizmak 
@Aslatiel 
@delta9A 

Please del: `mignews.com.ua`, `semobile.com.ua`

**Comment by dimisa-RUAdList** [comment]
@Aslatiel
@delta9A

Please add: `transkarpatia.net#$#abort-current-inline-script document.createElement redtram`

Example: `https://transkarpatia.net/world/130894-scho-prihovuiut-zhnki-ntimn-sekreti-vsh-znakv-zodaku.html`

**Comment by dimisa-RUAdList** [comment]
@Aslatiel 
@delta9A 
Please add: `pravdatutnews.com#$#abort-current-inline-script document.createElement /ru-n4p|ua-n4p|загрузка.../`

Example: `https://pravdatutnews.com/politics/2023/08/24/28524-norvegiya-peredaye-ukrayini-rakety-iris-t`
