### ISSUE TITLE
znanija.com

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#306]
Please add a snippets:  `znanija.com#$#abort-on-property-write getAdBlockType`

https://znanija.com/task/8165732

**Comment by wizmak** [comment]
@dimisa-RUAdList Can not reproduce ads, can you add some details? what ads does it target? what does the filter do? thanks!

**Comment by dimisa-RUAdList** [comment]
If you refresh the page several times, then the content for adblock users will be hidden until they watch the video ad.
https://i.imgur.com/Afctwa4.jpg
