### ISSUE TITLE
NSFW xhamster.com

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#310]
**Website**

* `https://xhamster.com/` (**NSFW**)

**Problem**

* popunder everywhere you click.

**Comment by dimisa-RUAdList** [comment]
`xhamster.com#$#abort-on-property-read wig-popunder`

**Comment by smed79** [comment]
@wizmak `xhamster.com` redirect to `xhamster.one`

**Comment by wizmak** [comment]
> @wizmak `xhamster.com` redirect to `xhamster.one`

@smed79 I'm not experiencing redirect to `xhamster.one`, but I can see the popunder issue there, will push a fix in couple of minutes.

**Comment by smed79** [comment]
@wizmak popunder ==> `xhamster2.com` (nsfw)

**Comment by wizmak** [comment]
> popunder ==> `xhamster2.com` (nsfw)

@smed79 Fixed, thanks!
