### ISSUE TITLE
www.classic-retro-games.com block ad block (bab)

### ISSUE THREAD

**Issue by peace2000** [abp-filters/abp-filters-anti-cv#312]
Site `www.classic-retro-games.com` uses a known block ad block (bab) script to tell adblock users to disable their adblock.

![kuva](https://user-images.githubusercontent.com/17256841/70309833-0d9e1600-1817-11ea-89fd-b5f27611d45a.png)

I recommend a general filter as bab is a known anti ablock script:

`/bab.min.js$script`

`https://blockadblock.com/`

**Comment by mapx-** [comment]
ABP cannot circumvent anti adblocking (legal reasons)

**Comment by peace2000** [comment]
Oh. All right then.

**Comment by mile-ne** [comment]
Hey @peace2000! thank you for the suggestion. Indeed we can't circumvent anti-adblocking walls or for legal reasons. Still you make whatever use of your extension, meaning that in the advanced tab in the custom filters panel you can add, or edit any filter that would make your browsing experience better!

**Comment by smed79** [comment]
How to add a custom filter to ABP https://help.eyeo.com/en/adblockplus/custom-filters?
