### ISSUE TITLE
streaming-one.com

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#315]
**Website**

* `https://streaming-one.com/`

**Problem**

* propellerads popups

**Fix**

* `streaming-one.com#$#abort-current-inline-script Math zfgloaded`

**Comment by smed79** [comment]
Site seems to be dead, you can remove it.

**Comment by arsykan** [comment]
Hey @smed79 , the site is working for me, could you recheck?

**Comment by smed79** [comment]
You are right. site is working again.
