### ISSUE TITLE
NSFW hclips.com

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#316]
**Website**

* `https:// hclips.com/` (**NSFW**)

**Problem**

* popunder

**Fix**

* `hclips.com#$#abort-on-property-read open`

**Comment by mapx-** [comment]
@mile-ne did you test the filter ?

tested in chrome and I still get popups

Another (ABP) issue: in the logger (devtools) I see only a snippet filter (the other with hclips) but not the last one or any other snippet added as custom filter.

However, you should test and add:
`hclips.com#$#abort-on-property-read btoa`

**Comment by mile-ne** [comment]
hey @mapx- 
I did test the filter but I haven't noticed that they were still ads on the wild. I changed the snippet and can confirm that ads and popups are now blocked.
Regarding that bug in abp dev tools panel I already reported that issue. will look for it add it

**Comment by smed79** [comment]
@wizmak could you please add `hclips.com#$#abort-on-property-read open`

**Comment by smed79** [comment]
@wizmak popunder, add
- `hclips.com#$#abort-on-property-read adver`
