### ISSUE TITLE
yandex.ru

### ISSUE THREAD

**Issue by denisbalyko** [abp-filters/abp-filters-anti-cv#32]
### List the website(s) where you encounter issues with ABP filters 

* russian.txt

### Define the problem 

You are breaking the basic search functionality. removing significant results in addition to advertising. These are obviously incorrect filters in the commit https://github.com/abp-filters/abp-filters-anti-cv/commit/b63dd297428bb0c92e31d0d7e55024b00b016d90

### Screenshot(s) 

**this is not advertising!**

![image](https://user-images.githubusercontent.com/638190/50152185-02836a80-02d4-11e9-9d9c-5385b57f49de.png)

### List all of your filter lists 

- ABP filters
- RuAdList+EasyList

### Tell us about your system configuration 

- Operating system and version: macOS Mojave 10.14.2
- Browser and version: Chrome 71.0.3578.98
- Adblock Plus version: v3.4.2

**Comment by denisbalyko** [comment]
@wizmak ping

**Comment by wizmak** [comment]
Unable to reproduce. Can you disable `ABP filters` list, and highlight the element(s) in the page that should not be hidden in a screenshot?

**Comment by m-peshekhonov** [comment]
@wizmak 
Request example: https://yandex.ru/search/?text=iphone&lr=213

You are blocked part of the search results, which is not advertising. Class `.sitelinks` in `.serp-item` is not only in advertising.

Simple:

<img width="1342" alt="2018-12-18 20 10 00" src="https://user-images.githubusercontent.com/1990156/50170430-f06bf100-0300-11e9-8e37-bed97a228c9b.png">

**Comment by denisbalyko** [comment]
You can change the request, for example, to "[buy tickets](https://yandex.ru/search/?lr=213&text=buy%20tickets)" / "[купить билеты](https://yandex.ru/search/?lr=213&text=купить%20билеты)" / "[купить билеты в кино](https://yandex.ru/search/?lr=213&text=купить%20билеты%20в%20кино)". And compare results with and without Adblock.

**Comment by nadoske** [comment]
Hello.

Today found a strong drop in traffic to the site from the search engine Yandex. When checking, we found that Adblock Plus, with ABP filters enabled, removes our site from the search.

On the first screenshot ABP filters - off

![screenshot_1](https://user-images.githubusercontent.com/45977058/50173900-ce2aa100-0309-11e9-921d-4f713ec2e37a.png)

On the second screenshot ABP filters - enabled

![screenshot_2](https://user-images.githubusercontent.com/45977058/50173926-dedb1700-0309-11e9-958a-f62ebb976342.png)

We will be grateful if you return our clients to us. Thank.

ps We apologize for errors, this text is written by Google translation

**Comment by nadoske** [comment]
Hello.

Today found a strong drop in traffic to the site from the search engine Yandex. When checking, we found that Adblock Plus, with ABP filters enabled, removes our site from the search.

On the first screenshot ABP filters - off

![screenshot_2](https://user-images.githubusercontent.com/45977058/50174046-2eb9de00-030a-11e9-967f-b6274f430ffd.png)

On the second screenshot ABP filters - enabled

![screenshot_1](https://user-images.githubusercontent.com/45977058/50174064-3bd6cd00-030a-11e9-8b92-04cabfbd8659.png)


We will be grateful if you return our clients to us. Thank.

ps We apologize for errors, this text is written by Google translation

**Comment by wizmak** [comment]
Hello @nadoske 

Can you manually update your `ABP filters` list and check again?
Looks like it's no longer an issue, see screenshot below:
![yandex_ 32_2](https://user-images.githubusercontent.com/38558046/50174987-fad7bc00-02fb-11e9-8f4e-e214ebdbb218.JPG)

**Comment by nadoske** [comment]
Updated. There is no problem. Thank.
