### ISSUE TITLE
NSFW playboy.de

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#331]
**Website**

* `playboy.de` (**NSFW**)

**Problem**

* AdDefend ads

**List all of your filter lists**

- ABP filters
- EasyList
- EasyPrivacy
- AWRL

**Fix**

- `playboy.de#$#abort-on-property-read window.screen`

**Comment by mapx-** [comment]
wrong filter:
go to `https://www.playboy.de/girls/playmates/unsere-playmates-stellen-sich-vor-miss-dezember-2019-lena-bednarska`

video broken

**Comment by wizmak** [comment]
@smed79 the filter breaks the video player.

**Comment by dimisa-RUAdList** [comment]
May be: `playboy.de#$#abort-on-property-read Object.prototype.networkListener` ?

**Comment by wizmak** [comment]
> May be: `playboy.de#$#abort-on-property-read Object.prototype.networkListener` ?

@dimisa-RUAdList 
Good one, just modified it to `playboy.de#$#abort-current-inline-script Object.prototype.networkListener`
