### ISSUE TITLE
anime.anidub.life, online.anidub.com

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#338]
Please add a snippet: `anime.anidub.life,online.anidub.com#$#abort-on-property-read brrand`

Branding

Example: 
https://anime.anidub.life/
https://anime.anidub.life/

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read bgc`

**Comment by dimisa-RUAdList** [comment]
Delete please. It doesn't work anymore.

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak
Please add: `anidub.club,anidub.link,anidub.life,online.anidub.com#$#abort-on-property-read brblob`

**Comment by dimisa-RUAdList** [comment]
@manuel-martinez-dev
@wizmak

Unfortunately, the last rule breaks class `popular` on the main pages of domains. For example - `https://online.anidub.life/`.

This could be fixed in styles, [like this](https://github.com/easylist/ruadlist/commit/972fd461ed46bf05701f89589913248c54105b84#diff-101cad5cbd9d78a6d3b42c7aa62f8c51477585a061b3ea3eaab0a2a51afd5331R145).

But over the past eight years, this functionality has not yet appeared in Adblock Plus. [2014](https://issues.adblockplus.org/ticket/756/) > [2020](https://gitlab.com/eyeo/adblockplus/abc/adblockpluscore/-/issues/210)

Please del: `anidub.club,anidub.link,anidub.life,online.anidub.com#$#abort-on-property-read brblob`

**Comment by manuel-martinez-dev** [comment]
Hi @dimisa-RUAdList thanks for the message,

when you mention it breaks, what exactly happens?, I've checked and I could not find the issue

**Comment by dimisa-RUAdList** [comment]
@manuel-martinez-dev 
You can see it right now at: `https://online.anidub.club/`, `https://online.anidub.com/`.

On `https://online.anidub.life/`, branding is now disabled, so this problem is not there.

**Comment by dimisa-RUAdList** [comment]
@manuel-martinez-dev
@wizmak

I propose to remove the clickability and the background of the banners >

`anidub.club,anidub.link,anime.anidub.life,online.anidub.com,online.anidub.life#$#override-property-read URL.createObjectURL noopFunc; prevent-listener click window.open`

Example: `https://online.anidub.club/`

**Comment by dimisa-RUAdList** [comment]
@manuel-martinez-dev
@wizmak
Please add: `anime.anidub.com`

**Comment by dimisa-RUAdList** [comment]
@manuel-martinez-dev
@wizmak

Please add: `abort-on-property-read brblob`

Example: `https://online.anidub.club/`

**Comment by dimisa-RUAdList** [comment]
@Aslatiel
@delta9A
@manuel-martinez-dev
@wizmak

Please replace with:
`anidub.vip,anidubonline.com,tr.anidub.com#$#prevent-listener click window.open; abort-on-property-read brblob`

**Comment by dimisa-RUAdList** [comment]
@Aslatiel
@delta9A
@manuel-martinez-dev
@wizmak

Please del: `tr.anidub.com`

**Comment by dimisa-RUAdList** [comment]
@delta9A 

Please del: `anidub.vip,anidubonline.com#$#override-property-read ad.done true`

The webmaster reacted quickly and made the rule useless.

**Comment by dimisa-RUAdList** [comment]
@delta9A 

I suggest adding: `anidub.vip,anidubonline.com#$#override-property-read ad.active.timeout 0`

Let's see the reaction.

**Comment by dimisa-RUAdList** [comment]
@Aslatiel 
@delta9A 

Please del: `override-property-read ad.active.timeout 0`

The rule has become useless.
