### ISSUE TITLE
hlamer.ru, zloekino.ru

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#339]
Please add a snippet: `hlamer.ru,zloekino.ru#$#abort-on-property-read open`

Popup when clicking on the side of the background.

Example: https://hlamer.ru/

See also: https://github.com/abp-filters/abp-filters-anti-cv/issues/280

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Please replace: `zloekino.ru` > `zloekino.com`

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Please add: `zloekino.ru`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `zloekino.su`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `serialfilm.ru`

**Comment by dimisa-RUAdList** [comment]
@manuel-martinez-dev 

Please replace: `serialfilm.ru,zloekino.su,zloekino.ru,zloekino.com` on: `anicat.ru`

**Comment by manuel-martinez-dev** [comment]
I had a typo on the commit msg while pushing, but changes were made.
https://github.com/abp-filters/abp-filters-anti-cv/commit/0911abaec4bad5b95adacbf7ab7fcb6ec747dec6

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak

Please replace: `anicat.ru` > `wseries.ru`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak

Please replace: `wseries.ru` > `zloekino.site`
Example: `https://zloekino.site/series`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak
Please replace: `zloekino.site` > `oveg.ru`
Example: `https://oveg.ru/series`
