### ISSUE TITLE
search.seznam.cz - cinema schedules are disappearing from changes in #31

### ISSUE THREAD

**Issue by BrianSLedoux** [abp-filters/abp-filters-anti-cv#34]
### List the website(s) where you encounter issues with ABP filters 

* search.seznam.cz

### Define the problem 

As changes made for issue #31, now element for cinemas are being blocked. With query "kino dnes vecer"  the element showing movie theatres schedule is being blocked for no reason.

### Screenshot(s) 

the element that is blocked: https://prnt.sc/lwun6s

### List all of your filter lists 

Disabled - Adblock Warning Removal List
Active - ABP filters
Active - EasyList Czech and Slovak+EasyList
Active - Allow nonintrusive advertising

### Tell us about your system configuration 

- Operating system and version: Windows 10
- Browser and version: Chrome 71
- Adblock Plus version: 3.4.2

**Comment by smed79** [comment]
@BrianSLedoux Dont create new topics without searching for [existing issues](https://github.com/abp-filters/abp-filters-anti-cv/issues?utf8=%E2%9C%93&q=search.seznam.cz). That to provide better continuity and tracking for each case.
