### ISSUE TITLE
liveinternet.ru

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#35]
Please add a snippet liveinternet.ru#$#abort-on-property-read Ya

**Comment by dimisa-RUAdList** [comment]
Please replace this snippet with: 
`liveinternet.ru#$#abort-on-property-read atob; abort-on-property-read Ya; abort-on-property-read yandex_metrika_callbacks`

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Please replace to: `liveinternet.ru#$#abort-on-property-read YaHeaderBiddingSettings`

**Comment by dimisa-RUAdList** [comment]
@monzta 
@wizmak 
Please replace to: `liveinternet.ru#$#abort-on-property-read atob`

**Comment by monzta** [comment]
https://github.com/abp-filters/abp-filters-anti-cv/commit/fec3db4

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Please add: `liveinternet.ru#$#abort-on-property-read Object.prototype.Direct`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace to: `abort-on-property-read Object.prototype.isAdfoxPageTurbo`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.headerBidding`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.getMatchidManager`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.AdvManager`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.AdvManagerStatic`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype._bannerId`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.adUnitsStorage`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.__confirmBlocks`

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Please replace with: `abort-on-property-read Object.prototype.bannerOptions`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.Rtb`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.Rtb`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.BaseAdFox`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.renderDirect`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.getAdbBits`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.loadDirectScript`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.BlockRenderProducts`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.bannerId`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.AdfoxEvents`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.isAdblock`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.RtbDataParsed`

**Comment by dimisa-RUAdList** [comment]
@arsykan 
Please replace with: `abort-on-property-read Object.prototype.containerId`

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Please replace with: `abort-on-property-read Object.prototype.AdblockCookieMatchingType`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.renderBanner`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.loadBanner`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.showBanner`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.AdfoxErrors`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.useYandexDomain`

**Comment by dimisa-RUAdList** [comment]
@wizmak
@arsykan
Please replace with: `abort-on-property-read Object.prototype.addAdfoxNamespace`

**Comment by dimisa-RUAdList** [comment]
@wizmak
@arsykan
Please replace with: `abort-on-property-read Object.prototype.adfoxDomain`

**Comment by dimisa-RUAdList** [comment]
@wizmak
@arsykan
Please replace with: 
`abort-on-property-read Object.prototype.requestBids; abort-on-property-read Object.prototype.WidgetRenderFinish`

**Comment by dimisa-RUAdList** [comment]
@arsykan 
Please add: `abort-on-property-read Object.prototype.isAdBlocked`

**Comment by arsykan** [comment]
@dimisa-RUAdList 
Hey, old filters still working for me. do you want to add those new ones instead of replacing the old?

**Comment by dimisa-RUAdList** [comment]
Let's leave it as it is for now. The old ad embed code is working there right now and the current rules are really enough.

I will follow this.

**Comment by dimisa-RUAdList** [comment]
@arsykan
Please replace with: `abort-on-property-read Object.prototype.bidManager; abort-on-property-read Object.prototype.initWidgetBlock`
The old rules don't work again.

**Comment by dimisa-RUAdList** [comment]
@arsykan
Please replace with: `abort-on-property-read Object.prototype.adblock; abort-on-property-read Object.prototype.ADFOX`

**Comment by dimisa-RUAdList** [comment]
@arsykan
Please replace with: `abort-on-property-read Object.prototype.doNotMatch`

**Comment by wizmak** [comment]
As this is a known issue, it does not need to remain open.

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Please add: `abort-on-property-read Object.prototype.AdChosen`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `abort-on-property-read Object.prototype.dataSource`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.callBids`

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Please replace everything with: `abort-on-property-read Object.prototype.isMatchIdCookieGotten`

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Please replace with: `abort-on-property-read Object.prototype.onAdStart`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.loadData`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.logData`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.sendRequestWithUrl`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `abort-on-property-read Object.prototype.createErrorBids`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace everything with: `abort-on-property-write Object.defineProperty`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `abort-on-property-read window.parse`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `abort-on-property-read Object.prototype._bid`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `abort-on-property-read Object.prototype.getRenderTo`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `abort-on-property-read Object.prototype.allowLowerLevelDomains`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `abort-on-property-read Object.prototype.requestParsed`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `abort-on-property-read Object.prototype.isAnYandexLoader`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `abort-on-property-read Object.prototype.SSR_BLOCKS`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `abort-on-property-read Object.prototype.onRender`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `abort-on-property-read Object.prototype.cbManagers`

**Comment by dimisa-RUAdList** [comment]
@arsykan 
@wizmak
Please replace with: `abort-on-property-read Object.prototype.parseResponseData`

**Comment by dimisa-RUAdList** [comment]
@arsykan 
@manuel-martinez-dev 
@wizmak 

Please replace: `liveinternet.ru#$#abort-on-property-read Object.prototype.parseResponseData`

with: `||liveinternet.ru/$header=content-type=application/json`

**Comment by dimisa-RUAdList** [comment]
@manuel-martinez-dev 
Really. Then like this: `/^https?://www\.liveinternet\.ru/[^\s]{100,}/$header=content-type=application/json`

**Comment by dimisa-RUAdList** [comment]
@delta9A 
@Aslatiel 
@arsykan
@manuel-martinez-dev
@wizmak

Please replace with: `liveinternet.ru#$#abort-current-inline-script window.yaContextCb; cookie-remover ayabnsr; prevent-listener /beforeunload|DOMContentLoaded|pagehide/ '0x';`

Note that the snippet `abort-current-inline-script window.yaContextCb` doesn't work properly, nor does this:
https://gitlab.com/eyeo/snippets/-/issues/16
https://gitlab.com/eyeo/snippets/-/issues/17
https://gitlab.com/eyeo/snippets/-/issues/18

I added it for the future, in the hope that the Eyeo developers will someday make a fix, and use the real case for debugging and testing.

**Comment by dimisa-RUAdList** [comment]
@Aslatiel
@delta9A
@wizmak
Please replace everything with: 
`/^https?://www\.liveinternet\.ru/[^\s]{100,}/$xmlhttprequest,header=content-type=application/javascript`

**Comment by dimisa-RUAdList** [comment]
@delta9A
@Aslatiel
@wizmak
Please replace with: `/^https?://www\.liveinternet\.ru/[^\s]{100,}/$script,header=report-to`

**Comment by dimisa-RUAdList** [comment]
@Aslatiel
@delta9A
@wizmak
Please replace with: `/^https?://www\.liveinternet\.ru/[^\s]{100,}/$script,header=Nel`

**Comment by dimisa-RUAdList** [comment]
@Aslatiel
@delta9A
@wizmak
Please replace with: `/^https?://www\.liveinternet\.ru/[^\s]{100,}/$script,header=X-Content-Type-Options`

**Comment by dimisa-RUAdList** [comment]
@Aslatiel
@delta9A
@wizmak
Please replace with: `/^https?://www\.liveinternet\.ru/[^\s]{100,}/$script,header=x-consumed-content-encoding`

**Comment by dimisa-RUAdList** [comment]
@Aslatiel
@delta9A
@wizmak
Please replace with: `/^https?://www\.liveinternet\.ru/[^\s]{100,}/$script,header=X-Robots-Tag`

**Comment by dimisa-RUAdList** [comment]
@Aslatiel
@delta9A
@wizmak
Please replace with: `/^https?://www\.liveinternet\.ru/[^\s]{100,}/$xmlhttprequest,header=X-Xss-Protection`
