### ISSUE TITLE
porno365.blog (NSWF)

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#356]
Please add a snippet: `porno365.blog#$#abort-on-property-read J2CC`

Popup after clicking on any video. Only on the first visit. Or after clearing cookies.

`http://porno365.blog/`

**Comment by wizmak** [comment]
@dimisa-RUAdList 
Couldn't reproduce, but added the filter anyways since you could, and it does not seem to break anything.

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Yes, I also do not see this object. Perhaps it was a test. I will be watching this site for some time and will let you know if the current situation remains stable.

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Please del
