### ISSUE TITLE
gamemag.ru

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#366]
Please add a snippet: `gamemag.ru#$#abort-on-property-write keepAdblock`

Detect: https://i.imgur.com/haNRwM5.jpg

Example: https://gamemag.ru/

**Comment by wizmak** [comment]
@dimisa-RUAdList 
> Detect: https://i.imgur.com/haNRwM5.jpg

I understand this is an adblock detection message, this list does not address that.
