### ISSUE TITLE
onemanhua.com

### ISSUE THREAD

**Issue by cjx82630** [abp-filters/abp-filters-anti-cv#367]
### List the website(s) where you encounter issues with ABP filters 
https://www.onemanhua.com/12202/1/497.html
* 

### Define the problem 
Popunder ads appear after adding whitelist to avoid anti-adblocker

### List all of your filter lists 
Easylist China + Easylist

### Tell us about your system configuration 

- Operating system and version: win10
- Browser and version: chrome80
- Adblock Plus version: 3.8

### Other details 
onemanhua.com#$#abort-on-property-read __cad.cpm_popunder
onemanhua.com#$#abort-on-property-read __ad

**Comment by cjx82630** [comment]
The domain name has changed. Redirect to ohmanhua.com

**Comment by smed79** [comment]
@cjx82630 Warn with "**NSFW**" when it is about adult content.

**Comment by cjx82630** [comment]
The domain name ohmanhua.com has changed to cocomanhua.com

**Comment by cjx82630** [comment]
The domain name "cocomanhua.com" has changed to  cocomanga.com
