### ISSUE TITLE
viamichelin.com

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#37]
Hi,

**List the website(s) where you encounter issues with ABP filters**

```
https://www.viamichelin.com/
https://www.viamichelin.at/
https://www.viamichelin.be/
https://www.viamichelin.ch/
https://www.viamichelin.co.uk/
https://www.viamichelin.de/
https://www.viamichelin.es/
https://www.viamichelin.fr/
https://www.viamichelin.ie/
https://www.viamichelin.it/
https://www.viamichelin.nl/
https://www.viamichelin.pl/
https://www.viamichelin.pt/
```

**Define the problem**

Tab Under redirect to `booking.com` when clicking the search button.

**Ss**

https://imgur.com/a/wBTyKW0

**List all of your filter lists**

ABP filters
EasyList
EasyPrivacy
Adblock Warning Removal List

**Tell us about your system configuration**

- Browser and version: Firefox 64 / Chromium 71
- Adblock Plus version: 3.4.2

**Other details**

https://issues.adblockplus.org/ticket/2095
[uA@a780a44](https://git.io/fjYbm)

**Comment by hfiguiere** [comment]
We need to handle $popunder for this.

**Comment by smed79** [comment]
> We need to handle $popunder for this.

[#2095](https://issues.adblockplus.org/ticket/2095) closed (rejected)

**Comment by hfiguiere** [comment]
I filed https://gitlab.com/eyeo/adblockplus/adblockpluscore/issues/95 to replace it.

**Comment by smed79** [comment]
@wizmak Lost cause ?

**Comment by wizmak** [comment]
@smed79 Just think it doesn't make sense to keep it open here for so long, while we have [this filed issue](https://gitlab.com/eyeo/adblockplus/adblockpluscore/issues/95) Hubert shared above.
