### ISSUE TITLE
elektroda.pl

### ISSUE THREAD

**Issue by kulfoon** [abp-filters/abp-filters-anti-cv#372]
### List the website(s) where you encounter issues with ABP filters 

* https://www.elektroda.pl/

### Define the problem 

AD WALL - when visiting the website for the first time, it hides/replaces the content of website with black background + an advertisement + a "CONTINUE TO WEBSITE" ("PRZEJDŹ DO STRONY") button which if you click on it will skip the ad & black backgorund and continue to website, if not clicking the button it will automatically continue to webpage after like 10 sec. The ad is already hidden by filter lists, but the BLACK WALL + CONTINUE button still not.

### Screenshot(s) 

https://github.com/MajkiIT/polish-ads-filter/issues/15475#issue-545451380

### List all of your filter lists 

The most noticeable ad lists related to the issue:

EasyList
EasyList Polish
ABP Anti-Circumvention Filter List
POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
POL: Oficjalne polskie filtry przeciwko alertom o Adblocku

### Tell us about your system configuration 

- Operating system and version: Win 7 SP1 64 PL
- Browser and version:  Firefox 75 / Opera 67
- Adblock Plus version: 

### Other details 

The example/test ABP solution is here: https://github.com/MajkiIT/polish-ads-filter/issues/16063#issue-595772093 (together with uBO solution which has been already added to POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda)

**Comment by gargul2** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/15475
https://github.com/MajkiIT/polish-ads-filter/issues/16063

**Comment by kulfoon** [comment]
It needs an update, because they bypassed it and changed script name from `popupStatus` to `loadElement` https://github.com/MajkiIT/polish-ads-filter/issues/16063#issuecomment-624162133
