### ISSUE TITLE
xxxtor.com (NSWF)

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#373]
Please add a snippet: `xxxtor.com#$#abort-current-inline-script document.querySelectorAll popMagic`

Clickunder

Example: `https://xxxtor.com/`

**Comment by smed79** [comment]
@wizmak You can apply the same filter for the mirrors sites `.org` and `.info`

**Comment by dimisa-RUAdList** [comment]
As much as I did not try to get on these mirrors, the redirect to the com all the time occurs.

**Comment by wizmak** [comment]
Same for me, both `www.xxxtor.info` and `www.xxxtor.org` are redirected to `xxxtor.com`.
