### ISSUE TITLE
https://www.chimica-online.it/

### ISSUE THREAD

**Issue by samu698** [abp-filters/abp-filters-anti-cv#376]
### List the website(s) where you encounter issues with ABP filters 
``https://www.chimica-online.it/``

### Define the problem 
When opening the page the page the page detects adBlock and stops working, the page does this by using a bait DIV element with the id "banner_ad", when the DIV is removed the page will stop.

I also found the script the does this and their website:
``https://blockadblock.com/blockadblock_basic_script.php``

I fixed the problem by adding this to my personal filters:
``www.chimica-online.it#@##banner_ad``

### List all of your filter lists 

- Acceptable Ads
- AdBlock custom filters
- Anti-Circumvention filters
- EasyList

### Tell us about your system configuration 

- Operating system and version: Windows 10
- Browser and version: Chrome 81.0.4044.113
- Adblock version: 4.10.0

**Comment by wizmak** [comment]
@samu698 
The anti-cv list does not address anti-adblock walls. Thank you for submitting this issue thought.
