### ISSUE TITLE
upflix.pl

### ISSUE THREAD

**Issue by kulfoon** [abp-filters/abp-filters-anti-cv#378]
### List the website(s) where you encounter issues with ABP filters 

* https://upflix.pl/

### Define the problem 

Anti-Adblock, add `upflix.pl#$#abort-on-property-read adBlock`

### Screenshot(s) 

https://github.com/MajkiIT/polish-ads-filter/issues/16205#issue-606984723

### List all of your filter lists 

EasyList
EasyList Polish
ABP Anti-Circumvention Filter List
POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
POL: Oficjalne polskie filtry przeciwko alertom o Adblocku

### Tell us about your system configuration 

- Operating system and version: Win 7 SP1 64 PL
- Browser and version:  Firefox 75 / Opera 67
- Adblock Plus version:

**Comment by wizmak** [comment]
@kulfoon The anti-cv list does not address anti-adblock messages. Thank you for submitting this issue though.

**Comment by kulfoon** [comment]
No offence but...

Similarity between `anti-circumvention` / `circumvention ads` and `anti adblock` wordings can be confusing for internet users so that they can think it means the same, because both of them contains the same word `anti`, especially for non-native english users, also `circumvention ads` and `anti adblock` both tries to fool / trick adblockers, furthermore, some of the links you guys put in the [replies](https://github.com/abp-filters/abp-filters-anti-cv/issues/262#issuecomment-526128634) lead to [articles ](https://adblockplus.org/blog/native-schmative-they-re-still-advertisements) containing 7 `anti-adblock` phrases, one of them in a big red banner. Instead of constanly repeating the same reply "The anti-cv list does not address anti-adblock messages." in these [anti-adblock issues](https://github.com/abp-filters/abp-filters-anti-cv/issues?q=%22anti+adblock%22), you could simply put it in the [desciption](https://github.com/abp-filters/abp-filters-anti-cv#abp-anti-circumvention-filter-list) or in the [contributing guide](https://github.com/abp-filters/abp-filters-anti-cv/blob/master/CONTRIBUTING.md) or in the [issue template](https://github.com/abp-filters/abp-filters-anti-cv/issues/new). 

It reminds me this confusing [uBO's tooltip issue](https://github.com/easylist/easylistgermany/issues/70#issuecomment-619544549) which can be misleading so that someone can think the more generic filters, the more performance they can eat.

I wonder how many yet in my life, I and others will meet such confusing/misleading descriptions, and then, the authors will deny it completely, saying it doesn't mean what it seems to mean, making people looking like complete fools, and noone likes when someone else make him looking like a fool. Is that on purpose? Having so many "invalid" `anti-adblock` requests on your issue tracker, yet still you hadn't updated either the description / nor the issue template / nor the contributing guide with less-confusing information, instead, you still keep pasting replies what this list doesn't addess. How can it be this way.

One more time anyone make me looking like a fool and I will end... watching [this](https://www.youtube.com/watch?v=2q3MPDIA5yc) or [this](https://www.youtube.com/watch?v=F1d41395fVY).

"Have a good day and let me know if I can help with anything".

**Comment by monzta** [comment]
> you could simply put it in the [desciption](https://github.com/abp-filters/abp-filters-anti-cv#abp-anti-circumvention-filter-list) or in the [contributing guide](https://github.com/abp-filters/abp-filters-anti-cv/blob/master/CONTRIBUTING.md) or in the [issue template](https://github.com/abp-filters/abp-filters-anti-cv/issues/new).

Did you read the description? The second line says 
> Adblock Plus (ABP) filter list to fight "circumvention ads." 

and its description ("Introduction") is quite clear: 

> Some providers have begun to show ads that are harder to detect for ad-blocking tools like ABP, thus tricking ad-blocker users into downloading and displaying unrequested and intrusive advertising ("circumvention ads").
> 
> This filter list is drafted and maintained by ABP and is intended to detect and block circumvention ads.

**Comment by kulfoon** [comment]
I did, and still the point still is the same what is "quite clear" / not confusing for one/you, might be confusing / not "quite clear" for others, as proven  [here](https://github.com/abp-filters/abp-filters-anti-cv/issues?q=%22anti+adblock%22) and [here](https://github.com/easylist/easylistgermany/issues/70#issuecomment-619544549), expecially if one is non-native english and/or unexperienced, anti-adblock messages are circumvention as well, they may be easly confused with circumvention ads, just like a wasp with a bee. There is a reason why in [uAssets issue tracker](https://github.com/uBlockOrigin/uBlock-issues#ublock-issues) they added "**Do not post any filter list issues or issues where website's functionality is broken**. We have [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues) for that, post there instead." part., if you don't want to add similiar: "**Do not post any anti-adblock issues**. There is Adblock Warning Removal List: [link 1](https://easylist-downloads.adblockplus.org/antiadblockfilters.txt) / [link 2](https://easylist.to/pages/other-supplementary-filter-lists-and-easylist-variants.html) for that, post [there](https://forums.lanik.us/) instead, although it's unrelated to us" it's your choice. I expressed my opinion and provided arguments, if you disagree with them, I'll not be stopping you and let's just end the discussion.

**Comment by monzta** [comment]
Thanks for your input. I'll leave it up to @wizmak and @arsykan as they currently work here the most.

**Comment by kulfoon** [comment]
wizmak & montza - thank you too
