### ISSUE TITLE
dailymail.co.uk cxresources

### ISSUE THREAD

**Issue by mapx-** [abp-filters/abp-filters-anti-cv#38]
- use a uk ip (vpn)
- go to `https://www.dailymail.co.uk/news/article-6481297/Chelsea-fan-accused-racially-abusing-Sterling-says-called-MANC-c-not-black-one.html`
- `cxresources` stuff (see in the abp logger) and some ads appear
- existent filter does not seem to work
`dailymail.co.uk#$#abort-on-property-read cxrgx_`
- working filter (at least for me) => `dailymail.co.uk#$#abort-on-property-read adverts`
- you could also add (some instart references in the code)
`dailymail.co.uk#$#abort-on-property-read I11C`

**Comment by wizmak** [comment]
Fixed with the suggested filter. I think the second filter for instart is unnecessary.
