### ISSUE TITLE
wp.pl

### ISSUE THREAD

**Issue by adblock-filters** [abp-filters/abp-filters-anti-cv#380]
### List the website(s) where you encounter issues with ABP filters 
* `www.wp.pl`

### Define the problem 
Circumvented ads on main website from WP group. Issue concerns only main site, not WP subsites.

### Screenshot(s) 
![Screenshot from 2020-04-30 10-35-05](https://user-images.githubusercontent.com/52950278/80689927-57411300-8ace-11ea-9dc9-061d910f888b.png)

### List all of your filter lists 
* EasyList Polish+EasyList
* ABP filters

### Tell us about your system configuration 

- Operating system and version: Ubuntu
- Browser and version: Opera 68.0
- Adblock Plus version: 3.8

### Other details 
`www.wp.pl#$#abort-on-property-read SlotRegistrar` 

This filter blocks property _registerSlot_ in _adsFirstRegisterSlot()_ which is the function in _<script>_ below each ad on `www.wp.pl`. It doesn't work on subsites, since their code is different. But seems to block corretly on the main site.

**Comment by wizmak** [comment]
@adblock-filters  Added, thanks!

Could you try `abort-on-property-read rekid` on subdomains? it seems to work well on some, e.g. `sportowefakty.wp.pl` and `wiadomosci.wp.pl` but it makes some disappear, e.g `pilot.wp.pl`

**Comment by adblock-filters** [comment]
Just tried and it actually blocks most ads on sites from WP group. But also blocks video clips so may cause some mess. I'll submit similar snippets for WP group in this issue next week.

**Comment by kulfoon** [comment]
Also: https://github.com/abp-filters/abp-filters-anti-cv/issues/183#issuecomment-622925067

**Comment by adblock-filters** [comment]
site anti-cv code has been updated, new filter:
`www.wp.pl#$#abort-current-inline-script PRELOAD randvar`
