### ISSUE TITLE
quora.com: answer feedback buttons hidden by ABP

### ISSUE THREAD

**Issue by rchan-93** [abp-filters/abp-filters-anti-cv#382]
### List the website(s) where you encounter issues with ABP filters 
quora.com
* quora.com/answer_url. You need to ask a question and get an answer in order to see the prompt.

### Define the problem 
After having asked a question on quora, each answer has a prompt asking whether the answer was helpful or not. When ABP is on I cannot see the "Yes" or "No" buttons in the prompt.

### Screenshot(s) 
With ABP:

<img width="759" alt="adblockeron" src="https://user-images.githubusercontent.com/64870539/81119796-5ea65900-8ee0-11ea-9469-16c0796cc5b0.png">

Without ABP:

<img width="760" alt="adblockeroff" src="https://user-images.githubusercontent.com/64870539/81119808-636b0d00-8ee0-11ea-81eb-4314560286ba.png">

### List all of your filter lists 

- ABP filters
- EasyList
- Allow nonintrusive advertising

I originally opened this issue with "Ad Block" and we narrowed down the filter to the "Anti-Circumvention filters".

### Tell us about your system configuration 

- Operating system and version: Mac OS Catalina 10.15.3
- Browser and version: Chrome Version 81.0.4044.129 (Official Build) (64-bit)
- Adblock Plus version: Version 3.8.4

### Other details 
You will need login and have created a question and received an answer in order to reproduce the issue. It should hopefully be easy to get an answer quickly on a generic question.

**Comment by wizmak** [comment]
@rchan-93 

I can not reproduce this issue, but I'm getting a different-looking feedback widget (see screenshot below) this might be the reason.
![image](https://user-images.githubusercontent.com/38558046/81173160-e56e3b00-8f9f-11ea-97bd-062850d8069a.png)

Could you add a copy of the HTML element of the entire feedback widget you're getting?
