### ISSUE TITLE
topwwnews.com

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#390]
**Website**

* `http://topwwnews.com/`

**Problem**

* Аds by Galaksion + ADS via push notifications

**List all of your filter lists**

- ABP filters
- EasyList
- EasyPrivacy

**Fix**

```
topwwnews.com#$#abort-on-property-read localStorage
```

**Comment by smed79** [comment]
@wizmak ads are back.

**Comment by wizmak** [comment]
@smed79 
> @wizmak ads are back.

Seems to be tackled in EasyList already.
