### ISSUE TITLE
kakprosto.ru

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#40]
Please add a snippet kakprosto.ru#$#abort-on-property-read Ya
https://reports.adblockplus.org/0ba9cff4-768d-4330-a2d4-1a67e151e7cc#tab=screenshot

**Comment by wizmak** [comment]
Fixed as suggested in 294bd83

**Comment by dimisa-RUAdList** [comment]
Does not work any more. Delete please.

**Comment by dimisa-RUAdList** [comment]
Please add a snippet `kakprosto.ru#$#abort-current-inline-script document.createElement renderTo`

https://www.kakprosto.ru/kak-9782-kak-varit-yayca-vkrutuyu
https://i.imgur.com/EQT0y90.jpg

**Comment by dimisa-RUAdList** [comment]
@mile-ne 
Please replace: `kakprosto.ru#$#abort-current-inline-script document.createElement renderTo`
To: `kakprosto.ru#$#abort-current-inline-script document.createElement String.fromCharCode`

**Comment by mile-ne** [comment]
@dimisa-RUAdList suggestion: kakprosto.ru#$#abort-current-inline-script String.fromCharCode
please test

**Comment by dimisa-RUAdList** [comment]
@mile-ne 
It does not work out. The navigation buttons (1, 2, 3, 4) stop working: https://i.imgur.com/uTZHf5T.jpg

**Comment by dimisa-RUAdList** [comment]
Please replace with: `kakprosto.ru#$#abort-current-inline-script document.createElement String.fromCharCode; abort-on-property-write window.yaProxy`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `abort-on-property-write Object.defineProperty`

**Comment by wizmak** [comment]
@dimisa-RUAdList 
> Please add: `abort-on-property-write Object.defineProperty`

This change does not seem to have any impact, but added anyways.
