### ISSUE TITLE
doodstream.com

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#402]
**Website**

* `https://doodstream.com/d/hfqtot6ywvuo`

**Problem**

* popup

**List all of your filter lists**

- ABP filters
- EasyList + FR
- EasyPrivacy

**Fix**

```
doodstream.com,dood.to,dood.watch#$#abort-current-inline-script Math zfgloaded
```

**Comment by wizmak** [comment]
@smed79 
> doodstream.com,dood.to,dood.watch#$#abort-current-inline-script Math zfgloaded

Does not seem to help, but `abort-on-property-read DoodPop` does, can you confirm?

**Comment by smed79** [comment]
I cleaned the browser cache, changed my ip address, added you filter but unfortunately i still get the popup.

**Comment by wizmak** [comment]
How about `abort-on-property-read DoodPop; abort-on-property-write adb; abort-on-property-write cRAds; abort-on-property-write xRds; abort-on-property-write xPoPAdS; `

**Comment by smed79** [comment]
I checked various time, and i get no popup with

`doodstream.com,dood.to,dood.watch#$#abort-on-property-read DoodPop; abort-on-property-write adb; abort-on-property-write cRAds; abort-on-property-write xRds; abort-on-property-write xPoPAdS`

**Comment by dimisa-RUAdList** [comment]
@wizmak 

`https://dood.so/e/g5dpoi3mk60u/`

A few seconds after the start of playback, a warning appears: https://i.imgur.com/JhjIgPs.jpg

**Comment by wizmak** [comment]
> @wizmak
> 
> `https://dood.so/e/g5dpoi3mk60u/`
> 
> A few seconds after the start of playback, a warning appears: https://i.imgur.com/JhjIgPs.jpg

@dimisa-RUAdList 
From an anti-cv perspective, there is nothing we should do about this kind warnings.
(an `NSFW` warning could have been nice)

**Comment by smed79** [comment]
@wizmak Please, alwayse warn about **nsfw** content.

Thank you.

**Comment by wizmak** [comment]
> @wizmak Please, alwayse warn about **nsfw** content.
> 
> Thank you.

@smed79 Sure! Although I asked the same from @dimisa-RUAdList (see the previous version of my comment above) I should have added a warning in the quoted text, I'll do it now.
