### ISSUE TITLE
clicknupload.co

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#405]
**Website**

* `https://clicknupload.co/nz3u9mh98auk`

**Problem**

* popup / ads

**List all of your filter lists**

- ABP filters
- EasyList
- EasyPrivacy

**Fix**

```
clicknupload.co#$#abort-on-property-read btoa
clicknupload.co#$#abort-on-property-read atob
```

**Comment by wizmak** [comment]
> ```
> clicknupload.co#$#abort-on-property-read btoa
> clicknupload.co#$#abort-on-property-read atob
> ```

This fix does not seem to eliminate all pop ads, I added one more filter, but will need to have another look later.

**Comment by mapx-** [comment]
remove btoa, atob, just translate uBO filter:
`clicknupload.co##+js(acis, Object.defineProperty, XMLHttpRequest)`

**Comment by wizmak** [comment]
> remove btoa, atob, just translate uBO filter:
> `clicknupload.co##+js(acis, Object.defineProperty, XMLHttpRequest)`

@mapx- 
Still does not eliminate all pop-ups, needed `abort-current-inline-script String.fromCharCode shift` as well.

@smed79 
Should be good now, let me know how it looks now on your end.

**Comment by mapx-** [comment]
could be, ABP didn't implement aeld I guess

```
clicknupload.*##+js(acis, Math, zfgloaded)
clicknupload.*##+js(aopr, AaDetector)
clicknupload.*##+js(aopr, eddOptions)
clicknupload.*##+js(aeld, , _0x)
clicknupload.co##+js(acis, Object.defineProperty, XMLHttpRequest)
```

**Comment by wizmak** [comment]
> could be, ABP didn't implement aeld (`addEventListener-defuser.js`) I guess
> 

Right, ABP doesn't have `addEventListener-defuser`.

**Comment by smed79** [comment]
@wizmak Seem to be fixed.
