### ISSUE TITLE
katfile.com

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#407]
**Website**

* `https://katfile.com/wu98034nxeil/sr-candlemanthecompletejourneyv20200617.iso.html`

**Problem**

* popup

**List all of your filter lists**

- ABP filters
- EasyList
- EasyPrivacy

**Comment by wizmak** [comment]
`abort-on-property-read/write` and `abort-current-inline-script` seem to always break the download functionality, will block using `$popup` for now and see how it goes.
