### ISSUE TITLE
vidlo.us

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#413]
**Website**

* `https://www.vidlo.us/jaaf564ovomf`

**Problem**

* popup

**List all of your filter lists**

- ABP filters
- EasyList
- EasyPrivacy

**Fix**

```
vidlo.us#$#abort-on-property-read decodeURIComponent
```

**Comment by llacb47** [comment]
`410 Gone`

Link source?

**Comment by wizmak** [comment]
> `410 Gone`

`https://www.vidlo.us/jaaf564ovomf` works for me, will replace the link in the issue details.

**Comment by wizmak** [comment]
b5c33a83eb77da983dda9cbe0d3f662a5cf9db71
(for some reason issues are not referenced properly in commit messages)
