### ISSUE TITLE
ahri-hentai.com

### ISSUE THREAD

**Issue by cjx82630** [abp-filters/abp-filters-anti-cv#415]
### List the website(s) where you encounter issues with ABP filters 
(NSFW)
http://ahri-hentai.com/index.php

### Define the problem 

Popunder ads
### List all of your filter lists 
Easylist China + Easylist

### Tell us about your system configuration 

Operating system and version: win10
Browser and version: chrome83
Adblock Plus version: 3.9

### Other details 
ahri-hentai.com#$#abort-current-inline-script document.querySelectorAll popMagic

**Comment by smed79** [comment]
@cjx82630 Warn with "**NSFW**" when it is about adult content.

**Comment by cjx82630** [comment]
The domain name has changed to ahri8.top please take a look.
