### ISSUE TITLE
ling.online

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#417]
**Website**

* `https://ling.online/en/video/serials/project-blue-book/`

**Problem**

* popup / ads

**List all of your filter lists**

- ABP filters
- EasyList
- EasyPrivacy

**Fix**

```
ling.online#$#abort-on-property-read encodeURI
ling.online#$#abort-current-inline-script Math zfgloaded
```

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak

`ling.online` ~> `ling-online.com`

Please replace:
```
ling.online#$#abort-on-property-read encodeURI
ling.online#$#abort-current-inline-script Math zfgloaded
```
~>

`ling-online.com#$#abort-current-inline-script document.documentElement JSON.parse`
