### ISSUE TITLE
vudeo.net

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#423]
**Website**

* `https://vudeo.net/embed-70thhu0m1qm4.html`

**Problem**

* popup

**List all of your filter lists**

- ABP filters
- EasyList
- EasyPrivacy

**Fix**

```
vudeo.net#$#abort-on-property-read String.fromCharCode
```

**Comment by smed79** [comment]
@wizmak update
```
vudeo.net#$#abort-current-inline-script String.fromCharCode btoa
```

**Comment by SxtBox** [comment]
> **Website**
> 
> * `https://vudeo.net/embed-70thhu0m1qm4.html`
> 
> **Problem**
> 
> * popup
> 
> **List all of your filter lists**
> 
> * ABP filters
> * EasyList
> * EasyPrivacy
> 
> **Fix**
> 
> ```
> vudeo.net#$#abort-on-property-read String.fromCharCode
> ```

does not solve the adblocker problem but php script manipulator dude,
test your link here and see if you jump with popup https://paidcodes.albdroid.al/Players/ADS_Remover/ LOL
