### ISSUE TITLE
series.movie

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#435]
**Website**

* `https://series.movie/` - (`gowatchseries.movie` & `gowatchseries.tv`)

**Problem**

* popup

**List all of your filter lists**

- ABP filters
- EasyList
- EasyPrivacy

**Fix**

```
series.movie,gowatchseries.movie,gowatchseries.tv#$#abort-on-property-read zfgloaded
series.movie,gowatchseries.movie,gowatchseries.tv#$#abort-current-inline-script Object.defineProperty XMLHttpRequest
```

**Comment by wizmak** [comment]
@smed79 
I'm not getting any hits for `abort-on-property-read zfgloaded` and it does not seem to have any effect, but I can see `abort-on-property-read zfgformats` & `abort-on-property-write zfgproxyhttp` hitting, but not sure I if they have any effect on popups.

**Comment by smed79** [comment]
The fix you pushed did the full job. 

closing this for now...
