### ISSUE TITLE
newstm.in

### ISSUE THREAD

**Issue by mediumkreation** [abp-filters/abp-filters-anti-cv#445]
### List the website(s) where you encounter issues with ABP filters 

* `https://newstm.in/`
* `https://3pm.in/`

### Define the problem 
Filter not applying for the whole page..
`newstm.in#?#div:-abp-has(> div > div > span[name="adchoicehtml"])`

1. Couple of sections gets blocked.. but many don't.
2. The ads don't get blocked until page render finishes. 

### List all of your filter lists 
* ABP filters
* IndianList+EasyList

### Tell us about your system configuration 

- Operating system and version:  LINUX(debian)
- Browser and version: Firefox 68.11.0esr (32-bit)
- Adblock Plus version: 3.9.4

**Comment by wizmak** [comment]
@mediumkreation Could you try `##a[href*="/click.htm?"][target="_blank"]` ?
