### ISSUE TITLE
ynetnews.com

### ISSUE THREAD

**Issue by kobizz** [abp-filters/abp-filters-anti-cv#456]
### List the website(s) where you encounter issues with ABP filters 

* `https://www.ynetnews.com/`
* `https://www.ynet.co.il/`

### Define the problem 

Every time you enter the site, there is a popup that requires disabling the Adblock in order to access the site.

### Screenshot(s) 

<img width="1009" alt="Screen Shot 2020-09-09 at 13 23 39" src="https://user-images.githubusercontent.com/5265263/92587012-bd6d4c00-f29f-11ea-9c2e-549a14d601b9.png">

### List all of your filter lists 

- ABP filters
- EasyList
- EasyPrivacy
- Fanboy's Social Blocking List

### Tell us about your system configuration 

- Operating system and version: macOS Catalina 10.15.6
- Browser and version: Google Chrome 85
- Adblock Plus version: 3.9.4

### Suggested filters:

The following filters will solve the problem:

- ynetnews.com##.fc-ab-root
- ynet.co.il##.fc-ab-root

**Comment by wizmak** [comment]
This list does not address messages targeting ad blockers users, for more information please refer to [README](https://github.com/abp-filters/abp-filters-anti-cv/blob/master/README.md). Thank you for filing this issue though.
