### ISSUE TITLE
ukr.net

### ISSUE THREAD

**Issue by ditraUA** [abp-filters/abp-filters-anti-cv#457]
### List the website(s) where you encounter issues with ABP filters 

`www.ukr.net`

### Define the problem 

Site is completely hidden

### Screenshot(s) 

https://i.imgur.com/1S5cxqo.png

### List all of your filter lists 

RuAdList+Easylist
Anti-Circumvention filters (causes the problem)

### Tell us about your system configuration 

- Operating system and version: Windows 10
- Browser and version: Chrome 84
- Adblock Plus version: Adblock 4.20.0

### Other details 

Site is completely hiding after a second. All is ok with other blokers and if a disable Anti-Circumvention filters
I think, Adblock does not correctly support this option: override-property-read

**Comment by ditraUA** [comment]
This problem is important because ukr.net is very popular mail service in Ukraine. And users ok Adblock can't login into mailbox.

**Comment by ditraUA** [comment]
Can't repeat it any more. It seems, site made some fixes on it's side. 

But I shall not close this issue by myself. May be this information will be useful for other cases. 

You can close it after reading.

**Comment by wizmak** [comment]
> Can't repeat it any more. It seems, site made some fixes on it's side.
> 
> But I shall not close this issue by myself. May be this information will be useful for other cases.
> 
> You can close it after reading.

@ditraUA I can not reproduce the issue as well, and for the record, the filter was tested before pushing, and the site was working without anz issues. Thanks for filing this issue!

**Comment by ditraUA** [comment]
> @ditraUA I can not reproduce the issue as well, and for the record, the filter was tested before pushing, and the site was working without any issues. Thanks for filing this issue!

Just one question: Was this filter tested in Adblock, not Adblock plus? It blocked whole site only in Adblock. May be that's why you didn't notice a problem?

**Comment by wizmak** [comment]
@ditraUA 
> Just one question: Was this filter tested in Adblock, not Adblock plus? It blocked whole site only in Adblock. May be that's why you didn't notice a problem?

It was tested in Adblock Plus only, but it would be very strange if it worked any differently in AdBlock.

**Comment by ditraUA** [comment]
> @ditraUA
> 
> It was tested in Adblock Plus only, but it would be very strange if it worked any differently in AdBlock.

The problem was in version 4.20, it has no support of `override-property-read` rule. I've downloaded versions 4.20 and 4.21 from http://code.getadblock.com/releases/, unpacked sources and found file, that contains "override-property-read" only in 4.21 folder. 

And I tried to disable Anti-Circumvention list and apply only this rule:
`www.ukr.net#$#override-property-read Math.random trueFunc; hide-if-shadow-contains /./`

Issue was reproduced only in Adblock (not Plus). But, when I removed this part: `override-property-read Math.random trueFunc;` Adblock Plus began to work same as Adblock: totally cleaned the page. Unfortunately, I don't understand, what exactly this rule do, so can't give you more details. I asked more experienced guy to help me, but he couldn't reproduce the issue - site made fixes on it's side.

Sorry for alarming, but I have to support tens of employees notebooks remotely (due to quarantine). And it is always a huge problem for me when important sites begin to work incorrectly due to Ad Blockers. Apparently, this case is a good reason for colleagues to replace Adblock with Adblock Plus.

**Comment by wizmak** [comment]
@ditraUA
> The problem was in version 4.20, it has no support of `override-property-read` rule. I've downloaded versions 4.20 and 4.21 from http://code.getadblock.com/releases/, unpacked sources and found file, that contains "override-property-read" only in 4.21 folder.
> 

I doubt this was the case, if the snippet doesn't exist in the extension's code, the corresponding snippet filter should have no effect.

> And I tried to disable Anti-Circumvention list and apply only this rule:
> `www.ukr.net#$#override-property-read Math.random trueFunc; hide-if-shadow-contains /./`
> 
> Issue was reproduced only in Adblock (not Plus). But, when I removed this part: `override-property-read Math.random trueFunc;` Adblock Plus began to work same as Adblock: totally cleaned the page. Unfortunately, I don't understand, what exactly this rule do, so can't give you more details. I asked more experienced guy to help me, but he couldn't reproduce the issue - site made fixes on it's side.
> 
Interesting... Unfortunately I also won't be able to figure out what happened, as long as I can/could not reproduce the issue.

> Sorry for alarming, but I have to support tens of employees notebooks remotely (due to quarantine). And it is always a huge problem for me when important sites begin to work incorrectly due to Ad Blockers. Apparently, this case is a good reason for colleagues to replace Adblock with Adblock Plus.

No worries! Always feel free to reach out in case you have any questions or issues. Cheers!

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak
Up!

**Comment by wizmak** [comment]
@dimisa-RUAdList 
I went ahead with the removal of the entire rule as it's no longer useful/needed.

**Comment by dportvine** [comment]
@wizmak
Please dell. This rule is outdated.
```adb
www.ukr.net#$#override-property-read Math.random trueFunc; hide-if-shadow-contains /./
```
