### ISSUE TITLE
budport.com.ua

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#460]
Please add a snippet: `budport.com.ua#$#abort-on-property-read open`

Popup when clicking on the side of the background.

Example: http://budport.com.ua/

See also: https://github.com/abp-filters/abp-filters-anti-cv/issues/339

**Comment by mapx-** [comment]
or
`budport.com.ua#$#abort-current-inline-script $ open`

**Comment by arsykan** [comment]
thanks @dimisa-RUAdList ,for me I don't see that `budport.com.ua#$#abort-on-property-read open` remove the background, if you could recheck, I can see `budport.com.ua#$#abort-current-inline-script $ open`  thanks to @mapx-  is doing the job if you could confirm.

**Comment by dimisa-RUAdList** [comment]
Yes, it's better to add: `budport.com.ua#$#abort-current-inline-script $ open`

This not only removes the clickability of the background, but the background itself.

**Comment by arsykan** [comment]
Great! thanks a ton for your contribution @dimisa-RUAdList  @mapx-

**Comment by dimisa-RUAdList** [comment]
@arsykan 
@wizmak 
Please replace with: `abort-current-inline-script $ append`
