### ISSUE TITLE
Non-Ads Are Blocked When Both Adblock and AdblockPlus are Enabled

### ISSUE THREAD

**Issue by yuchaozh** [abp-filters/abp-filters-anti-cv#467]
### List the website(s) where you encounter issues with ABP filters 
`https://www.bing.com`

### Define the problem 
when both adBlock and adBlockPlus are enabled. Our results in Bing.com homepage and the work tab are blocked.
![image](https://user-images.githubusercontent.com/3889738/94718362-83bfbc00-0306-11eb-96f8-ad6d686b1c6e.png)
![image](https://user-images.githubusercontent.com/3889738/94718422-93d79b80-0306-11eb-8687-1ba242841241.png)

But if we only keep one of them enabled. Our content is not removed.
enable adblock but disable adblockPlus
![image](https://user-images.githubusercontent.com/3889738/94718298-6a1e7480-0306-11eb-977b-1eb84b8dc56a.png)
enable adblockPlus but disable adblock
![image](https://user-images.githubusercontent.com/3889738/94718598-cd100b80-0306-11eb-8a3e-d7f6856f5673.png)

adding div element:
in bing.com `all` tab:
![image](https://user-images.githubusercontent.com/3889738/94721945-6ccf9880-030b-11eb-8937-92f70aa17532.png)
in bing.com `work` tab:
![image](https://user-images.githubusercontent.com/3889738/94722243-dfd90f00-030b-11eb-8366-01ae22790220.png)

Do you know what is causing this issue? Do you know how to resolve it?
Thanks!

### Tell us about your system configuration 

- Operating system and version: Windows
- Browser and version: Chrome, Edge
- Adblock Plus version: 3.9.5; Adblock verions: 4.22.0

**Comment by wizmak** [comment]
@yuchaozh 
I'm not sure why someone would need to use Adblock Plus and AdBlock simultaneously while they essentially do the same thing. Still, this is an interesting issue, we'll try figure out what's happening, and if it can actually be fixed.

**Comment by yuchaozh** [comment]
Thanks @wizmak, please keep us up to date

**Comment by wizmak** [comment]
@yuchaozh FYI this issue should be fixed as of **ABP 3.10**, I will let you again once the release is out.

**Comment by yuchaozh** [comment]
I was ABP 3.10 was released. And I test it on my side, the issue was resolved. Thanks! Appreciate for your help!
