### ISSUE TITLE
vg.no

### ISSUE THREAD

**Issue by SmartUser32** [abp-filters/abp-filters-anti-cv#47]
### List the website(s) where you encounter issues with ABP filters 

vg.no

### Define the problem 

InstartLogic ads everywhere.

### Tell us about your system configuration 

- Operating system and version: 
- Browser and version: Chrome
- Adblock Plus version: 3.4.2

**Comment by wizmak** [comment]
There are an ongoing efforts to tackle circumvention on vg.no and similar websites, but unfortunately there is no long-lasting solution just yet.
