### ISSUE TITLE
finanzen.net

### ISSUE THREAD

**Issue by cadeyrn** [abp-filters/abp-filters-anti-cv#48]
### List the website(s) where you encounter issues with ABP filters 

* https://www.finanzen.net/

### Define the problem 

1) alert dialog with the following error message:

MMSuggest Error:
ReferenceError: $ is not defined

2) a lot of error messages in the web console:

ReferenceError: $ is not defined[Weitere Informationen]
www.finanzen.net:242:6
ReferenceError: $ is not defined[Weitere Informationen]
www.finanzen.net:566:3
ReferenceError: objCookie is not defined[Weitere Informationen]
www.finanzen.net:591:2
ReferenceError: objCookie is not defined[Weitere Informationen]
www.finanzen.net:111:2460
ReferenceError: objCookie is not defined[Weitere Informationen]
www.finanzen.net:1004:7
ReferenceError: objCookie is not defined[Weitere Informationen]
www.finanzen.net:1022:6
ReferenceError: $ is not defined[Weitere Informationen]
www.finanzen.net:1069:491
ReferenceError: $ is not defined[Weitere Informationen]
www.finanzen.net:1330:3
ReferenceError: objCookie is not defined[Weitere Informationen]
www.finanzen.net:1355:6
ReferenceError: objCookie is not defined[Weitere Informationen]
www.finanzen.net:1367:6
ReferenceError: $ is not defined[Weitere Informationen]
www.finanzen.net:1404:6
ReferenceError: $ is not defined[Weitere Informationen]
www.finanzen.net:1413:3
ReferenceError: jQuery is not defined[Weitere Informationen]
fin-async.min.js:1:2
ReferenceError: jQuery is not defined[Weitere Informationen]
jquery-ui.min.js:6:52
TypeError: f is undefined[Weitere Informationen]
push-mdsng.min.js:177:1146

No alert message and no error messages in the console with the filter list "ABP filters" disabled.

### List all of your filter lists 

* ABP filters

### Tell us about your system configuration 

- Operating system and version: macOS Mojave
- Browser and version: Firefox Nightly 66.0a1 (2019-01-25)
- Adblock Plus version: 3.4.3

**Comment by wizmak** [comment]
This should be resolved now, please wait few minutes, then update `ABP filters`.
