### ISSUE TITLE
streaming-vostfr.net

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#486]
**Website**

* `https://streaming-vostfr.net/`

**Problem**

* popup + ads

**List all of your filter lists**

- ABP filters
- EasyList + Liste FR
- EasyPrivacy

**Fix**

```
streaming-vostfr.net#$#abort-current-inline-script String.fromCharCode btoa
```

**Comment by arsykan** [comment]
Hey @smed79 , could you have another look, I still have popups, thanks!

**Comment by smed79** [comment]
No, popups here.
