### ISSUE TITLE
clickscloud.net script

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#50]
Please add a snippet: `aftershock.news,alau.kz,amurmedia.ru,argumenti.ru,eaomedia.ru,fastpic.ru,irkutskmedia.ru,it-tehnik.ru,krasnodarmedia.su,krasnoyarskmedia.ru,magadanmedia.ru,moikolodets.ru,newsland.com,popcornnews.ru,primamedia.ru,radikal.ru,sakhalinmedia.ru,sevastopolmedia.ru,sovsport.ru,sport-express.ru,svpressa.ru,theplace.ru,tsargrad.tv,ulanmedia.ru,ussurmedia.ru,yakutiamedia.ru#$#abort-on-property-read ccScriptSupport`

Example: https://www.sport-express.ru/football/rfpl/reviews/spartak-2022-pochemu-fedun-ne-prodast-klub-1505821/
https://i.imgur.com/pIUqSh4.jpg

**Comment by dimisa-RUAdList** [comment]
Please add a snippet:  `car.ru#$#abort-on-property-read ccScriptSupport`

**Comment by dimisa-RUAdList** [comment]
Already not working. Please change to: `aftershock.news,alau.kz,amurmedia.ru,argumenti.ru,car.ru,eaomedia.ru,fastpic.ru,irkutskmedia.ru,it-tehnik.ru,krasnodarmedia.su,krasnoyarskmedia.ru,magadanmedia.ru,moikolodets.ru,newsland.com,popcornnews.ru,primamedia.ru,radikal.ru,sakhalinmedia.ru,sevastopolmedia.ru,sovsport.ru,sport-express.ru,svpressa.ru,theplace.ru,tsargrad.tv,ulanmedia.ru,ussurmedia.ru,yakutiamedia.ru#$#abort-on-property-write ccScriptSupport`

**Comment by wizmak** [comment]
> Already not working. Please change to: `aftershock.news,alau.kz,amurmedia.ru,argumenti.ru,car.ru,eaomedia.ru,fastpic.ru,irkutskmedia.ru,it-tehnik.ru,krasnodarmedia.su,krasnoyarskmedia.ru,magadanmedia.ru,moikolodets.ru,newsland.com,popcornnews.ru,primamedia.ru,radikal.ru,sakhalinmedia.ru,sevastopolmedia.ru,sovsport.ru,sport-express.ru,svpressa.ru,theplace.ru,tsargrad.tv,ulanmedia.ru,ussurmedia.ru,yakutiamedia.ru#$#abort-on-property-write ccScriptSupport`

This filter does not seem to work, does it work for you?

**Comment by dimisa-RUAdList** [comment]
These rules cannot be used simultaneously. Try only the new snippet.

**Comment by wizmak** [comment]
> These rules cannot be used simultaneously. Try only the new snippet.

I see, done.

**Comment by dimisa-RUAdList** [comment]
Already not working. Please change to: `aftershock.news,alau.kz,amurmedia.ru,argumenti.ru,car.ru,eaomedia.ru,fastpic.ru,irkutskmedia.ru,it-tehnik.ru,krasnodarmedia.su,krasnoyarskmedia.ru,magadanmedia.ru,moikolodets.ru,newsland.com,popcornnews.ru,primamedia.ru,radikal.ru,sakhalinmedia.ru,sevastopolmedia.ru,sovsport.ru,sport-express.ru,svpressa.ru,theplace.ru,tsargrad.tv,ulanmedia.ru,ussurmedia.ru,yakutiamedia.ru#$#abort-current-inline-script Math.floor ccScriptSupport`

**Comment by dimisa-RUAdList** [comment]
No longer works, you can delete.

**Comment by dimisa-RUAdList** [comment]
Please add a snippet: 7days.ru#$#abort-current-inline-script document.createElement

https://7days.ru/news/yuliya-nachalova-prokommentirovala-novost-o-popadanii-v-reanimatsiyu.htm?from=recommendation
https://i.imgur.com/3cDeAAD.jpg

**Comment by dimisa-RUAdList** [comment]
Please replace for 7days.ru >

Add:
```
7days.ru#$#abort-current-inline-script document.createElement div
7days.ru#$#abort-current-inline-script document.createElement Math_random
```
Del:
`7days.ru#$#abort-current-inline-script document.createElement`

**Comment by dimisa-RUAdList** [comment]
I was a little wrong. Please replace >
Add: `7days.ru#$#abort-current-inline-script Math_random`
Del: `7days.ru#$#abort-current-inline-script document.createElement Math_random`

**Comment by dimisa-RUAdList** [comment]
Delete please:
`7days.ru#$#abort-current-inline-script document.createElement div; abort-current-inline-script Math_random`

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Please add a snippet: `tsargrad.tv#$#abort-on-property-read Math_random`

**Comment by dimisa-RUAdList** [comment]
Please del:
```
tsargrad.tv#$#abort-on-property-read Math_random
gorodche.ru,9111.ru,fastpic.ru#$#abort-on-property-read Ma_random
```

Please add:
`7ogorod.ru,agrognom.ru,alau.kz,argumenti.ru,argumentiru.com,etotprazdnik.ru,fermilon.ru,globuss24.ru,gorodche.ru,mashintop.ru,maxpark.com,newsland.com,ogodom.ru,pasmi.ru,shtrafsud.ru,svpressa.ru#$#abort-on-property-read Math_random`

**Comment by dimisa-RUAdList** [comment]
Please add: `7days.ru#$#abort-on-property-read Math_random`

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Please add: `teleprogramma.pro#$#abort-on-property-read Math_random`

Example: https://teleprogramma.pro/stars/star-hist/1166173-opros-jaleete-li-vy-doch-alsu-kak-u3424/

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please add: `politros.com#$#abort-on-property-read Math_random`

Example: https://politros.com/152242-v-mid-rf-otvetili-na-zayavlenie-amerkianskogo-posla-po-delu-pola-uilana

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: 
`7days.ru,7ogorod.ru,agrognom.ru,alau.kz,argumenti.ru,argumentiru.com,etotprazdnik.ru,fermilon.ru,globuss24.ru,gorodche.ru,kp.ru,mashintop.ru,maxpark.com,newsland.com,ogodom.ru,pasmi.ru,news.ru,politros.com,shtrafsud.ru,svpressa.ru,teleprogramma.pro#$#abort-on-property-read M_rnd`

**Comment by dimisa-RUAdList** [comment]
Please replace with:
`7days.ru,7ogorod.ru,agrognom.ru,alau.kz,argumenti.ru,argumentiru.com,etotprazdnik.ru,fermilon.ru,fishki.net,globuss24.ru,gorodche.ru,kp.ru,mashintop.ru,maxpark.com,news.ru,newsland.com,ogodom.ru,pasmi.ru,politros.com,shtrafsud.ru,svpressa.ru,teleprogramma.pro#$#abort-on-property-write ccJugger`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak

Please del: `7days.ru,7ogorod.ru,agrognom.ru,alau.kz,argumenti.ru,argumentiru.com,etotprazdnik.ru,fermilon.ru,fishki.net,globuss24.ru,gorodche.ru,kp.ru,mashintop.ru,maxpark.com,news.ru,newsland.com,ogodom.ru,pasmi.ru,politros.com,shtrafsud.ru,svpressa.ru,teleprogramma.pro#$#abort-on-property-write ccJugger`
