### ISSUE TITLE
soundpark domains

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#500]
Please add: `sound-park.rocks,sound-park.world,soundpark.rocks#$#abort-current-inline-script $ open`

Redirect by clicking on the download button

Example: `https://sound-park.rocks/eng/va-reaching-altitude-special-selections-part-5-2020/`

**Comment by wizmak** [comment]
@dimisa-RUAdList 
> sound-park.rocks,sound-park.world,soundpark.rocks#$#abort-current-inline-script $ open

This doesn't seem to work every time.

**Comment by dimisa-RUAdList** [comment]
@wizmak 
This doesn't repeat itself for me when using a ruadlist. In addition to blocking the embedded script, there must be blocked adservers from the "pro" domain zone. More details: https://github.com/easylist/ruadlist/commit/f3fc549a93ff1d5a3418eb883309b6cee4540b13

**Comment by wizmak** [comment]
@dimisa-RUAdList 
> This doesn't repeat itself for me when using a ruadlist. In addition to blocking the embedded script, there must be blocked adservers from the "pro" domain zone. More details: [easylist/ruadlist@f3fc549](https://github.com/easylist/ruadlist/commit/f3fc549a93ff1d5a3418eb883309b6cee4540b13)

I see, I visited the English version of these websites, and so I had the ruadlist disabled, thanks for clarification!
