### ISSUE TITLE
gnula.nu

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#504]
**Website**

* `https://gnula.nu/` 

**Problem**

* popups / popunder

**List all of your filter lists**

- ABP filters
- EasyList
- EasyPrivacy

**Fix**

```
gnula.nu#$#abort-on-property-read String.fromCharCode
```

**Comment by mapx-** [comment]
bad filter

add

`gnula.nu#$#abort-current-inline-script String.fromCharCode break`

**Comment by smed79** [comment]
@wizmak replace **all** `String.fromCharCode btoa` with `String.fromCharCode /btoa|break/`
