### ISSUE TITLE
WP Group

### ISSUE THREAD

**Issue by keczuppp** [abp-filters/abp-filters-anti-cv#505]
### List the website(s) where you encounter issues with ABP filters 

- many websites from WP Group, see related issues: https://github.com/abp-filters/abp-filters-anti-cv/issues/183 https://github.com/abp-filters/abp-filters-anti-cv/issues/380 https://github.com/abp-filters/abp-filters-anti-cv/issues/381

### Define the problem 

- circumvented ads or ads placeholders on many websites from WP group

### Screenshot(s) 

<details not-open>
<summary>screenshoot circumvention ads on example www.wp.pl site</summary>

![ads](https://user-images.githubusercontent.com/74409207/101184882-82d24000-3651-11eb-961d-25c1cf24d54b.jpg)
</details>

<details not-open>
<summary>screenshoot grey ads placeholderss on example tech.wp.pl site</summary>

![placeholders](https://user-images.githubusercontent.com/74409207/101185045-b01eee00-3651-11eb-9301-d5719afa6b22.jpg)

</details>

### List all of your filter lists 

- ABP filters
- EasyList Polish+EasyList
- EasyPrivacy
- Official Polish Filters for AdBlock, uBlock Origin & AdGuard
- Polish Anti Adblock Filters
- Polish Privacy Filters

### Tell us about your system configuration 

- Operating system and version: Win 7 SP1 64bit
- Browser and version:  Firefox 83 / Opera 72
- Adblock Plus version: 3.10

### Other details 

@easylistpolish @adblock-filters

**Comment by wizmak** [comment]
@keczuppp 

As you already know these are CV ads of which some are already blocked at the moment. @adblock-filters is submitting fixes whenever possible, but unfortunately there is not a permanent long-lasting solution that blocks 100% of these ads. 

I'll close this issue if you don't mind, and thank you for reporting!
