### ISSUE TITLE
rg-mechanics.org, xatab-repack.net

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#51]
Please add a snippet: `rg-mechanics.org,xatab-repack.net#$#abort-on-property-read ads`
Substitution of download links.
Example: https://xatab-repack.net/games/torrent_igry/3d/dakar_18_2018_pc_124_repack_ot_xatab/3-1-0-685
https://i.imgur.com/NPGDLBV.jpg

**Comment by dimisa-RUAdList** [comment]
Please replace with:
```
rg-mechanics.org#$#abort-on-property-read adska
xatab-repack.net#$#abort-on-property-read adss
```

**Comment by dimisa-RUAdList** [comment]
Please del all, domains do not work.

**Comment by wizmak** [comment]
@dimisa-RUAdList 
> Please del all, domains do not work.

They seem to be working still.

**Comment by dimisa-RUAdList** [comment]
Just a few seconds. Then a redirect to:  otmechanikov.net, otxataba.net
