### ISSUE TITLE
toonget.net

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#512]
**Website**
```
https://toonova.net/
https://toonget.net/
```

**Problem**

* ads

**List all of your filter lists**

- ABP filters
- EasyList
- EasyPrivacy

**Fix**

```
toonget.net,toonova.net#$#abort-on-property-read bbHideDiv
```

**Comment by wizmak** [comment]
@smed79 Although I see `bbHideDiv` but I'm unable to reproduce any ads, any hints?

**Comment by smed79** [comment]
Banner image does not load for me but the clickable link still there (Firefox 83.0 / ABP 3.10) :
- https://i.ibb.co/9ym86bs/toonget-net.png
- https://i.ibb.co/2g1xT6w/toonova-net.png

```
https://toonget.net/assets/CCXTpKhFVigxNdlGxfUUkbAqy5a4y_fJEL4p6ZzBXfKVMt8JufjmEvOdyDo
https://toonova.net/assets/CCXTpKhFZ6gPVMplMXvwbr_MtscLWneg4ZYzq6BwoyJ5oBqykk
```
