### ISSUE TITLE
Quora feed answer dismissed after expanding

### ISSUE THREAD

**Issue by gleeq** [abp-filters/abp-filters-anti-cv#53]
### List the website(s) where you encounter issues with ABP filters 

* www.quora.com 

### Define the problem 

When expand an answer in quora main feed, the answer itself just disappears.

### Screenshot(s) 

https://cl.ly/d42159e10e59

### List all of your filter lists 

Cash Back Shopping
ABP filters 
EasyList (probably not this, as i disabled this, and issue still exists)

### Tell us about your system configuration 

- Operating system and version: MAC os 10.14.2
- Browser and version: Chrome Version 72.0.3626.96
- Adblock Plus version: Version number 3.4.3

**Comment by gleeq** [comment]
Hi @wizmak I am still seeing this happens in some parts of my feed: https://cl.ly/1f19df6e4948 I reinstall the ad blocker plus but still seeing this (assuming that gives me an updated version of ad block?).

**Comment by wizmak** [comment]
Hi @gleeq 
Normally you wouldn't need to reinstall ABP, you'd just need to manually update your `ABP filters` list if you want quickly to get latest updates, otherwise this list is updated automatically on hourly basis.
Anyways, looks like this is no longer an issue, do let me know if this still happens with you.

**Comment by gleeq** [comment]
Hello @wizmak! Thanks for the help last time. It seems like this started to happen again: https://cl.ly/570293365af2 the feed item just disappeared after expanding. I tried to update the filter list this time tho.

**Comment by wizmak** [comment]
> Hello @wizmak! Thanks for the help last time. It seems like this started to happen again: https://cl.ly/570293365af2 the feed item just disappeared after expanding. I tried to update the filter list this time tho.

Hey @gleeq you're welcome!
I can't reproduce the issue, but anyways I made the filter more specific, please check again and let me know if the issue persists.

> And I am not familiar with this reporting. should i just open a separate issue?

Please file a separate issue, thanks!
