### ISSUE TITLE
musify.club

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#538]
Add please: `musify.club#$#abort-on-property-read get_ya_browser`

Reason: advertising browser while downloading mp3

Example: `https://w1.musify.club/` - [screen](https://i.imgur.com/hDvZA4W.jpg)

**Comment by wizmak** [comment]
Could not reproduce, but added the suggested filter since you could.

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Please replace with: `musify.club#$#abort-current-inline-script $ get_ya_browser`

**Comment by dimisa-RUAdList** [comment]
@wizmak
Please replace with: `musify.club#$#abort-on-property-read get_ya_browser`
