### ISSUE TITLE
helloacm.com

### ISSUE THREAD

**Issue by ryanwilliams83** [abp-filters/abp-filters-anti-cv#547]
### List the website(s) where you encounter issues with ABP filters 

* `https://helloacm.com/simple-xargs-batch-implementation-for-windows/`

### Define the problem 
Dialog covering content

### Screenshot(s) 
![image](https://user-images.githubusercontent.com/3871256/106224240-10d43c80-6237-11eb-9a87-418ec398961e.png)

### List all of your filter lists 
ABP filters
EasyList

### Tell us about your system configuration 

- Operating system and version: Windows 10 Build 18363
- Browser and version: Chrome Version 80.0.3987.122 (Official Build) (64-bit)
- Adblock Plus version: 3.10.2

**Comment by wizmak** [comment]
Hey @ryanwilliams83!

The anti-cv list does not address anti-ad block messages/walls, for more details please refer to [README](https://github.com/abp-filters/abp-filters-anti-cv/blob/master/README.md).

Thanks for reporting!
