### ISSUE TITLE
russian.txt rules blocks site (CV-747)

### ISSUE THREAD

**Issue by Aminoser** [abp-filters/abp-filters-anti-cv#553]
### List the website(s) where you encounter issues with ABP filters 

* https://horoscopes.rambler.ru/ (in new version (Switching to the new version: https://horoscopes.rambler.ru/go-to-ts/ ))

### Define the problem 

After release CV-747 the new version of the site is almost completely hidden.

### Screenshot(s) 

<img width="327" alt="rule1" src="https://user-images.githubusercontent.com/3600064/107033142-edc10400-67c5-11eb-8a0e-02c6f9cdadc4.png">
<img width="329" alt="rule2" src="https://user-images.githubusercontent.com/3600064/107033156-f0235e00-67c5-11eb-9351-56ad1ea45f19.png">
<img width="1500" alt="site1" src="https://user-images.githubusercontent.com/3600064/107033161-f1ed2180-67c5-11eb-8513-e01ef1536e7e.png">
<img width="1496" alt="site2" src="https://user-images.githubusercontent.com/3600064/107033179-f6b1d580-67c5-11eb-8d34-8d15a2c3b213.png">
<img width="1792" alt="site3" src="https://user-images.githubusercontent.com/3600064/107035740-a8063a80-67c9-11eb-9fc0-38bab3198108.png">

### List all of your filter lists 
* ABP filters
* RuAdList+EasyList

### Tell us about your system configuration 

- Operating system and version: macOS Big Sur 11.2
- Browser and version: Mozilla Firefox 85.0, Google Chrome 88.0.4324.150
- Adblock Plus version: 3.10.2

**Comment by Aminoser** [comment]
@arsykan please fix your code as soon as possible

**Comment by arsykan** [comment]
Hey @Aminoser thanks for reporting! filter removed for now https://github.com/abp-filters/abp-filters-anti-cv/commit/82106f684cda2ba8c904c7d167d44f5e82dab689

btw, I could not reproduce on chrome using window 10 except after using emulation mode in chrome, is this your case here?

**Comment by Aminoser** [comment]
Thanks. At the moment, the site is displayed correctly.

Yes, that was my case.
