### ISSUE TITLE
tagaev.com

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#555]
Please add: `tagaev.com#$#abort-on-property-read PUM`

https://tagaev.com/cirkuljarnye-stanki/

https://i.imgur.com/u8vyhnx.jpg

**Comment by arsykan** [comment]
Hey @dimisa-RUAdList did you mean
`tagaev.com#$#abort-on-property-read PUM` ?

**Comment by dimisa-RUAdList** [comment]
Oh sure.

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak
Please replace: `tagaev.com#$#abort-on-property-read PUM` ~> `tagaev.com#$#abort-on-property-read PUM.getPopup`
