### ISSUE TITLE
dailyuploads.net

### ISSUE THREAD

**Issue by TheShadowRunner** [abp-filters/abp-filters-anti-cv#559]
With "Anti-Circumvention filters" filter active, the recaptacha "i'm not a robot" never obtains the ckeckmark, ever.
with**out** this filter, site works ok.
Sample: https://dailyuploads.net/fpxttsb9e3n5

I try adding to "Manually edit your filters":
@@||dailyuploads.net#$#abort-current-inline-script
@@||dailyuploads.net#$#abort-on-property-read
but it doesn't help..

Please fix if possible, thanks.

**Comment by arsykan** [comment]
Thanks @TheShadowRunner for reporting, fixed by https://github.com/abp-filters/abp-filters-anti-cv/commit/87a889e6e89a2495a558fadeea3c42768e99749f
