### ISSUE TITLE
Failed to load: gismeteo.ua

### ISSUE THREAD

**Issue by ditraUA** [abp-filters/abp-filters-anti-cv#564]
### List the website(s) where you encounter issues with ABP filters 

https://www.gismeteo.ua/

The site is not loading correctly when ABP Filters in turned on

### Screenshot(s) 

https://monosnap.com/file/xp3J6kDvn4dQVjJVsJ42QSLCDcT5d6

correct loading: 

https://monosnap.com/file/fOyZZnq84lys54TNAY2IbbGCed5Cop

### List all of your filter lists 

ABP Filters
Easylist + Ruadlist

### Tell us about your system configuration 

- Operating system and version: Mac OS Catalina
- Browser and version: Chrome 88
- Adblock Plus version: Adblock Plus 3.10.2

### Other details 

Issue can be reproduced only if ABP Filters list is on. 
May be issue is caused by this commit: https://github.com/abp-filters/abp-filters-anti-cv/commit/21cd495c4768c0495fc9dc0c94c22f9580a137be#diff-33f308abca070c70e1412accec2aa34fae921fd2646df7bdecb6cb0980f82bea

**Comment by arsykan** [comment]
Hey @ditraUA thanks for reporting! domain removed.

**Comment by ditraUA** [comment]
Thank you!

**Comment by ditraUA** [comment]
@arsykan  Unfortunatelly, issue is still there. May be, problem is in another rule.

https://api.monosnap.com/file/download?id=dE8xFv8wC6EiWWNAsH5Qa9XM4A5Y7G

**Comment by ditraUA** [comment]
@smed79 I think issue is here: https://github.com/abp-filters/abp-filters-anti-cv/commit/16bf94775e7e379d51d6cee0e62c559a5474a436

**Comment by arsykan** [comment]
@ditraUA could you update your ABP filters list, then give it another try?

**Comment by ditraUA** [comment]
Sorry for spamming. I can't reproduce issue at any page refresh. It is happening time to time (before previous fix, issue was stable). But it is still there.

**Comment by ditraUA** [comment]
@arsykan   I can't reproduce it any more. Looks like it was some cache in by Adblock or something like that.

I asked colleges to check and they can't reproduce it too. 

I think, issue is fixed. My Bad.

**Comment by arsykan** [comment]
No worries at all, always happy to help!
