### ISSUE TITLE
Failed to load: censor.net

### ISSUE THREAD

**Issue by ditraUA** [abp-filters/abp-filters-anti-cv#565]
### List the website(s) where you encounter issues with ABP filters 

https://censor.net/

### Define the problem 

The site is not loading correctly when ABP Filters in turned on

### Screenshot(s) 

https://i.imgur.com/B0mtGGM.png

### List all of your filter lists 

ABP Filters
Easylist + Ruadlist

### Tell us about your system configuration 

- Operating system and version: Mac OS Catalina, Windows 10
- Browser and version: Chrome 88
- Adblock Plus version: Adblock Plus 3.10.2

### Other details 

To reproduce this issue, you should purge the browser cache or use incognito mode. 
If you'll disable ABP Filters (or Adblock itself), page will load correctly. And after that page loads well even when ABP Filters list is enabled.

@arsykan  I think, this is the same issue that we had with gismeteo.ua: https://github.com/abp-filters/abp-filters-anti-cv/issues/564

**Comment by ditraUA** [comment]
I've checked other sites from the rule in this commit: https://github.com/abp-filters/abp-filters-anti-cv/commit/1d3c31d0431da804375d9b80e3ecc75278ca5191

And a see the same problem in https://toneto.net/. I've got some reports from my colleagues on other domains (earlier i asked them to send me any issues with ad blockers if they have some), but can't reproduce it.

**Comment by arsykan** [comment]
@ditraUA  fixed for now by https://github.com/abp-filters/abp-filters-anti-cv/commit/89258178f540e7444ad4ed28370cc38194819555

the rule is bypassed anyway

**Comment by ditraUA** [comment]
Yes, I see ads on other sites from list. So, it looks like the best option for now.
