### ISSUE TITLE
delfi.lt

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#57]
Hi,

**List the website(s) where you encounter issues with ABP filters**

```
https://www.delfi.lt/
```

**Define the problem**

unblocked ads / circumvention 

**Screenshot**

https://vgy.me/Nyr6sB.png

**List all of your filter lists**

ABP filters
EasyList
EasyList **Lithuania**
EasyPrivacy
Adblock Warning Removal List

**Tell us about your system configuration**

- Browser and version: Firefox 65 & Chromium 72
- Adblock Plus version: 3.4.3

**Other details**

- snippet `settimeout defuser` required / [ticket/7270](https://issues.adblockplus.org/ticket/7270)
- ubo fix [48d07d2](https://git.io/fhdr8)

**Comment by wizmak** [comment]
Hi @smed79 
Thanks for reporting, we'll push a fix once available.

**Comment by mapx-** [comment]
classic, ugly "fix"
```
@@||delfi.lt^$elemhide
@@*$script,domain=delfi.lt,third-party
```

**Comment by mapx-** [comment]
@wizmak @all_the_others you should liberalize your snippets, let them free for easylist authors.
More - add support in ABP the uBo format for script injecting filters => this way easylist authors could use this kind of advanced filters for the benefit of all users (and all adblockers)

**Comment by mapx-** [comment]
well, it's something different in ABP for `abort-on-property-read.js` snippet.

In uBo =>  `delfi.lt##+js(abort-on-property-read.js, _dlf.ab)` is working fine (disabling the `setTimeout` filter)

In ABP => `delfi.lt#$#abort-on-property-read _dlf.ab` => does not work (last ABP dev build, firefox / chrome)

more - in firefox I get a message from the browser => "a script in abp ..is slowing .."
@mjethani @hfiguiere

**Comment by hfiguiere** [comment]
It will not work with `_dlf.ab`. There is a patch pending to support that.

**Comment by hfiguiere** [comment]
See https://issues.adblockplus.org/ticket/7236

**Comment by mapx-** [comment]
@wizmak  I found a working filter in ABP
`delfi.lt#$#abort-on-property-read btoa`

**Comment by mapx-** [comment]
for FF unresponsive (after adding the snippet) see => https://issues.adblockplus.org/ticket/6067

**Comment by gymka** [comment]
> 
> 
> @wizmak I found a working filter in ABP
> `delfi.lt#$#abort-on-property-read btoa`

it solves problems.

**Comment by mapx-** [comment]
( gymka is the maintainer of `LTU: EasyList Lithuania` )

**Comment by wizmak** [comment]
@mapx- @gymka 
Suggested filter works, added.

**Comment by mapx-** [comment]
I got that behaviour testing `delfi.lt#$#abort-on-property-read _dlf.ab`
However, it's an old issue, I linked above the issue

**Comment by gymka** [comment]
works not as expected:
1. open browser, go to delfi.lt(easylistlithuania enabled and up to date). it shows ads.
2. manually add rule delfi.lt#$#abort-on-property-read btoa, refresh page. no ads.
3. remove rule, still no ads. now it shows that blocks rule which is in easylistlithuania)
seems like that it uses that rule only if it local(manually added, not from remote source)

**Comment by wizmak** [comment]
> I got that behaviour testing `delfi.lt#$#abort-on-property-read _dlf.ab`
> However, it's an old issue, I linked above the issue

@mapx- I see, thanks for clarification.

**Comment by mapx-** [comment]
@gymka  the snippets can be used ONLY if in local or in this special list (cv list)

**Comment by gymka** [comment]
@mapx- oh, ok. but it solves problem only for me, not for public :D

**Comment by wizmak** [comment]
> works not as expected:
> 
> 1. open browser, go to delfi.lt(easylistlithuania enabled and up to date). it shows ads.
> 2. manually add rule delfi.lt#$#abort-on-property-read btoa, refresh page. no ads.
> 3. remove rule, still no ads. now it shows that blocks rule which is in easylistlithuania
>    seems like that it uses that rule only if it local(manually added, not from remote source)

I'm not experiencing this behavior, when I remove the filters, ads are back.
However, please note that snippet filters only work if they're added locally, or to this anti-cv list.

**Comment by mapx-** [comment]
@wizmak  added the filter in cv list, see https://github.com/abp-filters/abp-filters-anti-cv/commit/2793da093da62f910a8dd4aebd81ffde8572f0c0

which is a list enabled by default for all

**Comment by gymka** [comment]
yesterday everything worked, today not works anymore :)

**Comment by mapx-** [comment]
`delfi.lt#$#abort-on-property-read __dabd`

**Comment by wizmak** [comment]
> `delfi.lt#$#abort-on-property-read __dabd`

@mapx- thanks, added.

**Comment by gymka** [comment]
today it's 
delfi.lt#$#abort-on-property-read __dabdf

i think such rules should be read and from user's list... i can write few lines of php + cron job and it will be updated daily.... it's bad workaround each few days write here....

**Comment by wizmak** [comment]
> delfi.lt#$#abort-on-property-read __dabdf

@gymka added 44f404f, thanks!
Will do my best to add suggested filters ASAP, this is the best I can do for now.

**Comment by gymka** [comment]
they changed source, i see new object '___dabdf' but old rule not works anymore... i tried `delfi.lt#$#abort-on-property-read ___dabdf` it not works, current `delfi.lt#$#abort-on-property-read __dabdf` not works too...

**Comment by mapx-** [comment]
working in uBo
`delfi.lt##+js(abort-on-property-write.js, ___dabdf)`

so try in ABP
`delfi.lt#$#abort-on-property-write ___dabdf`

**Comment by gymka** [comment]
this `rule(delfi.lt#$#abort-on-property-write ___dabdf`) works, please update in your list

**Comment by wizmak** [comment]
@mapx- @gymka 
Added, thanks!

**Comment by krystian3w** [comment]
This is remove banner "top sport"?

**Comment by gymka** [comment]
> 
> 
> This is remove banner "top sport"?

yesterday worked, today again not works. they change code each few days :)

**Comment by gymka** [comment]
there can i find all possible snipets? i mean whose abort-on-property-write, abort-on-property-read, etc.? i'll try myself to test those. today nothing from old codes not works anymore

**Comment by mapx-** [comment]
`delfi.lt##+js(abort-on-property-read.js, __dabd)`

**Comment by wizmak** [comment]
> there can i find all possible snipets? i mean whose abort-on-property-write, abort-on-property-read, etc.? i'll try myself to test those. today nothing from old codes not works anymore

@gymka 
Check [this link](https://issues.adblockplus.org/query?status=closed&keywords=~circumvention&summary=~+snippet)

**Comment by gymka** [comment]
today again it's
`delfi.lt#$#abort-on-property-write __dabdf`
don't remove older rule, maybe tuesday they will revert that :D

**Comment by gymka** [comment]
we came back to start :D again need `delfi.lt#$#abort-on-property-read _dlf.ab` ublock blocks that item, in abp not works. tried variuos things, don't know what else i can do :D

**Comment by hfiguiere** [comment]
There is a patch pending for ABP that would allow this to work. It's not in 3.5. (it's because of the '.')

**Comment by mapx-** [comment]
working in uBo
`delfi.lt##+js(abort-on-property-read.js, ___dabd)`

**Comment by gymka** [comment]
`delfi.lt#$#abort-on-property-read ___dabd` works in abp, but i think i tried it in last few days and didn't worked... code changes daily :D today this rule works

**Comment by gymka** [comment]
today 
delfi.lt#$#abort-on-property-read _dabd
is working

**Comment by gymka** [comment]
visited again this page, today line "delfi.lt#$#abort-on-property-read _dlf.ab" works, maybe tommorow wont't work again, but please add it.

**Comment by krystian3w** [comment]
Anybody can test similar:

```
||adform.net/banners/scripts/adx.js$script,rewrite=abp-resource:blank-js
```

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/41420
https://github.com/uBlockOrigin/uAssets/issues/6372

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/41420#issuecomment-537591597
