### ISSUE TITLE
freeze-element breaks the entire domain

### ISSUE THREAD

**Issue by MeFoDy** [abp-filters/abp-filters-anti-cv#570]
### List the website(s) where you encounter issues with ABP filters 

* `https://yandex.ru/search/?text=adblock&lr=213`
* `https://yandex.ru/`

### Define the problem 

When I enable both AdBlock Plus and AdBlock with ABP filters enabled (from this url: https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt) the site is broken. It's the same problem we saw here: https://github.com/abp-filters/abp-filters-anti-cv/issues/541

As far as I understand it came with this commit: https://github.com/abp-filters/abp-filters-anti-cv/commit/cd0216f510418b66f906f6654da5fbb63d8af5b8

### Screenshot(s) 

https://user-images.githubusercontent.com/1439919/108827354-9056f080-75d6-11eb-8d85-ba53850c2a6e.mp4

It should have the footer and JS working as well.

### List all of your filter lists 

Only custom filter.
```
yandex.ru#$#freeze-element .not-exists
```

Or https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt as default filter list.

### Tell us about your system configuration 

- Operating system and version: macOS 10.15.7
- Browser and version: Chrome 88.0.4324.182
- Adblock Plus version: 3.10.2
- Adblock version: 4.28.5

### Other details 

It's a critical problem for our service. This filter breaks entire domain if the user has two adblockers in his browser. And the user can't see useful content, not only the ads. Unfortunately, we can't tell our customers just use only one of adblockers.
Please, revert the commit until it's working with both of Adblock and ABP.

**Comment by b-uwe** [comment]
@MeFoDy Can you please also add the AdBlock version to the system configuration and/or recheck if it's the latest?

**Comment by MeFoDy** [comment]
> @MeFoDy Can you please also add the AdBlock version to the system configuration and/or recheck if it's the latest?

It's 4.28.5. Added to issue description. 👍

**Comment by b-uwe** [comment]
We confirm the issue and rolled back the filter! Thanks a lot for reporting @MeFoDy

**Comment by arsykan** [comment]
fixed by https://github.com/abp-filters/abp-filters-anti-cv/commit/de860e2c80652baa3bd52e2d924023533d0b5b80
