### ISSUE TITLE
autojournal.fr

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#58]
Hi,

**List the website(s) where you encounter issues with ABP filters**

```
http://news.autojournal.fr/
```

**Define the problem**

unblocked ads / circumvention 

**Screenshot**

https://vgy.me/eBmWkS.png
https://vgy.me/D24YxR.png
https://vgy.me/uDjFd7.png

**List all of your filter lists**

ABP filters
EasyList
EasyList **FR**
EasyPrivacy
Adblock Warning Removal List

**Tell us about your system configuration**

- Browser and version: Firefox 65 & Chromium 72
- Adblock Plus version: 3.4.3

**HTML & Js**
https://pastebin.com/D1rFz1JD
https://pastebin.com/HYSwJjz3

**Comment by mapx-** [comment]
@smed79  test this filter (coverted for uBo)
`autojournal.fr##+js(abort-on-property-read.js, $jscomp)`

**Comment by smed79** [comment]
Filter not working.

**Comment by smed79** [comment]
Sorry...
- ads is not block and the page is not broken
- filter tested in ABP & uBo

**Comment by mapx-** [comment]
my bad, I was testing the filter but ...together with a working one (only uBo)
`autojournal.fr##+js(setTimeout-defuser.js, (), 1)`

Could you test it ?

**Comment by smed79** [comment]
The filter works for ubo (i get no ads) but i still get [requests](https://vgy.me/xIBroq.png) from randome sub-domains.

**Comment by mapx-** [comment]
yes, very few.

**Comment by mapx-** [comment]
working filters for ABP:
```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=autojournal.fr
@@||static.doubleclick.net/instream/ad_status.js$script,domain=autojournal.fr
@@||autojournal.fr^$generichide
```

**Comment by okiehsch** [comment]
`autoplus.fr##+js(abort-on-property-read.js, PerformanceLongTaskTiming)`
works for me, so this could be converted to a adblock-snippet if it works fo you too.

**Comment by wizmak** [comment]
> `autojournal.fr,autoplus.fr##+js(abort-on-property-read.js, PerformanceLongTaskTiming)`
> works for me, so this could be converted to a adblock-snippet if it works for you too.

@okiehsch works for me, added. Thanks!
