### ISSUE TITLE
google.com

### ISSUE THREAD

**Issue by GitHub-User010** [abp-filters/abp-filters-anti-cv#581]
### List the website(s) where you encounter issues with ABP filters 

``https://www.google.com/
https://www.google.at/
https://www.google.be/
https://www.google.ch/
https://www.google.co.uk/
https://www.google.de/
https://www.google.es/
https://www.google.fr/
https://www.google.ie/
https://www.google.it/
https://www.google.nl/
https://www.google.pl/
https://www.google.pt/``

### Define the problem 

Google logo won't show up.

### List all of your filter lists 

ABP filters
Easylist Cookie List
Fanboy's Social Blocking List
EasyPrivacy
Fanboy's Annoyance List
EasyList
Fanboy's Social Blocking List

### Tell us about your system configuration 

- Operating system and version: Windows 10 64-bit 20H2 19042.804
- Browser and version: Opera GX LVL 2 (core: 73.0.3856.400)
- Adblock Plus version: 3.10.2

### Other details 

(Format: City, Region, Country.) My location is in Eindhoven, North Brabant, Netherlands.

**Comment by wizmak** [comment]
Hello @GitHub-User010,
I'm unable to reproduce this issue, maybe it was because of one of the mentioned enabled lists, and it's resolved already.
Thanks for reporting!
