### ISSUE TITLE
autoplus.fr

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#59]
Hi,

**List the website(s) where you encounter issues with ABP filters**

```
https://www.autoplus.fr/
```

**Define the problem**

unblocked ads / circumvention 

**Screenshot**

https://vgy.me/iG324A.png

**List all of your filter lists**

ABP filters
EasyList
EasyList **FR**
EasyPrivacy
Adblock Warning Removal List

**Tell us about your system configuration**

- Browser and version: Firefox 65 & Chromium 72
- Adblock Plus version: 3.4.3

**HTML & Js**
https://pastebin.com/nyrdDv9M
https://pastebin.com/tWBU5C4i

**Comment by mapx-** [comment]
test (for uBo)
`autojournal.fr,autoplus.fr##+js(setTimeout-defuser.js, (), 1)`

**Comment by mapx-** [comment]
https://github.com/abp-filters/abp-filters-anti-cv/issues/58#issuecomment-466125964

**Comment by smed79** [comment]
> test (for uBo)

The filter works.
