### ISSUE TITLE
Bit.ly Link Blocked - ads.amazon

### ISSUE THREAD

**Issue by KevinGoddard** [abp-filters/abp-filters-anti-cv#591]
### List the website(s) where you encounter issues with ABP filters 

`https://ads.amazon/*`

### Define the problem 

We are using https://ads.amazon as a "short link" for content linking to https://advertising.amazon.com - the Amazon Advertising website. Amazon Advertising provides tools and services for advertisers and marketers to promote their products on Amazon.com.

We are only using https://ads.amazon for the purposes of link shortening - mostly for our social media content.

Please let me know if you need any other information from me.

### Screenshot(s) 

NA - I can replicate if I go to this tweet https://twitter.com/AmazonAds/status/1379486317852168194 with AdBlock Plus on, it just rebounds me back to the tweet.

### List all of your filter lists 

Currently I only have ABP filters active

### Tell us about your system configuration 

- Operating system and version: MacOS Mojave 10.14.6
- Browser and version: Chrome Version 89.0.4389.114 
- Adblock Plus version: Version number 3.10.2

### Other details 

Please let me know if you need anything else from me.
Thanks!
Kevin Goddard
Head of Social Media
Amazon Advertising

**Comment by wizmak** [comment]
@KevinGoddard 
I can not reproduce this issue, and there was no filter in the anti-cv list that would cause such issue.
Let me know if the issue persists, and if this is the case, we can pair up to figure out what's happening.

**Comment by wizmak** [comment]
@KevinGoddard 
The issue could be due to a filter in [EasyList](https://github.com/easylist/easylist), can you double-check if you only have ABP filters enabled as mentioned in the issue details above?

**Comment by KevinGoddard** [comment]
﻿Thanks!
I also cannot replicate it today. I’ll let you know if I see it again.  Weird!

Kevin Goddard

From: Amr ***@***.***>
Reply-To: abp-filters/abp-filters-anti-cv ***@***.***>
Date: Wednesday, April 7, 2021 at 3:31 AM
To: abp-filters/abp-filters-anti-cv ***@***.***>
Cc: Kevin Goddard ***@***.***>, Mention ***@***.***>
Subject: Re: [abp-filters/abp-filters-anti-cv] Bit.ly Link Blocked - ads.amazon (#591)


@KevinGoddard<https://github.com/KevinGoddard>
I can not reproduce this issue, and there was no filter in the anti-cv list that would cause such issue.
Let me know if the issue persists, and if this is the case, we can pair up to figure out what's happening.

**Comment by KevinGoddard** [comment]
﻿Yup, this is the current status of my filter list. I did actually find that EasyList was blocking it last week, but they updated to allow the ads.amazon.  Thanks!


***@***.***D72B97.3DF9B4F0]
Kevin Goddard

From: Amr ***@***.***>
Reply-To: abp-filters/abp-filters-anti-cv ***@***.***>
Date: Wednesday, April 7, 2021 at 6:07 AM
To: abp-filters/abp-filters-anti-cv ***@***.***>
Cc: Kevin Goddard ***@***.***>, Mention ***@***.***>
Subject: Re: [abp-filters/abp-filters-anti-cv] Bit.ly Link Blocked - ads.amazon (#591)


@KevinGoddard<https://github.com/KevinGoddard>
The issue could be due to a filter in EasyList<https://github.com/easylist/easylist>, can you double-check if you only have ABP filters enabled as mentioned in the issue details above?

**Comment by mapx-** [comment]
yeah, it was fixed and you've acknowledged it
https://forums.lanik.us/viewtopic.php?f=64&t=45976

**Comment by wizmak** [comment]
> ﻿Yup, this is the current status of my filter list. I did actually find that EasyList was blocking it last week, but they updated to allow the ads.amazon. Thanks!

@KevinGoddard  You're welcome!
