### ISSUE TITLE
No content with adblock

### ISSUE THREAD

**Issue by TheStinkySkunk** [abp-filters/abp-filters-anti-cv#594]
### List the website(s) where you encounter issues with ABP filters 
https://designbump.com/why-are-mood-boards-important-in-web-design/
* 

### Define the problem 

This rule : 
https://github.com/abp-filters/abp-filters-anti-cv/commit/b84f904eb41d64d0aee02ce1d45b30029f5ba5e2

### Tell us about your system configuration 

- Operating system and version: 
- Browser and version: 
- Adblock Plus version:

**Comment by TheStinkySkunk** [comment]
@arsykan : As we can see, you don't check every website concerned by with rule.

**Comment by arsykan** [comment]
no problem here. content is shown normally.
