### ISSUE TITLE
Animepahe.com video player

### ISSUE THREAD

**Issue by runboy93** [abp-filters/abp-filters-anti-cv#599]
https://animepahe.com/play/c28598e0-4478-71c7-24fa-5184d3b3305f/449f201470ff9c1c2585a51c19be133eed8eb967edd3b4e0f63f6ce4f3753e6a

Video player (kwik) doesn't start correctly when anti-circumvention filterlist is activated, when disabled video player (kwik) does start normally.

**Comment by wizmak** [comment]
@runboy93 
It works the same for me with/without the anti-cv list. Let me know if the issue is still there on your end.

For the future, it would be better to stick to the issue template.
