### ISSUE TITLE
railpictures.net

### ISSUE THREAD

**Issue by jknockaert** [abp-filters/abp-filters-anti-cv#6]
### List the website(s) where you encounter issues with ABP filters 
railpictures.net
* 

### Define the problem 

When opening a picture a blocker comes up that seems to bypass the filters list, e.g.
http://railpictures.net/photo/668752/
It seems to be the eval(function(p,a,c,k,e,d)) at the bottom of the page that is triggering the blocker.

**Comment by smed79** [comment]
@jknockaert This filter list target [reinjections of ads](https://adblockplus.org/blog/newest-update-to-adblock-plus-is-a-massive-strike-against-anti-adblock-tools#c007496) no anti adblock.

PS:  _ask for help at easylist forum https://forums.lanik.us/ (use forumsearch before posting a new topic)_

**Comment by monzta** [comment]
What smed79 said.
