### ISSUE TITLE
gorodrabot.ru

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#61]
Please add a snippet `gorodrabot.ru#$#abort-on-property-read Ya`

https://ufa.gorodrabot.ru/vacancy/168317280/elektromontajnik_elektromonter_ufa
https://i.imgur.com/a3LwsFW.jpg

**Comment by wizmak** [comment]
Thanks @dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Please replace: `gorodrabot.ru#$#abort-on-property-read Ya`

To: `gorodrabot.ru#$#abort-on-property-read Object.prototype.AdvManager`
