### ISSUE TITLE
russian.txt rules blocks page on weather.rambler.ru (CV-747)

### ISSUE THREAD

**Issue by Aminoser** [abp-filters/abp-filters-anti-cv#612]
### List the website(s) where you encounter issues with ABP filters 

* https://weather.rambler.ru/v-moskve/tomorrow/  (in mobile version)

### Define the problem 

I don't see the content of the page. The reason is XPATH in CV-747: `.//div[not(@class)][not(@id)][not(@style)][string-length(text())=7]/ancestor::div[@class][4]`

### Screenshot(s) 

<img width="1790" alt="abp" src="https://user-images.githubusercontent.com/3600064/118687022-3d738a80-b80d-11eb-943a-b153bb9d4f29.png">

### List all of your filter lists 
* ABP filters

### Tell us about your system configuration 

- Operating system and version: macOS Big Sur 11.3.1
- Browser and version: Google Chrome 90.0.4430.212
- Adblock Plus version: 3.10.2

**Comment by wizmak** [comment]
Hey @Aminoser , 

XPath rules, similar to all snippet filters, are not working on mobile products, only desktop, so this shouldn't be an issue.
