### ISSUE TITLE
`https://www.csid.ro/` ads

### ISSUE THREAD

**Issue by IThinkIAmCool** [abp-filters/abp-filters-anti-cv#615]
@ryanbr @monzta Could you add `||remusclerait.xyz^` or `||remusclerait.xyz^$third-party` to EasyList or ABP anti cv?

**Comment by IThinkIAmCool** [comment]
the ads are addressed in uBlock Origin's 'uBlock filters' near `! Yavli ads`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/e8591524d8a1321f93e969d75e6862a1ebc4bbf2

**Comment by IThinkIAmCool** [comment]
New domain @ryanbr

**Comment by IThinkIAmCool** [comment]
@ryanbr New domain.

**Comment by IThinkIAmCool** [comment]
@ryanbr `||renvahirions.xyz^$third-party` might be needed.
