### ISSUE TITLE
gamepedia.com

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#62]
Hi,

**List the website(s) where you encounter issues with ABP filters**

```
https://terraria.gamepedia.com/ (all gamepedia subdomains)
```

**Define the problem**

Instart Logic ads / circumvention 

**List all of your filter lists**

ABP filters
EasyList
EasyPrivacy
Adblock Warning Removal List

**Tell us about your system configuration**

- Browser and version: Firefox 65 & Chromium 72
- Adblock Plus version: 3.4.3

**Suggested fix**
```
gamepedia.com#$#abort-on-property-read I11C
```

**Comment by wizmak** [comment]
Thanks @smed79 
Suggested filter works, and added.

**Comment by smed79** [comment]
@wizmak add also
```
; abort-current-inline-script document.createElement /adb|adn|ads|adv|inject|insert/
```

**Comment by smed79** [comment]
https://github.com/uBlockOrigin/uAssets/issues/5229

**Comment by pcjtulsa** [comment]
This is causing issues where editor toolbars are not loading. Please revert.

**Comment by Jack-McKalling** [comment]
Please reopen this ticket, as by above reason

**Comment by wizmak** [comment]
@pcjtulsa @Jack-McKalling 
Please provide more details about the issue (description, screenshots, etc). You can file new issue and fill in the issue template.

**Comment by Markus-Rost** [comment]
@wizmak 
Issue created: #130
