### ISSUE TITLE
telephony.yandex.ru

### ISSUE THREAD

**Issue by makstheimba** [abp-filters/abp-filters-anti-cv#639]
### List the website(s) where you encounter issues with ABP filters 

* `telephony.yandex.ru`

### Define the problem 

All popups on our website are incorrectly blocked by this filter. These popups do not contain ads at all. Popups are used to view and edit data for entities on our website.

### Screenshot(s) 

Here is one popup that allows our clients to add tags:
![image](https://user-images.githubusercontent.com/6356324/125601790-c837e997-4182-4f95-9ef5-efdb2ab44f54.png)
And with adblock enabled this same popup is completely unusable:
![image](https://user-images.githubusercontent.com/6356324/125601838-17455c25-07ec-45e5-a7a6-7a1e42780185.png)

Another popup that allows our client to add funds to their account:
![image](https://user-images.githubusercontent.com/6356324/125601975-98bb00a6-d63c-4f95-8f48-8f9f78969070.png)
And this is how it looks with adblock:
![image](https://user-images.githubusercontent.com/6356324/125602110-9d0bd498-cb1d-4dbd-a706-84e6834d837a.png)

This filter blocks contents of our popups like this:
![image](https://user-images.githubusercontent.com/6356324/125602656-95994f20-aa61-44d0-a4c4-dccd144ed29e.png)

### List all of your filter lists 

ABP filters
EasyList

### Tell us about your system configuration 

- Operating system and version: MacOS Catalina 10.15.7
- Browser and version: Firefox 89.0.2
- Adblock Plus version: 3.11

### Other details 

Our website is in Russian and requires a registration before our users can actually start using the website. If you need access to the website please contact me and I'll provide email and password with which you can log in to our website and examine that there are indeed no ads at all

**Comment by wizmak** [comment]
@makstheimba 

I could not replicate your experience, but I excluded `telephony.yandex.ru` from all potentially relevant filters, so if the issue was due to any of the filters on the anti-cv list, it should be resolved now, please let me know how it is on your end

**Comment by makstheimba** [comment]
@wizmak Thank you very much! We don't experience issues with adblock blocking our popups anymore

**Comment by makstheimba** [comment]
@wizmak Hi! Will it be possible to also whitelist our urls that we use for internal testing? AdBlock still affects these:

`telephony-preprod.yandex.ru`
`telephony-test.yandex.ru`
`yacalls-preprod.yandex.ru`
`yacalls-test.yandex.ru`

Thank you!

**Comment by wizmak** [comment]
> Hi! Will it be possible to also whitelist our urls that we use for internal testing? AdBlock still affects these:
> 
> `telephony-preprod.yandex.ru`
> `telephony-test.yandex.ru`
> `yacalls-preprod.yandex.ru`
> `yacalls-test.yandex.ru`
> 
> Thank you!

Hey @makstheimba 
If it's for internal use only, don't you think it makes more sense to disable ABP completely (locally) on the above subdomains, this will spare you running into any potential issues in the future.
