### ISSUE TITLE
bebi.com

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#64]
Hi,

**Examples of websites**

```
http://animeland.us/
http://mangareader.net/
http://animewow.org/
http://watchcartoononline.io/
```

**Define the problem**

bebi.com ads / circumvention 

**Screenshot**

https://i.ibb.co/qND9t6s/bb1.png
https://i.ibb.co/tZXRw59/bb2.png
https://i.ibb.co/6vPBCd4/bb3.png
https://i.ibb.co/XJc87dJ/bb4.png

**List all of your filter lists**

ABP filters
EasyList
EasyPrivacy
Adblock Warning Removal List

**Tell us about your system configuration**

- Browser and version: Firefox 65 & Chromium 72
- Adblock Plus version: 3.4.3

**Bulk fix**

`
211games.com,899games.com,9anime.to,9anime.vip,anime-odcinki.pl,anime-vf.fr,anime-vostfr.net,anime1.com,animeflv.net,animehd47.com,animeindo.video,animekompi.web.id,animeland.us,animeleggendari.com,animenova.org,animeplus.tv,animereborn.net,animeresistance.com,animetoon.org,animeworld.it,animewow.org,animonline.net,anitoonstv.com,anivn.com,awsubs.co,cartoontab.com,cartoontab.net,centraldeanimes.biz,darktorrent.xyz,dmhy.org,dramagalaxy.tv,dramago.com,dubbedanime.net,easyvideo.me,freeuseporn.com,gamefz.com,gamesmega.net,gogoanime.io,gogoanime.to,goodanime.co,gooddrama.to,gum-gum-streaming.tv,heavenmanga.com,hentai-online.pl,hentaicloud.com,igg-games.com,inkanime.com,kimcartoon.to,kisscosplay.moe,kisspanda.net,kreskowkazone.pl,mangahasu.se,mangareader.net,masdoramas.net,memecenter.com,mirai.io,mmsubs.com,narutohentaidb.com,oremanga.com,pcgamestorrents.com,phimhoathinh.biz,pivigames.blog,readcomiconline.to,sandai.me,shahiid-anime.net,superanimes.site,supergoku.com,toonget.net,toonova.net,veodoramas.net,videozoo.me,watchcartoononline.io,watchcartoonsonline.eu,watchfairytail.org,watchgintama.com,watchopm.net,wow-kow.com#$#abort-on-property-read BB_ind
`

**Comment by wizmak** [comment]
> 211games.com,899games.com,9anime.to,9anime.vip,anime-odcinki.pl,anime-vf.fr,anime-vostfr.net,anime1.com,animeflv.net,animehd47.com,animeindo.video,animekompi.web.id,animeland.us,animeleggendari.com,animenova.org,animeplus.tv,animereborn.net,animeresistance.com,animetoon.org,animeworld.it,animewow.org,animonline.net,anitoonstv.com,anivn.com,awsubs.co,cartoontab.com,cartoontab.net,centraldeanimes.biz,darktorrent.xyz,dmhy.org,dramagalaxy.tv,dramago.com,dubbedanime.net,easyvideo.me,freeuseporn.com,gamefz.com,gamesmega.net,gogoanime.io,gogoanime.to,goodanime.co,gooddrama.to,gum-gum-streaming.tv,heavenmanga.com,hentai-online.pl,hentaicloud.com,igg-games.com,inkanime.com,kimcartoon.to,kisscosplay.moe,kisspanda.net,kreskowkazone.pl,mangahasu.se,mangareader.net,masdoramas.net,memecenter.com,mirai.io,mmsubs.com,narutohentaidb.com,oremanga.com,pcgamestorrents.com,phimhoathinh.biz,pivigames.blog,readcomiconline.to,sandai.me,shahiid-anime.net,superanimes.site,supergoku.com,toonget.net,toonova.net,veodoramas.net,videozoo.me,watchcartoononline.io,watchcartoonsonline.eu,watchfairytail.org,watchgintama.com,watchopm.net,wow-kow.com#$#abort-on-property-read BB_ind

@smed79 
The filter above doesn't work for me, can you check again? anyways, I pushed a fix for now for websites where I could see ads.

**Comment by smed79** [comment]
please, test

`
animeland.us,animenova.org,animeplus.tv,animewow.org,gogoanime.in,gogoanime.to,gogoanimes.co,goodanime.co,igg-games.com,kiss-anime.ws,mangareader.net,toonget.net,toonova.net,watchcartoononline.io#$#abort-on-property-read BB_atvi
`

**Comment by smed79** [comment]
The fix 30876f0 does not seems to work.

Alternative filter

`
/^https?:\/\/([0-9a-z]+\.)?(animeland\.us|animenova\.org|animeplus\.tv|animewow\.org|gogoanime1\.com|gogoanime\.in|gogoanime\.to|gogoanime\.tv|gogoanimes\.co|goodanime\.co|igg-games\.com|kimcartoon\.to|kimcartoon\.tv|kiss-anime\.ws|mangareader\.net|readcomiconline\.to|thewatchcartoononline\.tv|toonget\.net|toonova\.net|watchcartoononline\.io)\/[a-z]+\/[0-9a-zA-Z\-]{20,50}$/$script
`

**Comment by wizmak** [comment]
@smed79 thanks, added.

**Comment by smed79** [comment]
Please, change
```
/[a-z]+\/[0-9a-zA-Z\-]{20,50}$/$script
```
to
```
/[a-z]+\/[0-9a-zA-Z\-\_]{15,50}$/$script
```
