### ISSUE TITLE
One of the filters breaks drop-down menu

### ISSUE THREAD

**Issue by Astarta0** [abp-filters/abp-filters-anti-cv#641]
Hi!

Three days ago [this](https://github.com/abp-filters/abp-filters-anti-cv/commit/d20d0597cb53a909178d708c7df3cc5ad797f9ed?branch=d20d0597cb53a909178d708c7df3cc5ad797f9ed&diff=unified.) commit was created

This [weird filter](https://github.com/abp-filters/abp-filters-anti-cv/blob/master/russian.txt#L4) is based on class attribute's length, hence filter triggers on drop-down menu items with length of chars in class attribute > 50. (And I think it creates problems on different sites)
This x-path selector seems strange and practically useless ( Hope I will be heard and that will be fixed.

For users from Russia:
Из-за этого куска говна, я 4 часа потратила чтобы найти в чем проблема

**Comment by dimisa-RUAdList** [comment]
@Astarta0 
Для отладки необходим точный адрес страницы, на которой наблюдается проблема.

**Comment by Astarta0** [comment]
@dimisa-RUAdList Привет, я к сожалению не могу предоставить адрес страницы, но приложу сниппет верстки с тегами, на которых срабатывал фильтр (из-за того что попадаем в список доменов и по x-path селектору  выполняется условие, длина классов у нас на теге div 73 символа)
![image](https://user-images.githubusercontent.com/11741142/126145091-eec6be48-2bf6-4fa9-9557-4c6cd1316169.png)

**Comment by dimisa-RUAdList** [comment]
Сейчас проблема воспроизводится?

**Comment by Astarta0** [comment]
@dimisa-RUAdList для нас мы как фикс заменили тег, а так воспроизводится. Мне просто кажется, что с таким фильтром с этим может столкнуться кто угодно на указанных доменах, кто формирует классы по бэм-методологии

**Comment by dimisa-RUAdList** [comment]
Так там доменов - вагон и маленькая тележка, поэтому тем кто составляет в Eyeo эти фильтры и нужны ссылки на страницы с проблемой.

**Comment by Astarta0** [comment]
Ссылка на страницу выглядит так 
`https://praktikum.yandex.ru/trainer/thinking/lesson/9d92d185-1be2-4267-a37d-36625a5f4629/`

**Comment by dimisa-RUAdList** [comment]
Для доступа к этой странице нужна авторизация. Впрочем, и с авторизацией у меня его нет. Соответственно, авторы фильтров тоже не смогут ничего проверить.

**Comment by wizmak** [comment]
Thanks @dimisa-RUAdList for jumping in.

@Astarta0 
If there is still a problem, please file another issue and stick to the issue template. I also suggest to watch your language, even if it was in Russian.
