### ISSUE TITLE
anitokyo.tv

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#644]
Please add: `anitokyo.tv,hcdn.online#$#abort-on-property-read ClickUndercookie`

Clickunder in player after clearing cookies

Example: `https://anitokyo.tv/anime/3390-shkolyary-cenzory-wangpai-yushi.html`

And: `https://anitokyo.tv/hentai/6852-princessa-i-devushka-rycar-prezrennoe-razoblachenie-ouju-amp-onna-kishi-w-do-gehin-roshutsu.html`

See also: https://github.com/abp-filters/abp-filters-anti-cv/issues/614

**Comment by manuel-martinez-dev** [comment]
[7047ddd](https://github.com/abp-filters/abp-filters-anti-cv/commit/7047ddd2b16eeba12f920fa8f25d917d257f665c)
