### ISSUE TITLE
reuters.com - ads not blocked

### ISSUE THREAD

**Issue by srbinas** [abp-filters/abp-filters-anti-cv#65]
### List the website(s) where you encounter issues with ABP filters 

* reuters.com

### Define the problem 

I see ads (home, article)
https://uk.reuters.com/
https://uk.reuters.com/article/uk-britain-eu-vote-idUKKCN1QA0Q4

### Screenshot(s) 

https://imgur.com/4syujS9
https://imgur.com/XT9wLJY

### List all of your filter lists 

* EasyList
* EasyList Germany+EasyList
[x] Allow Acceptable Ads
[x] ABP Anti-Circumvention Filter List

### Tell us about your system configuration 

- Operating system and version: Ubuntu 18.04
- Browser and version: Version 72.0.3626.96 (Official Build) (64-bit)
- Adblock Plus version: Version number 3.4.3

### Other details 

Ads are not blocked (see screenshots).

**Comment by mapx-** [comment]
test this 1
`reuters.com#$#abort-on-property-read advBidxc`

**Comment by wizmak** [comment]
> test this 1
> `reuters.com#$#abort-on-property-read advBidxc`

doesn't work for me.

**Comment by mapx-** [comment]
Weird, working fine for me ABP / uBo (after disabling the specific uBo filter)

**Comment by wizmak** [comment]
@mapx- 
It indeed works for these ads (https://imgur.com/a/owcI3fE), not for ads reported in this issue though. 
Just pushed it, thanks!
