### ISSUE TITLE
gov.ua zone issue

### ISSUE THREAD

**Issue by fckpgn** [abp-filters/abp-filters-anti-cv#657]
Hi
There is multiple issues with websites in gov.ua. zone. 
Found "gov.ua" record in #CV-716 ( abp-filters-anti-cv Version: 202107290520 ).
Can you remove this zone from list? Note, this is not one website, this is whole DNS zone of Ukrainian Goverment.

**Comment by dimisa-RUAdList** [comment]
This entry was deleted a few hours before you posted an issue: https://github.com/abp-filters/abp-filters-anti-cv/commit/beada425c59a9c11cab8427318342f37fb5589eb

**Comment by wizmak** [comment]
@fckpgn 
What @dimisa-RUAdList said, you may need to update the list manually.
