### ISSUE TITLE
fastpic.ru

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#66]
https://fastpic.ru/view/109/2019/0121/a76cbcf2d183ae34ee207bacaecd3320.jpg.html?test

Please add a snippet `fastpic.ru#$#abort-current-inline-script document.createElement Math.random`

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Please replace: `#$#abort-current-inline-script document.createElement Math.random`
To: `#$#abort-on-property-read Ma_random`

Example: https://fastpic.ru/fullview/73/2016/0306/ec3a44581ab8b7eeedd5aa84503b9a07.jpg.html

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Something I do not find in the list of any rules for this site. Please add a snippet: `fastpic.ru#$#abort-current-inline-script document.createElement Math.random`

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Add please: `abort-on-property-read document.getElementsByTagName`

**Comment by dimisa-RUAdList** [comment]
@wizmak 
Add please: `~new.fastpic.ru`

Example: https://new.fastpic.ru/album/coFO9fBfj4

**Comment by dimisa-RUAdList** [comment]
@arsykan 
@wizmak 
Replace please:
`fastpic.ru,~new.fastpic.ru#$#abort-current-inline-script document.createElement Math.random; abort-on-property-read document.getElementsByTagName` ~>
`fastpic.ru,~new.fastpic.ru#$#abort-current-inline-script Math.random; abort-on-property-read document.getElementsByTagName; abort-on-property-read Math.floor`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@wizmak
Please add:
`fastpic.org,~new.fastpic.org#$#abort-current-inline-script Math.random; abort-on-property-read document.getElementsByTagName; abort-on-property-read Math.floor`

Example: https://fastpic.org/view/59/2015/0422/18578ba101d2697c1e8eb9287380df54.png.html

**Comment by dimisa-RUAdList** [comment]
@arsykan
@wizmak
@manuel-martinez-dev
Replace please:
`fastpic.org,~new.fastpic.org,fastpic.ru,~new.fastpic.ru#$#abort-current-inline-script Math.random; abort-on-property-read document.getElementsByTagName; abort-on-property-read Math.floor` ~>

`fastpic.org,~new.fastpic.org,fastpic.ru,~new.fastpic.ru#$#abort-current-inline-script document.querySelectorAll, popMagic; abort-current-inline-script Math.random; abort-on-property-read document.getElementsByTagName; abort-on-property-read utarget_script`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@wizmak
@manuel-martinez-dev

Fastpic.ru is no longer working, please remove the rules for this domain, to get ~ >
`fastpic.org,~new.fastpic.org#$#abort-current-inline-script document.querySelectorAll, popMagic; abort-current-inline-script Math.random; abort-on-property-read document.getElementsByTagName; abort-on-property-read utarget_script`


In addition, to prevent infinite loading, need to add ~>
`fastpic.org,~new.fastpic.org#$#abort-current-inline-script document.querySelector contentDocument`

Or even ~>
`fastpic.org,~new.fastpic.org#$#abort-on-property-read document.querySelector`

Example: `https://fastpic.org/view/117/2022/0430/_63da295d803c97bb6cecda60845a513d.jpg.html` [NSFW]

But applying these rules does not lead to a solution to the problem. Probably for the same reason as [this](https://gitlab.com/eyeo/adblockplus/abc/adblockpluscore/-/issues/413). So I don't know what to do with it.

**Comment by dimisa-RUAdList** [comment]
It looks like this is working fine ~>
`fastpic.org,~new.fastpic.org#$#override-property-read document.querySelector null`

**Comment by manuel-martinez-dev** [comment]
I will add that second filter `override`, but tbh, I cannot reproduce the issue that you reported some time ago on gitlab, for me that filter works fine... but good that it's been reported so it can be looked into.

**Comment by dimisa-RUAdList** [comment]
@manuel-martinez-dev 
Something wrong. The current rules should look like this ~>
`fastpic.org,~new.fastpic.org#$#abort-current-inline-script document.querySelectorAll, popMagic; abort-current-inline-script Math.random; abort-on-property-read document.getElementsByTagName; abort-on-property-read utarget_script; override-property-read document.querySelector null`

In addition, I see here: `https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt` two more mentions `fastpic.ru`.

As for the ticket to the gitlab, at the time of its creation, the existence of the problem was confirmed by the developers of ABP. However, the discussion after that was immediately moved to the private section. At the moment there is no problem on `animejoy.ru` due to changes in the source code of the site.

**Comment by dimisa-RUAdList** [comment]
This rule is now redundant: https://github.com/abp-filters/abp-filters-anti-cv/commit/4390d6e8dd803da62775479424cadbb15c9942b8#diff-33f308abca070c70e1412accec2aa34fae921fd2646df7bdecb6cb0980f82beaR63

Because already contained here: https://github.com/abp-filters/abp-filters-anti-cv/commit/4390d6e8dd803da62775479424cadbb15c9942b8#diff-33f308abca070c70e1412accec2aa34fae921fd2646df7bdecb6cb0980f82beaR62

**Comment by dimisa-RUAdList** [comment]
@arsykan
@wizmak
@manuel-martinez-dev
Replace please: `fastpic.org,~new.fastpic.org#$#abort-current-inline-script document.querySelectorAll, popMagic; abort-current-inline-script Math.random; abort-on-property-read document.getElementsByTagName; abort-on-property-read utarget_script; override-property-read document.querySelector null` ~>

`fastpic.org,~new.fastpic.org#$#abort-current-inline-script addEventListener DOMContentLoaded; abort-current-inline-script document.createElement Math.random; override-property-read document.querySelector null`

**Comment by dimisa-RUAdList** [comment]
@delta9A 
@wizmak 
Replace please: `override-property-read document.querySelector null` ~> `abort-current-inline-script Math.floor ExoLoader`

**Comment by dimisa-RUAdList** [comment]
@delta9A
@wizmak
Replace please: `fastpic.org,~new.fastpic.org#$#abort-current-inline-script addEventListener DOMContentLoaded; abort-current-inline-script document.createElement Math.random; abort-current-inline-script Math.floor ExoLoader;` ~>

`fastpic.org,~new.fastpic.org#$#abort-current-inline-script addEventListener DOMContentLoaded; abort-current-inline-script document.createElement Math.random; prevent-listener /click|load/ popMagic; prevent-listener getexoloader;`

This combination will work even without RU AdList.
