### ISSUE TITLE
horoscopes.rambler.ru

### ISSUE THREAD

**Issue by Aminoser** [abp-filters/abp-filters-anti-cv#660]
### List the website(s) where you encounter issues with ABP filters 

* https://horoscopes.rambler.ru/ (in new version (Switching to the new version: https://horoscopes.rambler.ru/go-to-ts/ ). All articles in https://horoscopes.rambler.ru/longread/)

### Define the problem 

In ALL articles pages in https://horoscopes.rambler.ru/longread/ blocked article content. Example urls:
- https://horoscopes.rambler.ru/horoscopes-articles/46929040-peredayte-initsiativu-partneru-lyubovnyy-goroskop-na-2-avgusta/
- https://horoscopes.rambler.ru/horoscopes-articles/46912767-vlyubimsya-kak-v-pervyy-raz-goroskop-na-2-8-avgusta/
- https://horoscopes.rambler.ru/fortune-articles/46932830-primety-na-3-avgusta-chto-nelzya-delat-v-etot-den/
- https://horoscopes.rambler.ru/horoscopes-articles/46932070-chetyre-samyh-derzkih-znaka-zodiaka/
- etc

In some articles, not only content is blocked, but also the central column in the grid: https://horoscopes.rambler.ru/horoscopes-articles/46912767-vlyubimsya-kak-v-pervyy-raz-goroskop-na-2-8-avgusta/

After I disable "ABP filters" - everything becomes normal.

### Screenshot(s) 

<img width="1789" alt="Снимок экрана 2021-08-02 в 12 50 59" src="https://user-images.githubusercontent.com/3600064/127842671-278dfeca-741e-4790-b5f3-32ddafacf36e.png">
<img width="1792" alt="Снимок экрана 2021-08-02 в 12 46 19" src="https://user-images.githubusercontent.com/3600064/127842626-777150fa-81dd-4cb4-8abc-363398a788df.png">
<img width="1791" alt="Снимок экрана 2021-08-02 в 12 39 42" src="https://user-images.githubusercontent.com/3600064/127842698-1ab6c39f-3bf2-4c51-9138-ad9812db9eb2.png">
<img width="1792" alt="Снимок экрана 2021-08-02 в 12 39 36" src="https://user-images.githubusercontent.com/3600064/127842716-8367cdff-c1d5-41c7-ae59-fe047dc5f8fc.png">
<img width="1791" alt="Снимок экрана 2021-08-02 в 12 39 07" src="https://user-images.githubusercontent.com/3600064/127842727-d2fa26b9-8609-43e8-a003-140f2f54eee4.png">

### List all of your filter lists 
* ABP filters
* RuAdList+EasyList

### Tell us about your system configuration 

- Operating system and version: macOS Big Sur 11.5.1
- Browser and version: Mozilla Firefox 90.0.2, Google Chrome 92.0.4515.107
- Adblock Plus version: 3.11.1

**Comment by arsykan** [comment]
@Aminoser thanks for reporting, I'll look into it.

**Comment by arsykan** [comment]
@Aminoser problem should be fixed by now
https://github.com/abp-filters/abp-filters-anti-cv/commit/b48106bdc214e8d13ce810b59e191a79351a90ba
