### ISSUE TITLE
Use extended CSS selectors in snippet filters?

### ISSUE THREAD

**Issue by Znunu** [abp-filters/abp-filters-anti-cv#666]
Been messing around with o2.pl trying to write a filter just for fun. Is it possible to use extended CSS selectors in snippet filters? I tried and it didn't work, but maybe I did something wrong?

I took a look at the existing filter (xpath?) as well. It looks quite complex. Is it handwritten or some tool was used?

**Comment by arsykan** [comment]
Hey @Znunu , thanks for reaching out! 
afaik, extended CSS selectors are not possible in the recent DOM structure of o2.pl as they randomize everything & mix it with content.

as for Xpath, it is handwritten.

if it is not doing the job for you anymore please let us know. Cheers!

**Comment by Znunu** [comment]
Oh, I think the Xpath works good! Just wanted to try myself. Yes, they really went to lengths to make navigating the DOM a pain.
My approach was to combine `hide-if-contains-visible-text` with `:-abp-has()` but like I said, it doesn't seem to work

**Comment by arsykan** [comment]
I'll have another look next week using your suggestions then come back to you, thanks for the feedback!

**Comment by Znunu** [comment]
Nooooooo, I wanna do it myself. Just curious if it's possible to combine those two.

**Comment by arsykan** [comment]
if you mean combine them in the same filter, you can not combine both as they have different syntax
`#?#` for Element hiding emulation (Extended CSS selector) e.g.  `#?#:-abp-has()`
and
`#$#` for Snippet filter

**Comment by Znunu** [comment]
Ah, that's really too bad

**Comment by arsykan** [comment]
if you want, you can start to learn Xpath & use it, it does not have to be a complicated filter to hide ads

here you go!
https://developer.mozilla.org/en-US/docs/Web/XPath
https://devhints.io/xpath

I'll close the issue then.
Cheers!
