### ISSUE TITLE
zoznam.sk

### ISSUE THREAD

**Issue by oliverfindl** [abp-filters/abp-filters-anti-cv#669]
Hello,

this rule added in commit https://github.com/abp-filters/abp-filters-anti-cv/commit/63f29930690d617ca588a4a0b1f99080799e4124 somehow matches `html` and/or `body` tags on multiple subdomains of zoznam.sk domain. Please fix or remove this rule.

https://github.com/abp-filters/abp-filters-anti-cv/blob/e62000042b141dd1bf2b6ff412a7c7ed04b0c701/czech.txt#L576

Thanks.

**Comment by manuel-martinez-dev** [comment]
Hi,
thanks for reaching out!

can you provide some examples of where you're encountering problems?.

**Comment by oliverfindl** [comment]
Hello,

reported links from my colleagues:
- `https://spuntik.zoznam.sk/`
- `https://karierainfo.zoznam.sk/cl/1005025/2167143/Ranajky-pre-personalistov-uz-tento-piatok--Pozrite-si-program-podujatia`

There are far more subdomains under zoznam.sk domain, but I did not test them individually, because I'm not user of ABP.
Just reporting this issue on behalf of my colleagues, which are not github users themself.

Thanks.

**Comment by manuel-martinez-dev** [comment]
I've adjusted the filter, the issue should be resolved, lists will be updated automatically in due time.

Please get back to us if the problem persist by creating a new issue.
