### ISSUE TITLE
zoznam.sk

### ISSUE THREAD

**Issue by oliverfindl** [abp-filters/abp-filters-anti-cv#671]
Hello,

following my previous issue https://github.com/abp-filters/abp-filters-anti-cv/issues/669, changes made in commit https://github.com/abp-filters/abp-filters-anti-cv/commit/ea4c0260f7554950389c6900f40dbb78b30cd077 breaks another page on subdomain under zoznam.sk domain:

- `https://media.zoznam.sk/napiste-nam#kariera`

Thanks.

**Comment by manuel-martinez-dev** [comment]
Hi, 
thanks for reaching out.
issue should be resolved now.

regards,
