### ISSUE TITLE
mainnews.center

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#677]
**Website**
```
https://mainnews.center/
```

**Problem**

* popup**s**

**List all of your filter lists**

- ABP filters
- EasyList
- EasyPrivacy

**Comment by manuel-martinez-dev** [comment]
Hi @smed79,
I'm unable to get any popups on the site, would you be able to provide more details in order to reproduce?.
thanks

**Comment by smed79** [comment]
Currently, I am unable to reproduce.

I'm closing this issue for now.
