### ISSUE TITLE
seasonvar.re

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#68]
Please add a snippet `seasonvar.re#$#abort-current-inline-script String`

http://seasonvar.re/4449-viktoriya-3-sezon-smotret-onlayn-na-seasonvar.html
https://i.imgur.com/2z6Y7xk.jpg

**Comment by wizmak** [comment]
Can not reproduce, and seasonvar.re is completely blocked when using `RU AdList`

**Comment by dimisa-RUAdList** [comment]
When accessing from Russia, this snippet works perfectly.

**Comment by wizmak** [comment]
> When accessing from Russia, this snippet works perfectly.

I'm using a Russian VPN, still can not reproduce.
The website is fully blocked when using only `RuAdList+EasyList`, without the suggested snippet.

**Comment by dimisa-RUAdList** [comment]
I have repeatedly encountered the fact that not all things can be played using a VPN. In cases where the site breaks, this snippet should also help, preventing breakage.

**Comment by wizmak** [comment]
> https://imgur.com/a/9HpY57m

Thanks for the screen recording, added.

**Comment by dimisa-RUAdList** [comment]
@manuel-martinez-dev 
@wizmak 

Please del: `seasonvar.re`

**Comment by manuel-martinez-dev** [comment]
I did a quick check and I did not find it on the list.

**Comment by dimisa-RUAdList** [comment]
Really. Probably someone removed this snippet earlier.
