### ISSUE TITLE
ebay sponsored filter doesn't work 

### ISSUE THREAD

**Issue by ajczyzewska** [abp-filters/abp-filters-anti-cv#698]
### List the website(s) where you encounter issues with ABP filters 

` https://www.ebay.co.uk/b/Seasonal-Outdoor-Decorations/156812/bn_812430`

### Define the problem 

Looks like filter: ebay.co.uk,ebay.com,ebay.com.au#$#hide-if-contains-visible-text SPONSORED 'li.s-item' 'li.s-item span[role="text"]'  from: https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt
Doesn't hide SPONSORED content. 

### Screenshot(s) 

![Screenshot 2021-10-11 at 17 41 03](https://user-images.githubusercontent.com/36823877/136818294-274e4d94-8ba5-4aec-b538-9904c678852c.png)

### List all of your filter lists 

![Screenshot 2021-10-11 at 17 42 00](https://user-images.githubusercontent.com/36823877/136818440-60570689-514a-49a6-8d2c-b5c9800bf9e2.png)

### Tell us about your system configuration 

- Operating system and version: MacOS
- Browser and version:  Firefox  92.0.1 
- Adblock Plus version: 3.11.2 
I've tested it on ABPKit Host App with recent changes that supports snippets & elem-hide-emulation and also didn't work.

**Comment by arsykan** [comment]
Hey @ajczyzewska , I can reproduce the ads & I am on it.
