### ISSUE TITLE
Facebook pages' posts getting hidden by ABP Filters

### ISSUE THREAD

**Issue by PokemonSpears** [abp-filters/abp-filters-anti-cv#718]
### List the website(s) where you encounter issues with ABP filters 

* `` https://www.facebook.com/correointernacionalsd/``

### Define the problem 

After the latest update, AdblockPlus is hiding all the actual posts from the Facebook page.

### Screenshot(s) 

With adblock plus turned on: https://i.postimg.cc/8kXHz2Jb/Image-001.png

With adblock plus turned off (or specifically turning off ABP Filters): https://i.postimg.cc/J4yQDpjC/Image-002.png

### List all of your filter lists 

AakList (Anti-Adblock Killer)
ABP filters

### Tell us about your system configuration 

- Operating system and version: Windows 10 Home
- Browser and version: Firefox Developer Edition 95.0b10 (64-bit)
- Adblock Plus version: 3.11.2

### Other details 

It seems to be not working only with Facebook pages of stores/businesses and the likes.

Example pages that work fine: 
https://www.facebook.com/britneyspears
https://www.facebook.com/Netflixmx/

Other pages that hide content:
https://www.facebook.com/Kantocards

**Comment by DestructChen** [comment]
also noticed similar issue on facebook group posts

looks like @manuel-martinez-dev made some recent changes

**Comment by manuel-martinez-dev** [comment]
thanks for reporting!.

I've removed the problem filter [problem filter](https://github.com/abp-filters/abp-filters-anti-cv/commit/da4fa94a2044eab54820a9b096533d1be4388f81), Issue should be resolved.

Please update the filterlists.

**Comment by PokemonSpears** [comment]
Thanks!
