### ISSUE TITLE
apkmirror.com

### ISSUE THREAD

**Issue by No-ADS** [abp-filters/abp-filters-anti-cv#733]
### List the website(s) where you encounter issues with ABP filters 

`https://www.apkmirror.com/apk/telegram-fz-llc/telegram/telegram-8-2-7-release/telegram-8-2-7-android-apk-download/`

### Define the problem 

detects adblocking

### Screenshot(s) 

<details>

![2021-12-03_185037](https://user-images.githubusercontent.com/94611448/144641012-8b68edec-0d89-4402-9ae3-aebee1d3cc47.png)
![2021-12-03_185046](https://user-images.githubusercontent.com/94611448/144641017-7716f5c5-bd56-450b-bb38-07fa0ef14f3c.png)
<summary>Screen</summary>
</details>

### List all of your filter lists 

ABP filters
Adblock Warning Removal List
EasyList
RU AdList

### Tell us about your system configuration 

- Operating system and version:  Windows 8.1 x64
- Browser and version:  Google Chrome - 96.0.4664.45 
- Adblock Plus version: 3.11.4

**Comment by mapx-** [comment]
no no ... ABP cannot add filters for anti adblocking (legal reasons)

**Comment by manuel-martinez-dev** [comment]
Hello, 
thanks for the report.

As mentioned previously, the list does not handle any anti adblock messages.

I will close this issue.
