### ISSUE TITLE
cq.ru

### ISSUE THREAD

**Issue by volkv** [abp-filters/abp-filters-anti-cv#734]
Hi. Your filter blocks all content on match pages like:

https://cq.ru/matches/cs-go/308284-natus-vincere-navi-vs-g2-esports-g2-pgl-07-11-21

this filter most likely https://github.com/abp-filters/abp-filters-anti-cv/blob/cc8533cc7ca5c3acc3db653a633f6f74b68af8f4/russian.txt#L104

**Comment by manuel-martinez-dev** [comment]
Hi @volkv,

Thanks for reporting,

I've adjusted the filter, and the issue should now be fixed. do let me know if you see any other issues.

Thanks again.
