### ISSUE TITLE
go4games .ro

### ISSUE THREAD

**Issue by LikesHisComputer** [abp-filters/abp-filters-anti-cv#741]
`https://www.go4games.ro/reviews/call-of-duty-vanguard-review-19295998/` - I encountered Yavli ads

**Comment by manuel-martinez-dev** [comment]
Hello,

thanks reporting.

we'll make sure to include this site, next time we update any Yavli ads.

**Comment by BottledSoda** [comment]
ads (yavli ads?) on `https://www.9am.ro/stiri/Incredibil/354801/A-tras-prea-mult-de-clopote-si-a-fost-amendat-cu-2-000-de-euro-Isprava-unui-preot-italian.html`
