### ISSUE TITLE
kijk.nl ads not blocked anymore

### ISSUE THREAD

**Issue by KoningCo** [abp-filters/abp-filters-anti-cv#746]
I am new on Github and hope I report this correctly. For some time I have to turn AdBlock off to watch video's on the following website. I hope someone can create a code for me to block ads on during the video's on this site again.
* <https://www.kijk.nl>
   
### Define the problem 

For some time the website kijk.nl asks to turn AdBlock off. When I don't do this I can't watch a video. When I turn AdBlock off I have to watch ads before each video and about 3 times per hour during a video. Example video: <https://www.kijk.nl/programmas/beat-me-the-five-knock-outs/6AZ246Ms7at>
Maybe it are gigya ads, but I am not sure if this is the correct information you need.

### Tell us about your system configuration 

- Operating system and version:  Windows 10 Home
- Browser and version: Chrome 96.0.4664.93 (latest version)
- Adblock Plus version: 4.40.0 (11 november 2021)

List all of your filter lists
Easylist Nederlands + Easylist

**Comment by mapx-** [comment]
add

`@@||kijk.nl^$generichide`

or disable ABP and use uBO (uBlock Origin adblocker)

ABP cannot add anti adblocking filters

**Comment by manuel-martinez-dev** [comment]
Hi,
thanks for your report.

unfortunately, due to legal reasons we're unable to tackle any anti-adblock walls.
