### ISSUE TITLE
ABP anti-cv filters blocking YouTube Shorts.

### ISSUE THREAD

**Issue by Pathduck** [abp-filters/abp-filters-anti-cv#750]
### List the website(s) where you encounter issues with ABP filters 

* `https://www.youtube.com/shorts/HPRAFjMXuG8`

### Define the problem 

Requests to `googlevideo.com/videoplayback` are blocked by ABP anti-cv list for YT Shorts.

### Screenshot(s) 

https://i.imgur.com/PbW8So7.png

### List all of your filter lists 

ABP filters
EasyList
Allow nonintrusive advertising

### Tell us about your system configuration 

- Operating system and version: 
Windows 10 x64 21H2

- Browser and version: 
Vivaldi 5.0.2497.28 (Stable channel) (64-bit)

- Adblock Plus version: 
3.11.4

### Other details 

https://reports.adblockplus.org/88a2623b-906a-4296-8ae7-b2afe38f78eb

Caused by the rule:
`||googlevideo.com/videoplayback?*&ctier=*$xmlhttprequest,domain=www.youtube.com|m.youtube.com|music.youtube.com`

The XHR requests to Googlevideo all contain a `ctier` argument.

https://github.com/abp-filters/abp-filters-anti-cv/blob/master/mobile-anti-cv.txt

Discovered in Vivaldi which uses the ABP anti-cv rules. Tested in ABP with Vivaldi adblocker disabled.

**Comment by smed79** [comment]
@wizmak You have completely disable the blocking here !!

**Comment by Pathduck** [comment]
Yeah, I don't either see the logic in disabling the blocking completely for YT shorts. Just remove the blocks/exceptions for `googlevideo.com/videoplayback`. These requests seem to be required for video content to work.

Far as I can tell the only place these rules exist is in `mobile-anti-cv.txt`. 
Why is for instance requests containing `pfa` allowed while `ctier` blocked?

**Comment by wizmak** [comment]
@smed79 @Pathduck 
As far as I can see there are no issues, the added filter is only for `youtube.com/shorts` which users can not visit directly, but only via shorts videos. Please let me know if you experience any issues. In all cases, this is a temporary fix and should be replaced once a better one is found.

@Pathduck These rules are needed for both Mobile & desktop. Blocking `ctier` requests is essential for blocking video ads for many users for which snippet filters are sometimes not effective, and allowing `pfa` requests was to fix an issue reported a while back.

**Comment by Pathduck** [comment]
> In all cases, this is a temporary fix and should be replaced once a better one is found.

Thanks for the explanation 👍 

It seems to work fine here for me. I don't actually use the Shorts myself (they destroy the brain...) 
I reported the issue for another user who discovered that the videos were not working in Vivaldi with the adblocker enabled.

**Comment by wizmak** [comment]
@Pathduck Sure, thank you for reporting!
