### ISSUE TITLE
Problem with filter on Facebook

### ISSUE THREAD

**Issue by solitaire2511** [abp-filters/abp-filters-anti-cv#764]
Hi, I use Firefox (v95.0.2) with ABP+ (v3.11.4) and I just found a problem with ABP-filter-anti-cv.

When I enable your filer list, systematically the second publication is missing/hidden.
I disable only your list and directly the second publication appears.
I've tried on my FB profile, friends profiles or group and it's everywhere the same problem.

Thanks in advance to correct this issue in the next update.

Best regards,
Soliatire2511

**Comment by arsykan** [comment]
Hi, @solitaire2511 thanks for reporting this, could you give us more info about the issue? I don't follow what does the second publication means?

Cheers

**Comment by solitaire2511** [comment]
Hi aryskan, I mean the second post on the timeline.

Thanks

**Comment by solitaire2511** [comment]
here are 2 print screens with and without filter, you can see that the post of 24 December is not visible. that was the second post on the timeline. it doesn't concern only my posts but any posts of any profile (group, friends' timeline) I've blurred the names but not the dates. Please let me know if you need more info.

![pixiz-29-12-2021-13 34 04](https://user-images.githubusercontent.com/91852162/147663837-ab3f26ff-91f3-41cc-844c-1f679765a46d.jpg)

**Comment by arsykan** [comment]
@solitaire2511 this is really helpful, thanks! we are on it.

**Comment by arsykan** [comment]
@solitaire2511 
I think this https://github.com/abp-filters/abp-filters-anti-cv/commit/f80bf427100fcd5f35ba9fa9f580105f338929ce should resolve that issue, if you could confirm after 15 min & updating the list.

**Comment by solitaire2511** [comment]
I confirm, after having updated the list, that it works.
Thank you very much for your speedy intervention, your help is much appreciated !

Kind regards

**Comment by arsykan** [comment]
happy to help
thanks for reporting! it is always appreciated.
Cheers
