### ISSUE TITLE
tv2.no

### ISSUE THREAD

**Issue by DandelionSprout** [abp-filters/abp-filters-anti-cv#772]
### List the website(s) where you encounter issues with ABP filters 

```
https://aftenposten.no
https://abcnyheter.no
https://recordere.dk
https://gastrofun.dk
https://fyens.dk
https://tilbudsuken.no
https://viborg-folkeblad.dk
https://gaffa.dk
https://jv.dk
https://tv2.no
```

### Define the problem 

I know this is a long shot, but here goes:

Inspired by `https://reports.adblockplus.org/63ddfa3a-b24a-4e8a-a838-98197ce09b47`, and by various experiences I had in 2020 and early 2021, I know there are problems with Google adding an uncloseable adblock warning stickybanner on the bottom of windows on many third-party newssites. This happens primarily to people who use I Don't Care About Cookies and who *don't* use EasyPrivacy (though it can happen when using that list too). The banner is very hard to trigger on command, but once triggered, it'll haunt the user until they clear their browser cookies.

I propose `##div[style^="bottom: 0px;"][style*="width: 10"][style*="z-index: 2147"]` as a generic entry. I've used that with success in the uBO and AdGuard versions of *Dandelion Sprout's Nordic Filters*, but have presumed that it couldn't be used in the ABP version of that list.

### Screenshot(s) 

https://reports.adblockplus.org/63ddfa3a-b24a-4e8a-a838-98197ce09b47.png

### List all of your filter lists 

```
https://easylist-downloads.adblockplus.org/easylist.txt
https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt
https://easylist-downloads.adblockplus.org/easyprivacy.txt
https://easylist-downloads.adblockplus.org/i_dont_care_about_cookies.txt
https://easylist-downloads.adblockplus.org/fanboy-notifications.txt
https://easylist-downloads.adblockplus.org/fanboy-social.txt
https://easylist-downloads.adblockplus.org/dandelion_sprouts_nordic_filters+easylist.txt
```

### Tell us about your system configuration 

- Operating system and version: Windows 10~11
- Browser and version: Chrome 85~97
- Adblock Plus version: 3.11.x

### Other details 

The uBlock Origin team has consistently refused to recognise this banner as a problem that people can encounter, since they believe EasyPrivacy fixes it. The linked-to report above seems to disprove it.

Since *Adblock Warning Removal List* is no longer included in Adblock Plus or uBlock Origin, not even as opt-ins, I presume I have to submit this to Anti-CV instead.

**Comment by manuel-martinez-dev** [comment]
Hi @DandelionSprout,

thanks for the report.

unfortunately, due to legal reasons, we cannot block or hide any adblock wall or message users get on any given site.
