### ISSUE TITLE
Blocking burger menu

### ISSUE THREAD

**Issue by antonioiodice-reply** [abp-filters/abp-filters-anti-cv#776]
### List the website(s) where you encounter issues with ABP filters 

* generalirealestate[dot]com

### Define the problem 

Menu button (top right corner) should open on hover and click. It is currently being blocked with this list. Any idea what is causing this?

### List all of your filter lists 

This list only.

### Tell us about your system configuration 

- OS: Mac OS 12.0.1
- Browser and version: Chrome 97.0.4692.71 (x86_64)
- Adblock Plus version: 4.42.0

### Other details 
Current Location: Italy.

**Comment by manuel-martinez-dev** [comment]
Hi @antonioiodice-reply 

thanks for your report.

Please note that it is not the list that seems to be causing an issue with the menu, or the extension.

I've tried on several different browsers (opera, Firefox, Edge) with or without the extension installed/enabled/disabled and it's only on chrome that does not seem to be working, hence the problem does not stem from ABP.
