### ISSUE TITLE
spletnik.ru

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#784]
Add please: `spletnik.ru#$#abort-on-property-read noAdSample`

Ads in the side player.

Example: `https://www.spletnik.ru/culture/104770-dzhonni-depp-vernetsya-na-ekrany-v-roli-lyudovika-xv.html`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak

Please replace: `spletnik.ru#$#abort-on-property-read noAdSample`

To:
`spletnik.ru#$#abort-current-inline-script String.fromCharCode decodeURIComponent; abort-on-property-read Ya; cookie-remover bltsr`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak

Please add: `||spletnik.ru/$header=content-type=text/javascript`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak

Please replace: `spletnik.ru#$#abort-current-inline-script String.fromCharCode decodeURIComponent; abort-on-property-read Ya; cookie-remover bltsr`

To: `spletnik.ru#$#abort-on-property-read Object.prototype.createHostAsserter`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak

up!

**Comment by dimisa-RUAdList** [comment]
@manuel-martinez-dev
@wizmak

Please replace: `spletnik.ru#$#abort-on-property-read Object.prototype.createHostAsserter; abort-on-property-read Object.prototype.DlEDrf; cookie-remover bltsr;`


To: `spletnik.ru#$#abort-on-property-read document.cookie.indexOf; cookie-remover wordpress_test_cookie;`

**Comment by dimisa-RUAdList** [comment]
@manuel-martinez-dev
@wizmak

Please remove all rules. They are not needed yet. The site uses a new design.

**Comment by manuel-martinez-dev** [comment]
[Filters removed](https://github.com/abp-filters/abp-filters-anti-cv/commit/cf273335a29b89946ec4cb586cfb749c13d971ec)
