### ISSUE TITLE
NSFW exoclick script

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#80]
**Define the problem**

* exoclick script (NSFW banners / popup / popunder)
* https://github.com/sanosay/exads-adblock

**Comment by smed79** [comment]
**NSFW Websites**

`
18-teen-xxx.com,18teenporno.tv,18tubehd.com,22pixx.xyz,24pornvideos.com,2japaneseporn.com,3prn.com,429tube.com,4asianporn.com,4tube.com,5299.tv,8teenxxx.com,9gag2.com,absolugirl.com,absoluporn.com,absoluporn.es,absolutube.com,activevoyeur.com,adultvideosjapanese.com,agedvideos.com,fullhdxxx.com,gotporn.com,txxx.com,vivud.com,xcafe.com,youngsex0.com,ah-me.com,al4a-archives.com,al4a.com,allbbwtube.com,allpussypics.com,allschoolboysecrets.com,alltstube.com,alotporn.com,alrincon.com,amateur-twink.com,amateurmaturewives.com,amateurmoms.net,amateurpicsporn.com,amateurporn1.com,amateurxpictures.com,analdin.com,anyporn.com,anysex.com,area51.porn,asianhamster.com,asianxxxvideo.net,
atube.porn#$#abort-on-property-read ExoLoader
`

**Comment by smed79** [comment]
[nsfw_sites_01.txt](https://github.com/abp-filters/abp-filters-anti-cv/files/2939314/nsfw_sites_01.txt)

**Comment by wizmak** [comment]
@smed79 Thanks

**Comment by smed79** [comment]
[nsfw_sites_02.txt](https://github.com/abp-filters/abp-filters-anti-cv/files/2942750/nsfw_sites_02.txt)

**Comment by smed79** [comment]
[nsfw_sites_03.txt](https://github.com/abp-filters/abp-filters-anti-cv/files/2950248/nsfw_sites_03.txt)

**Comment by smed79** [comment]
@wizmak fyi

**Comment by smed79** [comment]
[nsfw_sites_04.txt](https://github.com/abp-filters/abp-filters-anti-cv/files/2962367/nsfw_sites_04.txt)

**Comment by smed79** [comment]
@wizmak fyi

**Comment by smed79** [comment]
[nsfw_sites_05.txt](https://github.com/abp-filters/abp-filters-anti-cv/files/2973410/nsfw_sites_05.txt)

**Comment by smed79** [comment]
@wizmak 

replace `.......#$#abort-on-property-read ExoLoader`
with ==> [fix_nsfw_sites.txt](https://github.com/abp-filters/abp-filters-anti-cv/files/3010595/fix_nsfw_sites.txt)

**Comment by wizmak** [comment]
> @wizmak
> 
> replace `.......#$#abort-on-property-read ExoLoader`
> with ==> [fix_nsfw_sites.txt](https://github.com/abp-filters/abp-filters-anti-cv/files/3010595/fix_nsfw_sites.txt)

@smed79 there seems to be some typos, can you check the file?

**Comment by wizmak** [comment]
Ping @smed79

**Comment by smed79** [comment]
typos fixed https://pastebin.com/raw/LGeeHh7B

**Comment by smed79** [comment]
[update_nsfw_sites.txt](https://github.com/abp-filters/abp-filters-anti-cv/files/3194662/update_nsfw_sites.txt)

**Comment by smed79** [comment]
@wizmak fyi

**Comment by smed79** [comment]
@mile-ne

**Comment by mile-ne** [comment]
Thanks for the addition!

These domains were not added since: 
iesfafe.pt, ciclopoli.de, city-data.com, ilemi.co, ; all chrono24 domains don't have the exoclick script
ilix.in; eq-igl.ac.cn - domain offline

**Comment by smed79** [comment]
add : `nsfwalbum.com` (**nsfw**)

**Comment by mile-ne** [comment]
@smed79 removed some other domains that were offline or not having exoclick script. l

**Comment by smed79** [comment]
add `pornsouls.com` (nsfw)

**Comment by smed79** [comment]
add `sexmoza.com`

**Comment by smed79** [comment]
@wizmak add `beeg.com` (nsfw) and `oral-amateure.com` (nsfw)

**Comment by smed79** [comment]
@wizmak add `spankwire.com` (nsfw)

**Comment by smed79** [comment]
add also `extremetube.com`

**Comment by smed79** [comment]
@wizmak add `sexy-youtubers.com` (nsfw)

**Comment by smed79** [comment]
add `tbib.org` (nsfw)

**Comment by smed79** [comment]
@wizmak add `aflamsexnek.com` (nsfw)

**Comment by smed79** [comment]
add `realgfporn.com` (nsfw)

**Comment by smed79** [comment]
@wizmak check attached file for new sites.

[nsfw_sites_exoclick.txt](https://github.com/abp-filters/abp-filters-anti-cv/files/4273304/nsfw_sites_exoclick.txt)

**Comment by smed79** [comment]
@wizmak Please add
```
porndollz.com
xnxxvideo.pro
xvideosxporn.com
famuathletics.com
porndollz.com
```
add also 
```
xnxxvideo.pro,xvideosxporn.com,porndollz.com#$#abort-on-property-read open
xxxhdporno.net,indianpornvideo.org,hindixxxvideos.net#$#abort-on-property-read decodeURI
```

**Comment by smed79** [comment]
add (nsfw sites)
```
3movs.com
upornia.com
```
add also (for the popunder)
```
pornj.com,upornia.com#$#abort-on-property-read encodeURI
```

**Comment by smed79** [comment]
@wizmak please add `porn300.com` and `pornhail.com` (**nsfw**)

add also `; abort-on-property-read aNB`

**Comment by wizmak** [comment]
@smed79 
> add also `; abort-on-property-read aNB`

This didn't work for me, added anyways.

**Comment by smed79** [comment]
please, add 

```
pictoa.com
filmpornofrancais.fr
```
