### ISSUE TITLE
samelectric.ru

### ISSUE THREAD

**Issue by dimisa-RUAdList** [abp-filters/abp-filters-anti-cv#854]
Add please: `samelectric.ru#$#abort-on-property-read XMLHttpRequest`

Endless requests to `rotarb.bid`

Example: `https://samelectric.ru/powersupply/pochemu-luchshe-stavit-avtomaty-s-harakteristikoj-v.html`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak

Add please: `pro100hobbi.ru#$#abort-on-property-read XMLHttpRequest`

Example: `https://pro100hobbi.ru/kak-ssit-komplekt-postelnogo-bela-svoimi-rukami-cast-1/`

**Comment by dimisa-RUAdList** [comment]
@arsykan
@manuel-martinez-dev
@wizmak

Add please: `vibir.ru#$#abort-on-property-read XMLHttpRequest`

Example: `https://vibir.ru/faq/nastrojka-vajbera`

**Comment by dimisa-RUAdList** [comment]
@manuel-martinez-dev
@wizmak

Add please: `publy.ru#$#abort-on-property-read XMLHttpRequest`

Example: `https://www.publy.ru/post/58412`

**Comment by dimisa-RUAdList** [comment]
@manuel-martinez-dev
@wizmak

Up!

**Comment by dimisa-RUAdList** [comment]
@manuel-martinez-dev
@wizmak

Add please: `its-kids.ru#$#abort-on-property-read XMLHttpRequest`

Example: `https://its-kids.ru/vosmaya-nedelya-beremennosti.html`

**Comment by dimisa-RUAdList** [comment]
@manuel-martinez-dev
@wizmak

Add please: `coderlessons.com#$#abort-on-property-read XMLHttpRequest`

Example: `https://its-kids.ru/vosmaya-nedelya-beremennosti.html`

**Comment by dimisa-RUAdList** [comment]
@Aslatiel 
@delta9A 

Please add: `tvcenter.ru`

Example: `https://tvcenter.ru/zvezdy/poslednyaya-informatsiya-o-sostoyanii-romana-kostomarov/`

**Comment by delta9A** [comment]
Hi @dimisa-RUAdList filter would block the comment field. Could you please give us more insights to what should be blocked? Thank you. 
<img width="838" alt="cf2" src="https://user-images.githubusercontent.com/121119167/234527702-e9b3bcc3-764b-4c5e-9dc3-937f9ddd573b.png">

**Comment by dimisa-RUAdList** [comment]
Really. No need to add anything, I'd rather block `tvcenter.ru/wp-content/1j9gg.js` for now.

**Comment by dimisa-RUAdList** [comment]
@Aslatiel
@delta9A

Please add: `tehnobzor.ru`

Example: `https://tehnobzor.ru/telefony/obzor-xiaomi-redmi-12c/`

**Comment by dimisa-RUAdList** [comment]
@Aslatiel
@delta9A

Please add: `100popugaev.ru`

Example: `https://100popugaev.ru/polezno/kakuju-pticu-podarit-shkolniku`
