### ISSUE TITLE
rarbg.to

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#89]
**Website**

* rarbgweb.org, rarbgunblock.com, rarbgto.org, rarbgmirror.xyz, rarbgdata.org, rarbggo.org ...

**Define the problem**

* transparent overlay ad link

**Screenshot**

* https://vgy.me/87Tlet.png

**Fix**
`
rarbg.to,rarbg2019.org,rarbgaccess.org,rarbgdata.org,rarbgget.org,rarbggo.org,rarbgmirror.com,rarbgmirror.org,rarbgmirror.xyz,rarbgmirrored.org,rarbgproxy.org,rarbgprx.org,rarbgto.org,rarbgunblock.com,rarbgweb.org#$#abort-on-property-read LieDetector
`

**Comment by mapx-** [comment]
@wizmak it's simpler getting ublock filters automatically for the existent snippets.
