### ISSUE TITLE
Recaptcha challenge blocked on "voiranime.com"

### ISSUE THREAD

**Issue by MK1338** [abp-filters/abp-filters-anti-cv#916]
Website :

Link 1 (NSFW ads) : https://voiranime.com/anime/yami-shibai-10/yami-shibai-10-01-vostfr/

For Link 1 :
Problem : Google recaptcha challenge is blocked and can't confirm captcha solve
Screenshot(s)
Captcha : https://i.gyazo.com/064ab266c2d821596fbcf857ab3da91e.png

List all of your filter lists:
ABP filters
Liste FR+EasyList
Allow nonintrusive advertising

Configuration :

Windows 10
Google Chrome Version 100.0.4896.75 (Official Build) (64-bit)
Other details
Problem is happening with ublockOrigin and Adblock and Adblockplus

**Comment by MK1338** [comment]
Same problem happening again with this filter list : "ABP filters" (disabling that filter fix the problem)

**Comment by wizmak** [comment]
@MK1338 I removed the problematic filter, this should be fixed now. I can see there are some nasty popups, will have a deeper look when possible. Thanks for reporting.
