### ISSUE TITLE
Remove rule czech.txt

### ISSUE THREAD

**Issue by herrdickinson** [abp-filters/abp-filters-anti-cv#917]
### List the website(s) where you encounter issues with ABP filters 

* www.seznamzpravy.cz

### Define the problem 

New set of rules: https://github.com/abp-filters/abp-filters-anti-cv/pull/913 is killing the website.
Please remove these rules.

### Screenshot(s) 

If I click on any menu button:
![image](https://user-images.githubusercontent.com/103173784/162142736-4a180d93-69bf-41a1-a9a9-65837868df97.png)
I always get this:
![image](https://user-images.githubusercontent.com/103173784/162142993-5206307e-bb6c-468c-b8a9-eb330c5bc642.png)

### Tell us about your system configuration 

- Operating system and version: Windows 10
- Browser and version: Chrome 100.0.4896.75
- Adblock Plus version: 3.12

**Comment by wizmak** [comment]
Hey @herrdickinson , thanks for reporting.
I removed the responsible rule, please let me know if the site works normally for you too, just give ~10 minutes for the change to be live, then update your list manually.

**Comment by herrdickinson** [comment]
it seems like its working right now, thanks
