### ISSUE TITLE
Videos are not working on www.seznamzpravy.cz

### ISSUE THREAD

**Issue by herrdickinson** [abp-filters/abp-filters-anti-cv#919]
### List the website(s) where you encounter issues with ABP filters 

* www.seznamzpravy.cz

### Define the problem 

Videos are not working on seznamzpravy.cz. When I click on them, nothing happens. It is due to https://github.com/abp-filters/abp-filters-anti-cv/pull/913 Probably by blocking message event. It is not wise to block it, because without it, most websites wont normally work.

### Screenshot(s) 

![image](https://user-images.githubusercontent.com/103173784/162405717-883be57e-77a2-400d-b7bf-265a71977c3a.png)

### Tell us about your system configuration 

- Operating system and version: Windows 10
- Browser and version: Chrome 100.0.4896.75
- Adblock Plus version: 3.12

**Comment by wizmak** [comment]
@herrdickinson I removed two problematic filters, it should work fine now, let me know please how it looks on your end. Thanks!
