### ISSUE TITLE
Unable to download with adblock.

### ISSUE THREAD

**Issue by FaggotGay** [abp-filters/abp-filters-anti-cv#925]
### List the website(s) where you encounter issues with ABP filters 

* http://bluemediafiles.com/url-generator.php?url=onAhF5ZLCDGjfP3AAUIv/XlRmDn+wudFEkfnJ7uEgBcw/+nrsiud6qHp1oPQrbQ+X9yO6knu6qhg7fmYB5jUIhq/cQLY5q1Mtf+JQdTc/8KH8ct+UJ1LHdQLfvA9K6AB

### Define the problem 

Unable to access the download button using adblock.

Working anti-adblock.

**Comment by FaggotGay** [comment]
Hurry up because the account is going to get flagged and removed.

**Comment by manuel-martinez-dev** [comment]
Hello,
thanks for the report.

Due to legal reasons we're unable to handle this request, the list does not manage any anti adblock messages.

I will close this issue.
