### ISSUE TITLE
Unable to download with adblock

### ISSUE THREAD

**Issue by FaggotGay** [abp-filters/abp-filters-anti-cv#926]
### List the website(s) where you encounter issues with ABP filters 

* Megaup.net

### Define the problem 

Megaup is a mess, working anti-adblock,

**Comment by FaggotGay** [comment]
Hurry up because the account is going to get flagged and removed.

**Comment by manuel-martinez-dev** [comment]
Hello,
thanks for the report.

Due to legal reasons we're unable to handle this request, the list does not manage any anti adblock messages.

I will close this issue.
