### ISSUE TITLE
Make it official?

### ISSUE THREAD

**Issue by zpfzezefuhzeifu** [abp-filters/abp-filters-anti-cv#928]
You are invited as moderator, just send a modmail to /r/adbockp

**Comment by zpfzezefuhzeifu** [comment]
Just to make it the official ABP sub

**Comment by manuel-martinez-dev** [comment]
Hello,

as mentioned previously [here](https://github.com/abp-filters/abp-filters-anti-cv/issues/927)... there's is no need for this reddit page.

thanks again for the suggestion.
