### ISSUE TITLE
popups - torcidatricolor.tv - player: kastream

### ISSUE THREAD

**Issue by mapx-** [abp-filters/abp-filters-anti-cv#93]
example link: `http://www.torcidatricolor.tv/bbb.php`

working filters:
```
kastream.biz#$#abort-on-property-write _pop
kastream.biz#$#abort-on-property-write Fingerprint2
kastream.biz#$#abort-on-property-write AaDetector
```

reported here: https://adblockplus.org/forum/viewtopic.php?f=1&t=64175&p=186123#p186123

**Comment by smed79** [comment]
If i add block admeasures third party popup script
`http://qjjto.com/c2/4c/9e/c24c9e7391d531923b9ff444c8a9565c.js`
the suggested filters won't work https://vgy.me/0ZGo7X.png

do you know why?

**Comment by wizmak** [comment]
The suggested filters don't work for some reason, do they still work?

**Comment by mapx-** [comment]
well, indeed, today does not work anymore.
In uBo => still working. So, you should ask @mjethani, @hfiguierre why this difference.

However, these ones seem working
```
||torcidatricolor.tv/*.gif$image
kastream.biz#$#abort-on-property-write open
```

**Comment by wizmak** [comment]
> ||torcidatricolor.tv/*.gif$image
> kastream.biz#$#abort-on-property-write open

@mapx- works, thanks!
