### ISSUE TITLE
[NSFW] https://cambro.tv/

### ISSUE THREAD

**Issue by felippesantos46** [abp-filters/abp-filters-anti-cv#931]
### List the website(s) where you encounter issues with ABP filters 

* https://cambro.tv/

### Define the problem 
Popunders (to Chaturbate)

### Screenshot(s) 
<img width="1212" alt="Screenshot 2022-04-13 at 10 20 09" src="https://user-images.githubusercontent.com/65717387/163132554-d5e6b3bc-9435-4424-aa48-3cd06d9cd6bf.png">

**Comment by dimisa-RUAdList** [comment]
**Add**:
```
cambro.tv#$#abort-current-inline-script crakPopInParams; abort-on-property-read onload
cambro.tv###kt_player > a[href][target="_blank"]
```
**Del**:
`cambro.tv#$#override-property-read flashvars.popunder_url null` (ABP filters)
