### ISSUE TITLE
https://repelishd.me/

### ISSUE THREAD

**Issue by felippesantos46** [abp-filters/abp-filters-anti-cv#932]
### List the website(s) where you encounter issues with ABP filters 

* https://repelishd.me/

### Define the problem 
Return to previous page if devtools is opened
Movie banner page- > Player page
Player page - > Movie banner page

### Screenshot(s) 
maybe at:
<img width="1223" alt="Screenshot 2022-04-13 at 11 10 51" src="https://user-images.githubusercontent.com/65717387/163142281-0ea2e64e-4ce5-4b17-a6b4-23c5a9c577db.png">

**Comment by dimisa-RUAdList** [comment]
`||cdn.jsdelivr.net/npm/disable-devtool@latest/disable-devtool.min.js$script,domain=players.repelishd.me`

**Comment by manuel-martinez-dev** [comment]
hey @felippesantos46 

We tend not to add filters that prevent/disrupt the page when opening dev tools, but indeed if we block the script called `/disable-devtool.min.js` it should disable this annoying feature and it could help you in checking the site for any other issues.

**Comment by felippesantos46** [comment]
@dimisa-RUAdList @manuel-martinez-dev my bad, i didn't realise that script 😅, sure it would be more for teste purposes! i'm going to return to this one later on!

Thank you and have a nice one !
