### ISSUE TITLE
[NSFW] https://sexdiaryz.xyz/

### ISSUE THREAD

**Issue by felippesantos46** [abp-filters/abp-filters-anti-cv#934]
### List the website(s) where you encounter issues with ABP filters 

* https://sexdiaryz.xyz/

### Define the problem 
Popunders

### Screenshot(s) 
<img width="1140" alt="Screenshot 2022-04-14 at 09 54 07" src="https://user-images.githubusercontent.com/65717387/163339870-e3a7125d-b2b2-465f-884b-c84da483da98.png">
<img width="477" alt="Screenshot 2022-04-14 at 09 54 16" src="https://user-images.githubusercontent.com/65717387/163339902-152b4aa0-de3d-4855-8bd9-61ff7f3aaf30.png">

**Comment by dimisa-RUAdList** [comment]
I don't see the need to use snippets. Enough:
`$third-party,script,domain=sexdiaryz.xyz`
and
`sexdiaryz.xyz##a[href^="//mage98rquewz.com/"]` or even `##a[href^="//mage98rquewz.com/"]`

**Comment by stephenhawk8054** [comment]
@hoang-rio Sorry, can you take a look at this site? Maybe it can be added to ABPVN.
