### ISSUE TITLE
fileflares.com

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#97]
**Website**

* http:\/\/fileflares.com/0kamhesr7ekh
* http:\/\/fflares.com/wtgwu4t7j6w1

**Problem**

* popups

**Fix**
```
fileflares.com,fflares.com#$#abort-on-property-read decodeURI
fileflares.com,fflares.com#$#abort-on-property-write _pop
```

**Comment by smed79** [comment]
@mapx- Please test the suggested filter in ABP.

**Comment by wizmak** [comment]
@smed79 can't reproduce popups, are there any preconditions?

**Comment by wizmak** [comment]
> @smed79 can't reproduce popups, are there any preconditions?

@smed79 never mind this comment.

The **Free Download** button doesn't work with the suggested filters.

**Comment by mapx-** [comment]
"for whatever odd reason the whole button isn't clickable just the left side"
